#import "../templates/conf.typ": *

#show: template.with(
  title: "Helix 편집기 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 설치 (Installation)
== 1.1 패키지 매니저
- `brew install helix` (macOS/Linux)
- `pacman -S helix` (Arch)
- `dnf install helix` (Fedora)
- `apt install helix` (PPA: `maveonair/helix`)
- `choco install helix` (Windows)

== 1.2 소스에서 빌드
- `git clone https://github.com/helix-editor/helix`
- `cargo install --path helix-term --locked`

= 2. 사용법 (Usage)
== 2.1 레지스터 (Registers)
사용법: `"` + `<문자>` + `<동작>` (예: `"ay`).

=== 사용자 정의 레지스터
- `"ay`: 현재 선택 영역을 레지스터 `a`에 복사(Yank).
- `"op`: 레지스터 `o`의 내용을 선택 영역 뒤에 붙여넣기.
- `"hc`: 영역을 `h`에 저장하고 변경 (삭제 후 삽입 모드).
- `"md`: 영역을 `m`에 저장하고 삭제.

=== 기본 레지스터
- `/`: 마지막 검색 패턴.
- `:`: 마지막으로 실행한 명령어.
- `"`: 마지막으로 복사(Yank)한 텍스트.
- `@`: 마지막으로 기록된 매크로.

=== 특수 레지스터
- `_`: 블랙홀 레지스터. 모든 값이 버려짐.
- `#`: 선택 영역 인덱스 (1, 2, 3...). 읽기 전용.
- `.`: 현재 선택 영역들의 내용. 읽기 전용.
- `%`: 현재 파일 이름. 읽기 전용.
- `+`: 시스템 클립보드와 연동 (복사/붙여넣기).
- `*`: 기본(Primary) 클립보드와 연동 (복사/붙여넣기).

== 2.2 서라운드 (매치 모드 `m`)
`vim-sandwich`에서 영감을 받았습니다. 카운트 및 다중 선택을 지원합니다.

- `ms<문자>`: 선택 영역에 서라운드 *추가*.
- `mr<기존><신규>`: 가장 가까운 서라운드 *교체*.
- `md<문자>`: 가장 가까운 서라운드 *삭제*.
- *활용 예*: `%` (전체 선택) -> `s` (분할) -> `use` 입력 -> `mr([` (`(use)`를 `[use]`로 일괄 교체).

== 2.3 텍스트 오브젝트 (매치 모드 `m`)
- `ma`: 오브젝트 *주변* 선택 (구분자 포함).
- `mi`: 오브젝트 *내부* 선택 (구분자 제외).

=== 오브젝트 키
- `w`, `W`: 단어(word), 공백 구분 단어(WORD).
- `p`: 단락(paragraph).
- `(`, `[`, `{`, `'`, `"`: 지정된 서라운드 쌍.
- `m`: 가장 가까운 서라운드 쌍.
- `f`, `t`: 함수(function), 타입 또는 클래스(type/class). (TS)
- `a`: 인자/매개변수(argument/parameter). (TS)
- `c`: 주석(comment). (TS)
- `T`: 테스트(test). (TS)
- `g`: 변경 사항(change).

== 2.4 구문 인식 이동 (TS)
구문 트리(Syntax Tree) 상의 위치에 따라 선택 영역을 제어합니다.

- `Alt-o`: 부모 노드로 선택 영역 *확장*.
- `Alt-i`: 자식 노드로 선택 영역 *축소*.
- `Alt-p`: *이전* 형제 노드로 이동.
- `Alt-n`: *다음* 형제 노드로 이동.
- `Alt-a`: 모든 형제 노드 선택.

== 2.5 피커 (스페이스 모드)
=== 주요 피커
- `f`, `F`: 파일 피커 (루트, 현재 디렉토리).
- `b`: 버퍼 피커.
- `j`: 점프리스트 피커.
- `s`, `S`: 심볼 피커 (문서, 작업 공간).
- `d`, `D`: 진단 정보 (문서, 작업 공간).
- `/`: 글로벌 검색 (Global search).
- `a`: 코드 액션.
- `k`: Hover docs.

=== 피커 상호작용
- *필터링*: 대부분 `fzf` 방식의 퍼지 매칭을 지원합니다.
- *정규식*: 글로벌 검색 피커는 정규식을 사용합니다.
- *컬럼 필터링*: %prefix (예: %p .toml은 경로에 .toml 포함 항목만 필터링).
- *레지스터 삽입*: Ctrl-r + <문자>로 레지스터 내용을 삽입.
- *빠른 글로벌 검색*: Space + / -> Enter 시 현재 검색 레지스터(/) 내용으로 즉시 검색.

== 2.6 키맵 (일반 모드)
=== 이동 (Movement)
- `h`, `j`, `k`, `l`: 좌, 하, 상, 우 이동.
- `w`, `b`, `e`: 다음/이전 단어 시작, 단어 끝 이동.
- `W`, `B`, `E`: 공백 구분 단어 단위 이동.
- `f`, `F`, `t`, `T`: 문자 찾기 (여러 줄 지원).
- `G`: 특정 줄 <n>으로 이동.
- `Home`, `End`: 줄의 시작과 끝으로 이동.
- `Ctrl-u`, `Ctrl-d`: 반 페이지 위, 아래로 스크롤.
- `Ctrl-i`, `Ctrl-o`: 점프리스트 앞, 뒤로 이동.

=== 수정 (Changes)
- `i`, `a`: 삽입, 추가.
- `I`, `A`: 줄 시작, 끝에 삽입.
- `o`, `O`: 아래, 위에 새 줄 추가.
- `u`, `U`: 실행 취소, 다시 실행.
- `Alt-u`, `Alt-U`: 작업 트리 기록 뒤로, 앞으로 이동.
- `y`, `p`, `P`: 복사(Yank), 뒤에 붙여넣기, 앞에 붙여넣기.
- `d`, `c`: 삭제, 변경.
- `>`, `<`: 들여쓰기, 내어쓰기.
- `=`: 코드 포맷팅 (LSP).
- `Ctrl-a`, `Ctrl-x`: 숫자 증가, 감소.

=== 선택 영역 제어 (Selection)
- `s`: 선택 영역 내 정규식 일치 항목 선택.
- `S`: 정규식 기준으로 선택 영역 분할.
- `;`: 선택 영역을 커서 위치로 축소.
- `Alt-;`: 앵커와 커서 위치 뒤집기.
- `Alt-:`: 선택 방향을 순방향으로 고정.
- `C`, `Alt-C`: 아래, 위에 커서 추가.
- `(`, `)`: 기본 선택 영역 순환.
- `%`: 파일 전체 선택.
- `x`: 현재 줄 선택/확장.
- `J`: 줄 합치기.
- `Ctrl-c`: 주석 토글.

=== 검색 (Search)
- `/`, `?`: 순방향, 역방향 검색.
- `n`, `N`: 다음, 이전 검색 결과 이동.
- `*`: 현재 선택 내용 검색 (단어 경계 포함).
- `Alt-*`: 현재 선택 내용 검색 (원문 그대로).

== 2.7 보조 모드 (Minor Modes)
- `v`: 선택/확장 모드.
- `g`: 이동 모드 (예: gh, ge, gd, gy).
- `m`: 매치 모드 (서라운드, 텍스트 오브젝트).
- `z`: 뷰 모드 (예: zz, zt, zb).
- `Ctrl-w`: 윈도우 모드 (분할, 창 이동).
- `Space`: 스페이스 모드 (피커, LSP).

== 2.8 Unimpaired (대괄호 [ ])
Navigate between structured elements (TS).

- \]d, [d: 다음, 이전 진단 정보.
- \]f, [f: 다음, 이전 함수.
- \]t, [t: 다음, 이전 타입/클래스.
- \]a, [a: 다음, 이전 인자/매개변수.
- \]c, [c: 다음, 이전 주석.
- \]T, [T: 다음, 이전 테스트.
- \]g, [g: 다음, 이전 변경 사항.
- \]Space, [Space: 아래, 위에 빈 줄 추가.

== 2.9 명령어 (Commands)
- :w, :q, :wq: 저장, 종료, 저장 후 종료.
- :e <파일>, :o: 파일 열기.
- :bn, :bp: 다음, 이전 버퍼.
- :t <테마>: 테마 변경.
- :h <명령어>: 도움말 확인.
- :tree-sitter-subtree: 구문 트리 확인.

= 3. 생태계 (Ecosystem)
== 3.1 Vim에서 전환하기
- 선택 후 동작(Selection -> Action) 패러다임.
- 여러 줄을 지원하는 f, t 이동.
- 기본 내장된 LSP 및 Tree-sitter 지원.

== 3.2 Helix 모드
- Emacs용 helix-mode.
- Zellij 터미널 멀티플렉서 기본 지원.

= 4. Configuration
== 4.1 에디터 설정 (config.toml)
```toml
theme = "nord"
[editor]
line-number = "relative"
cursor-shape.insert = "bar"
true-color = true
```

== 4.2 키 매핑 변경
```toml
[keys.normal]
"C-s" = ":w"
"C-q" = ":q"
```

= 5. 가이드 (Guides)
- Languages: languages.toml에서 LSP 정의.
- Queries: runtime/queries/ 폴더의 TS 기능 쿼리.
- Indents: 자동 들여쓰기를 위한 indents.scm.
- Injections: 혼합 언어 지원을 위한 injections.scm.
