#import "../templates/conf.typ": *

#show: template.with(
  title: "Linux 치트시트 ",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 파일 및 디렉토리 관리

- `ls`: 디렉토리의 파일 목록을 나열합니다. (`-l` 상세 정보, `-a` 숨김 파일 포함, `-h` 읽기 쉬운 단위 표시, `-t` 시간순 정렬, `-R` 하위 디렉토리 포함)
- `cd`: 작업 디렉토리를 변경합니다. (`~` 홈 디렉토리, `-` 이전 디렉토리, `..` 상위 디렉토리)
- `pwd`: 현재 작업 중인 디렉토리의 절대 경로를 출력합니다.
- `mkdir -p <path>`: 새로운 디렉토리를 생성합니다. `-p` 옵션 사용 시 중간 경로의 디렉토리도 함께 만듭니다.
- `rm`: 파일이나 디렉토리를 삭제합니다. (`-r` 재귀적 삭제, `-f` 강제 삭제, `-v` 삭제 과정 표시)
- `cp`: 파일이나 디렉토리를 복사합니다. (`-r` 디렉토리 복사, `-p` 속성 유지, `-a` 모든 속성 및 링크 유지 아카이브 모드)
- `mv`: 파일이나 디렉토리를 이동시키거나 이름을 변경합니다.
- `touch`: 빈 파일을 생성하거나 기존 파일의 타임스탬프를 현재 시간으로 업데이트합니다.
- `find <path> -type f -name "*.txt"`: 지정한 경로에서 조건(예: `.txt` 확장자)에 맞는 파일을 검색합니다.
- `grep -r "pattern" .`: 현재 디렉토리부터 하위 디렉토리까지 파일 내용 중 특정 패턴을 재귀적으로 검색합니다.
- `chmod`: 파일이나 디렉토리의 권한을 변경합니다. (`u` 소유자, `g` 그룹, `o` 기타 사용자, `+` 권한 추가, `-` 권한 제거, `rwx` 읽기/쓰기/실행 권한)
  - `chmod u+x script.sh`: 소유자에게 스크립트 실행 권한을 부여합니다.
- `chown <user>:<group> <file>`: 파일의 소유자와 그룹을 변경합니다. (`-R` 하위 항목 일괄 변경)
- `stat <file>`: 파일의 상세 정보(inode, 크기, 권한, 접근/수정 시간 등)를 표시합니다.
- `ln -s <target> <link_name>`: 대상 파일이나 디렉토리에 대한 심볼릭 링크를 생성합니다.
- `du -sh <dir>`: 디렉토리나 파일이 사용 중인 디스크 용량 요약을 확인합니다.
- `df -h`: 파일 시스템별 전체 디스크 공간 및 사용량을 사람이 읽기 쉬운 단위로 확인합니다.

= 2. 텍스트 처리 및 리디렉션

- `cat`: 파일 내용을 화면에 출력하거나 여러 파일을 하나로 연결합니다.
- `less` / `more`: 파일 내용을 페이지 단위로 끊어서 확인합니다. (`less`가 더 많은 기능을 제공하여 권장됩니다.)
- `head -n 20 <file>`: 파일의 앞부분 20줄을 출력합니다.
- `tail -n 20 <file>`: 파일의 뒷부분 20줄을 출력합니다.
  - `tail -f <logfile>`: 파일 끝에 추가되는 내용을 실시간으로 모니터링합니다. (로그 확인 시 유용)
- `sort`: 텍스트 줄을 정렬합니다. (`-n` 숫자 기준 정렬, `-r` 역순 정렬, `-k` 특정 필드 기준 정렬)
- `uniq`: 연속해서 중복되는 줄을 하나로 합칩니다. (`-c` 중복 횟수 함께 표시)
- `cut -d',' -f1-3 <file.csv>`: 특정 구분자(예: 쉼표)를 기준으로 지정한 필드만 추출합니다.
- `sed 's/old/new/g' <file>`: 스트림 편집기를 사용하여 파일 내의 특정 문자열을 찾아 치환하거나 편집합니다.
- `awk '{print $1, $3}' <file>`: 텍스트 데이터를 분석하여 지정한 열(필드)을 출력하거나 처리합니다.
- `>`: 명령어의 표준 출력을 파일로 리디렉션합니다. (기존 내용 덮어쓰기)
- `>>`: 명령어의 표준 출력을 파일 끝에 추가합니다.
- `<`: 파일의 내용을 명령어의 표준 입력으로 사용합니다.
- `2>`: 표준 에러를 파일로 리디렉션합니다.
- `&>`: 표준 출력과 표준 에러를 한꺼번에 리디렉션합니다.
- `|`: 파이프 연산자. 한 명령어의 출력을 다음 명령어의 입력으로 전달합니다.
  - `ps aux | grep "nginx"`: 실행 중인 프로세스 목록에서 "nginx"가 포함된 줄만 필터링합니다.



= 3. 시스템 정보 및 모니터링

- `uname -a`: 커널 버전, 호스트 이름 등 시스템의 전반적인 정보를 출력합니다.
- `lscpu`: CPU 아키텍처 및 상세 사양 정보를 표시합니다.
- `free -h`: 물리 메모리 및 스왑 메모리의 전체 용량과 사용량을 확인합니다.
- `top`: 현재 시스템에서 실행 중인 프로세스와 리소스 사용 상태를 실시간으로 모니터링합니다.
- `htop`: `top` 기능을 시각적으로 개선하고 인터랙티브한 조작이 가능하게 한 도구입니다. (별도 설치 필요)
- `ps aux`: 시스템에서 실행 중인 모든 프로세스의 상세 상태를 출력합니다.
- `pstree`: 프로세스 간의 부모-자식 관계를 트리 구조로 보여줍니다.
- `kill <PID>`: 특정 프로세스를 종료합니다. (`-9` 강제 종료, `-15` 정상 종료 권고)
- `pkill <name>`: 프로세스 이름을 기준으로 일치하는 모든 프로세스를 종료합니다.
- `ip addr` 또는 `ifconfig`: 네트워크 인터페이스 설정과 할당된 IP 주소를 확인합니다.
- `netstat -tulnp`: 현재 네트워크에서 수신 대기(Listen) 중인 포트와 해당 포트를 사용하는 프로세스를 확인합니다.
- `ss`: `netstat`을 대체하는 최신 네트워크 상태 확인 도구입니다.
- `uptime`: 시스템 가동 시간과 평균 부하(Load Average)를 확인합니다.
- `dmesg`: 커널의 로그 버퍼 메시지를 출력합니다. 하드웨어 관련 에러나 부팅 문제를 진단할 때 유용합니다.
- `journalctl`: systemd 로그를 조회합니다. (`-u <service>` 특정 서비스 로그, `-f` 실시간 추적)

= 4. 패키지 관리

- *Debian/Ubuntu 기반 (APT)*:
  - `apt update && apt upgrade`: 패키지 목록 갱신 및 시스템 업데이트
  - `apt install <package>`: 새 패키지 설치
  - `apt remove <package>`: 패키지 삭제
  - `apt autoremove`: 사용되지 않는 의존성 패키지 일괄 정리
  - `apt search <keyword>`: 저장소에서 패키지 검색
  - `apt show <package>`: 패키지 상세 정보 확인
- *Red Hat/CentOS/Fedora 기반 (DNF/YUM)*:
  - `dnf check-update && dnf upgrade`: 업데이트 확인 및 적용
  - `dnf install <package>`: 패키지 설치
  - `dnf remove <package>`: 패키지 제거
  - `dnf search <keyword>`: 패키지 검색
  - `dnf info <package>`: 패키지 상세 정보 조회

= 5. 사용자 및 권한 관리

- `useradd -m <username>`: 새로운 사용자를 생성하고 홈 디렉토리까지 함께 만듭니다.
- `usermod -aG <group> <user>`: 기존 사용자를 특정 그룹에 추가합니다. (예: sudo 그룹)
- `userdel -r <username>`: 사용자 계정과 해당 홈 디렉토리를 모두 삭제합니다.
- `passwd <username>`: 사용자의 비밀번호를 설정하거나 변경합니다.
- `su - <username>`: 다른 사용자 계정으로 로그인하여 해당 사용자의 환경으로 전환합니다.
- `sudo <command>`: root 권한으로 명령을 실행합니다.
- `visudo`: `/etc/sudoers` 파일을 문법 오류 없이 안전하게 편집할 때 사용합니다.

= 6. 압축 및 아카이빙

- `tar`: 여러 파일을 하나로 묶는 아카이브 도구입니다. 보통 압축 도구와 병합해 사용됩니다.
  - `tar -cvf archive.tar /path/to/dir`: 디렉토리를 묶어 아카이브 파일 생성 (압축 안 함)
  - `tar -czvf archive.tar.gz /path/to/dir`: `gzip`으로 압축하여 아카이브 생성
  - `tar -cjvf archive.tar.bz2 /path/to/dir`: `bzip2`로 압축하여 아카이브 생성
  - `tar -cJvf archive.tar.xz /path/to/dir`: `xz`로 압축하여 아카이브 생성
  - `tar -xvf archive.tar`: `.tar` 아카이브 풀기
  - `tar -xzvf archive.tar.gz`: `gzip` 압축 아카이브 해제
  - `tar -xjvf archive.tar.bz2`: `bzip2` 압축 아카이브 해제
  - `tar -xJvf archive.tar.xz`: `xz` 압축 아카이브 해제

- `gzip` / `gunzip`: 단일 파일 압축에 주로 사용됩니다.
  - `gzip file`: 파일을 압축하여 `file.gz`를 만들고 원본 파일은 삭제합니다.
  - `gunzip file.gz`: `file.gz`의 압축을 풀고 압축 파일은 삭제합니다. (`-k` 옵션으로 원본 유지 가능)

- `zip` / `unzip`: Windows 등 다른 OS와의 호환성이 뛰어납니다.
  - `zip -r archive.zip /path/to/dir`: 디렉토리를 포함하여 `.zip` 파일로 압축합니다.
  - `unzip archive.zip`: `.zip` 파일의 압축을 해제합니다.

- 기타 압축 해제:
  - `bunzip2 file.bz2`: `.bz2` 파일의 압축을 풉니다.
  - `unxz file.xz`: `.xz` 파일의 압축을 풉니다.

= 7. SSH 및 네트워크 파일 전송

- `ssh <user>@<host>`: 원격 서버에 안전하게 접속합니다.
  - `ssh -p <port> <user>@<host>`: 특정 포트를 사용해 접속합니다.
  - `ssh -i /path/to/key <user>@<host>`: 비밀번호 대신 개인키를 사용하여 접속합니다.
- `scp`: 원격 호스트와 로컬 간에 파일을 안전하게 복사합니다.
  - `scp local_file user@host:/remote/path`: 로컬 파일을 원격지로 전송
  - `scp user@host:/remote/path local_file`: 원격지 파일을 로컬로 복사
- `rsync -avz <source> <destination>`: 증분 복사를 지원하여 대량의 파일을 효율적으로 동기화합니다.

= 8. 시스템 관리 및 모니터링 고급

== 프로세스 및 작업 우선순위
- `nice -n 10 command`: 프로세스 시작 시 낮은 우선순위를 할당합니다.
- `renice 5 -p <PID>`: 이미 실행 중인 프로세스의 우선순위를 동적으로 변경합니다.
- `ionice -c 1 -n 4 command`: 디스크 입출력(I/O) 우선순위를 설정합니다.
- `taskset -c 0,1 command`: 특정 CPU 코어만 사용하도록 프로세스 실행을 제한합니다.
- `chrt -f 50 command`: 실시간(Real-time) 스케줄링 정책을 적용합니다.
- `pgrep -f "pattern"`: 이름이나 명령줄 패턴과 일치하는 프로세스 ID를 찾습니다.
- `pkill -f "pattern"`: 패턴과 일치하는 모든 프로세스를 종료시킵니다.
- `killall process_name`: 특정 이름을 가진 모든 프로세스를 일괄 종료합니다.
- `kill -0 <PID>`: 실제 종료하지 않고 프로세스가 현재 실행 중인지 여부만 확인합니다.

== 시스템 자원 심층 분석
- `iostat -x 1`: 디스크 I/O 통계 정보를 1초 간격으로 상세히 보여줍니다.
- `iotop`: 프로세스별 실시간 디스크 I/O 사용량을 확인합니다.
- `vmstat 1`: 가상 메모리 사용 통계를 실시간으로 확인합니다.
- `sar -u 1`: CPU 사용률의 변화 추이를 확인합니다.
- `sar -r 1`: 메모리 사용률의 변화 추이를 확인합니다.
- `sar -d 1`: 디스크 활동 내역 통계를 확인합니다.
- `lsof -i :80`: 80번 포트를 현재 점유하고 있는 프로세스를 찾습니다.
- `lsof -p <PID>`: 특정 프로세스가 현재 열고 있는 모든 파일 목록을 확인합니다.
- `fuser -v /path/to/file`: 특정 파일을 사용 중인 프로세스 정보를 확인합니다.
- `strace -p <PID>`: 실행 중인 프로세스가 발생시키는 시스템 콜을 실시간으로 추적합니다.

== 고급 로그 분석
- `journalctl -u service_name`: 특정 서비스의 로그만 필터링하여 확인합니다.
- `journalctl -f`: 실시간으로 추가되는 시스템 로그를 계속 모니터링합니다.
- `journalctl --since "2023-01-01" --until "2023-12-31"`: 특정 기간 내의 로그만 조회합니다.
- `journalctl -p err`: 에러(Error) 등급 이상의 중요한 로그만 골라봅니다.
- `logrotate -d /etc/logrotate.conf`: 로그 순환(Rotation) 설정이 올바른지 테스트합니다.
- `tail -f /var/log/syslog`: 시스템의 일반적인 메시지 로그를 실시간으로 모니터링합니다.
- `grep -i error /var/log/syslog`: 로그에서 대소문자 구분 없이 "error" 키워드를 검색합니다.
- `awk '/ERROR/ {print $0}' /var/log/app.log`: 로그 파일에서 ERROR가 포함된 행만 추출하여 출력합니다.

= 9. 네트워크 관리 및 보안 고급

== 라우팅 및 인터페이스 제어
- `ip route show`: 시스템의 현재 라우팅 테이블을 확인합니다.
- `ip route add 192.168.1.0/24 via 192.168.1.1`: 특정 대역으로 가는 정적 라우팅 경로를 추가합니다.
- `ip route del 192.168.1.0/24`: 등록된 라우팅 경로를 삭제합니다.
- `ip link show`: 네트워크 인터페이스의 물리적 상태를 확인합니다.
- `ip addr add 192.168.1.100/24 dev eth0`: 인터페이스에 IP 주소를 할당합니다.
- `ip addr del 192.168.1.100/24 dev eth0`: 할당된 IP 주소를 제거합니다.
- `ethtool eth0`: 네트워크 인터페이스의 하드웨어 설정 정보를 확인합니다.
- `mii-tool eth0`: 네트워크 인터페이스의 물리적 연결 상태를 간단히 확인합니다.

== 방화벽 설정 (iptables)
- `iptables -L`: 현재 설정된 방화벽 규칙 리스트를 출력합니다.
- `iptables -A INPUT -p tcp --dport 22 -j ACCEPT`: 22번 포트(SSH) 입력을 허용합니다.
- `iptables -A INPUT -p tcp --dport 80 -j ACCEPT`: 80번 포트(HTTP) 입력을 허용합니다.
- `iptables -A INPUT -j DROP`: 정의된 규칙 외의 모든 입력을 차단합니다.
- `iptables -F`: 등록된 모든 방화벽 규칙을 즉시 삭제합니다.
- `iptables -I INPUT 1 -p tcp --dport 443 -j ACCEPT`: 규칙 리스트의 맨 처음에 HTTPS 허용 규칙을 삽입합니다.
- `iptables -D INPUT 1`: 첫 번째 규칙을 삭제합니다.
- `iptables-save > /etc/iptables/rules.v4`: 현재 설정을 파일로 저장합니다.
- `iptables-restore < /etc/iptables/rules.v4`: 파일에 저장된 규칙을 시스템에 다시 적용합니다.

== 네트워크 진단 및 트래픽 분석
- `nmap -sS target_ip`: 스텔스 방식의 포트 스캔을 수행합니다.
- `nmap -sV target_ip`: 활성화된 포트의 서비스 버전을 감지합니다.
- `tcpdump -i eth0 port 80`: 특정 인터페이스의 80번 포트로 오가는 패킷을 캡처합니다.
- `tcpdump -i eth0 host 192.168.1.1`: 특정 IP 주소와 연관된 패킷만 필터링합니다.
- `ss -tuln`: 수신 대기 중인 모든 포트 상태를 효율적으로 출력합니다.
- `lsof -i`: 현재 시스템의 모든 네트워크 연결 상태를 확인합니다.

= 10. 디스크 및 파일 시스템 관리 고급

== 파티셔닝 및 파일 시스템 생성
- `fdisk -l`: 시스템에 연결된 디스크와 파티션 정보를 나열합니다.
- `parted /dev/sda print`: GPT 파티션 형식을 포함한 디스크 상세 정보를 확인합니다.
- `mkfs.ext4 /dev/sda1`: 파티션을 ext4 파일 시스템 형식으로 포맷합니다.
- `mkfs.xfs /dev/sda1`: 파티션을 XFS 파일 시스템 형식으로 포맷합니다.
- `fsck /dev/sda1`: 파일 시스템의 무결성을 검사하고 필요한 경우 수리합니다.
- `resize2fs /dev/sda1`: ext4 파일 시스템의 크기를 파티션 크기에 맞게 조정합니다.

== LVM (Logical Volume Manager) 관리
- `pvcreate /dev/sda1`: 물리 볼륨을 생성합니다.
- `vgcreate myvg /dev/sda1`: 물리 볼륨들을 묶어 볼륨 그룹을 생성합니다.
- `lvcreate -L 10G -n mylv myvg`: 볼륨 그룹 내에 논리 볼륨을 생성합니다.
- `lvextend -L +5G /dev/myvg/mylv`: 논리 볼륨의 용량을 확장합니다.
- `lvremove /dev/myvg/mylv`: 사용하지 않는 논리 볼륨을 삭제합니다.

= 11. 시스템 보안 강화 (Hardening)

- `passwd -l username`: 특정 사용자의 계정을 잠가 로그인을 차단합니다.
- `chage -l username`: 패스워드 만료 및 변경 주기 정보를 확인합니다.
- `chattr +i file`: 파일에 불변(Immutable) 속성을 부여하여 삭제나 수정을 방지합니다.
- `lsattr file`: 파일에 설정된 특수 속성을 확인합니다.
- `umask 022`: 새로 생성되는 파일 및 디렉토리의 기본 권한 마스크를 설정합니다.
- `ufw status`: 데비안 계열의 간편한 방화벽(UFW) 상태를 확인합니다.
- `ufw allow 22/tcp`: SSH 연결을 허용합니다.

= 12. 백업 및 복구 활용

== rsync를 이용한 동기화 백업
```bash
# 디렉토리 전체를 대상지로 동기화 (삭제된 파일도 반영)
rsync -avz --delete /source/ /destination/

# SSH를 통해 원격지로 안전하게 백업 전송
rsync -avz -e ssh /local/path user@remote:/remote/path

# 하드 링크를 활용해 저장 공간을 절약하는 증분 백업
rsync -avz --link-dest=/previous/backup /source/ /new/backup/
```

== dd를 이용한 디스크 복제
```bash
# 디스크의 전체 내용을 다른 디스크로 완벽 복제
dd if=/dev/sda of=/dev/sdb bs=4M status=progress

# 디스크 전체를 이미지 파일로 생성
dd if=/dev/sda of=/backup/disk.img bs=4M status=progress

# 압축하며 이미지 생성 및 복원
dd if=/dev/sda bs=4M | gzip > /backup/disk.img.gz
gunzip -c /backup/disk.img.gz | dd of=/dev/sda bs=4M
```

= 13. 성능 튜닝 및 시스템 서비스

- `sysctl -a`: 현재 적용된 모든 커널 파라미터를 확인합니다.
- `sysctl -w vm.swappiness=10`: 스왑(Swap) 사용 선호도를 즉시 변경합니다.
- `systemctl list-units --type=service`: 현재 시스템의 모든 서비스 상태를 나열합니다.
- `systemctl enable service_name`: 시스템 부팅 시 서비스가 자동 실행되도록 설정합니다.
- `systemctl daemon-reload`: 수정된 systemd 유닛 설정 파일을 다시 로드합니다.

= 14. 트러블슈팅 및 장애 진단

- `journalctl -b`: 현재 부팅 세션의 모든 로그를 확인합니다.
- `dmesg | grep -i error`: 부팅 과정이나 장치 드라이버 상의 에러를 빠르게 찾습니다.
- `smartctl -a /dev/sda`: 디스크의 물리적 상태(S.M.A.R.T)를 진단합니다.
- `mtr google.com`: 네트워크 경로의 지연(Latency)과 패킷 손실을 실시간으로 추적합니다.
- `mount -o remount,ro /`: 루트 파일 시스템에 문제가 있을 때 안전을 위해 읽기 전용으로 재마운트합니다.
