#import "../templates/conf.typ": *

#show: template.with(
  title: "HTML5 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 기본 문서 구조

```html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>문서 제목</title>
    <link rel="stylesheet" href="style.css">
    <script src="script.js"></script>
</head>
<body>
    <!-- 페이지 콘텐츠 -->
</body>
</html>
```

= 주요 시맨틱 태그

- `<header>`: 페이지나 섹션의 머리말. 로고, 제목, 네비게이션 포함.
- `<nav>`: 주요 네비게이션 링크.
- `<main>`: 페이지의 주요 콘텐츠. 문서에 하나만 존재해야 함.
- `<article>`: 독립적으로 배포하거나 재사용할 수 있는 콘텐츠 (블로그 포스트, 뉴스 기사).
- `<section>`: 문서의 일반적인 구획. 보통 제목을 포함.
- `<aside>`: 보조 콘텐츠 (사이드바, 광고 등).
- `<footer>`: 페이지나 섹션의 꼬리말. 저작권, 연락처 정보 등.
- `<figure>` & `<figcaption>`: 이미지, 다이어그램 등에 주석을 붙일 때 사용.

= 텍스트 관련 태그

- `<h1>` - `<h6>`: 제목.
- `<p>`: 문단.
- `<a>`: 하이퍼링크. `href` 속성으로 URL 지정.
- `<strong>`: 중요한 텍스트 (굵게 표시).
- `<em>`: 강조하는 텍스트 (기울임꼴).
- `<blockquote>`: 인용 블록.
- `<code>`: 코드 조각.
- `<pre>`: 미리 서식이 지정된 텍스트 (공백, 줄바꿈 유지).
- `<br>`: 줄바꿈.
- `<hr>`: 수평선.

= 목록 태그

- `<ul>`: 순서 없는 목록 (Unordered List).
- `<ol>`: 순서 있는 목록 (Ordered List).
- `<li>`: 목록의 각 항목 (List Item).
- `<dl>`, `<dt>`, `<dd>`: 정의 목록 (Definition List).

= 폼 (Forms)

- `<form>`: 사용자 입력을 위한 양식. `action`, `method` 속성.
- `<input>`: 다양한 종류의 입력 필드.
  - `type="text"`: 텍스트 입력.
  - `type="password"`: 비밀번호 입력.
  - `type="email"`: 이메일 주소.
  - `type="number"`: 숫자.
  - `type="date"`: 날짜 선택.
  - `type="checkbox"`: 체크박스.
  - `type="radio"`: 라디오 버튼.
  - `type="submit"`: 제출 버튼.
  - `type="file"`: 파일 선택.
- `<label>`: 입력 필드의 라벨. `for` 속성으로 `input`의 `id`와 연결.
- `<textarea>`: 여러 줄 텍스트 입력.
- `<select>` & `<option>`: 드롭다운 목록.
- `<button>`: 클릭 가능한 버튼.

= 미디어 태그

- `<img>`: 이미지. `src`, `alt` 속성 필수.
- `<audio>`: 오디오 콘텐츠. `controls` 속성으로 제어판 표시.
- `<video>`: 비디오 콘텐츠. `controls`, `width`, `height` 속성.
- `<source>`: `<audio>`, `<video>`를 위한 여러 미디어 리소스 정의.

= 테이블 태그

- `<table>`: 테이블.
- `<thead>`: 테이블 헤더 그룹.
- `<tbody>`: 테이블 본문 그룹.
- `<tfoot>`: 테이블 푸터 그룹.
- `<tr>`: 테이블 행 (Table Row).
- `<th>`: 테이블 헤더 셀 (Table Header).
- `<td>`: 테이블 데이터 셀 (Table Data).
- `colspan`, `rowspan`: 셀 병합.

= 주요 속성 (Attributes)

- `id`: 문서 내에서 고유한 식별자.
- `class`: 스타일링이나 스크립트에서 사용할 하나 이상의 클래스 이름.
- `style`: 인라인 CSS 스타일.
- `title`: 요소에 대한 추가 정보 (툴팁으로 표시).
- `data-*`: 사용자 정의 데이터 속성.
- `href`: `<a>` 태그의 링크 주소.
- `src`: `<img>`, `<script>`, `<audio>`, `<video>` 태그의 리소스 소스.
- `alt`: `<img>` 태그의 대체 텍스트.
- `disabled`: `input`, `button` 등을 비활성화.
- `placeholder`: `input`, `textarea`에 입력 예시 텍스트 표시.
- `required`: 폼 제출 시 필수 입력 필드로 지정.


= Google Style Guide

== 공통 원칙

- Protocol: 이미지 등 모든 리소스에 `HTTPS` 사용.
- Indentation: 공백 2개 (탭 금지).
- Capitalization: 모든 코드(태그, 속성, 셀렉터 등)는 소문자만 사용.
- Encoding: `UTF-8` 사용 (BOM 없음). HTML에 `<meta charset="utf-8">` 명시.

== HTML 가이드

- Doctype: 항상 `<!doctype html>` 사용.
- Validity: 유효한 HTML 작성. W3C 밸리데이터 활용.
- Semantics: 태그 목적에 맞게 사용 (`div` 대신 `a`, `p`, `header` 등).
- Multimedia: `alt` 속성 등으로 대체 텍스트 제공 필수.
- Optional Tags: 파일 크기 최적화를 위해 선택적 태그(html, body, li 등) 생략 가능.
- Quotation: 속성값에는 큰따옴표(`"`) 사용.

== CSS 가이드

- Class Naming: 의미론적 또는 일반적인 이름 사용 (기능 중심). 하이픈(`-`)으로 단어 구분.
- ID Selectors: ID 셀렉터(` #id`) 사용 지양 (Class 셀렉터 권장).
- Shorthand: 가능한 한 단축 속성(`font`, `margin` 등) 사용.
- 0 & Units: 값이 0인 경우 단위 생략 (`margin: 0;`).
- Hex Notation: 가능하면 3자리 헥사 코드 사용 (`#abc`).
- Important: `!important` 사용 자제. 셀렉터 우선순위 활용.

== 포매팅 및 관례

- Order: CSS 선언은 알파벳 순서로 정렬 권장.
- Spacing: 블록 시작 전 공백 1개, 속성 콜론(`:`) 뒤 공백 1개 사용.
- Comments: 복잡한 코드에는 섹션 구분 주석 작성.
- Separation: 구조(HTML), 표현(CSS), 동작(JS)을 엄격히 분리.
