#import "../templates/conf.typ": *

#show: template.with(
  title: "Color Themes Palette",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

#let bordered-table(..args) = table(
  stroke: 0.5pt + gray,
  inset: 6pt,
  ..args
)

= Catppuccin Palette (Latte)

#import table: cell, header

#bordered-table(
  columns: 4,
  table.header(
    [Color], [Name], [Hex Code], [RGB Code]
  ),
  cell(fill: rgb("#dc8a78"), []), [Rosewater], [`#dc8a78`], [`220,138,120`],
  cell(fill: rgb("#dd7878"), []), [Flamingo], [`#dd7878`], [`221,120,120`],
  cell(fill: rgb("#ea76cb"), []), [Pink], [`#ea76cb`], [`234,118,203`],
  cell(fill: rgb("#8839ef"), []), [Mauve], [`#8839ef`], [`136,57,239`],
  cell(fill: rgb("#d20f39"), []), [Red], [`#d20f39`], [`210,15,57`],
  cell(fill: rgb("#e64553"), []), [Maroon], [`#e64553`], [`230,69,83`],
  cell(fill: rgb("#fe640b"), []), [Peach], [`#fe640b`], [`254,100,11`],
  cell(fill: rgb("#df8e1d"), []), [Yellow], [`#df8e1d`], [`223,142,29`],
  cell(fill: rgb("#40a02b"), []), [Green], [`#40a02b`], [`64,160,43`],
  cell(fill: rgb("#179299"), []), [Teal], [`#179299`], [`23,146,153`],
  cell(fill: rgb("#04a5e5"), []), [Sky], [`#04a5e5`], [`4,165,229`],
  cell(fill: rgb("#209fb5"), []), [Sapphire], [`#209fb5`], [`32,159,181`],
  cell(fill: rgb("#1e66f5"), []), [Blue], [`#1e66f5`], [`30,102,245`],
  cell(fill: rgb("#7287fd"), []), [Lavender], [`#7287fd`], [`114,135,253`],
)

= Catppuccin Palette (Frappé)

#bordered-table(
  columns: 4,
  table.header(
    [Color], [Name], [Hex Code], [RGB Code]
  ),
  cell(fill: rgb("#f2d5cf"), []), [Rosewater], [`#f2d5cf`], [`242,213,207`],
  cell(fill: rgb("#eebebe"), []), [Flamingo], [`#eebebe`], [`238,190,190`],
  cell(fill: rgb("#f4b8e4"), []), [Pink], [`#f4b8e4`], [`244,184,228`],
  cell(fill: rgb("#ca9ee6"), []), [Mauve], [`#ca9ee6`], [`202,158,230`],
  cell(fill: rgb("#e78284"), []), [Red], [`#e78284`], [`231,130,132`],
  cell(fill: rgb("#ea999c"), []), [Maroon], [`#ea999c`], [`234,153,156`],
  cell(fill: rgb("#ef9f76"), []), [Peach], [`#ef9f76`], [`239,159,118`],
  cell(fill: rgb("#e5c890"), []), [Yellow], [`#e5c890`], [`229,200,144`],
  cell(fill: rgb("#a6d189"), []), [Green], [`#a6d189`], [`166,209,137`],
  cell(fill: rgb("#81c8be"), []), [Teal], [`#81c8be`], [`129,200,190`],
  cell(fill: rgb("#99d1db"), []), [Sky], [`#99d1db`], [`153,209,219`],
  cell(fill: rgb("#85c1dc"), []), [Sapphire], [`#85c1dc`], [`133,193,220`],
  cell(fill: rgb("#8caaee"), []), [Blue], [`#8caaee`], [`140,170,238`],
  cell(fill: rgb("#babbf1"), []), [Lavender], [`#babbf1`], [`186,187,241`],
)

= Dracula Theme Palette

#bordered-table(
  columns: 4,
  table.header(
    [Color], [Name], [Hex Code], [RGB Code]
  ),
  cell(fill: rgb("#282a36"), []), [Background], [`#282a36`], [`40,42,54`],
  cell(fill: rgb("#44475a"), []), [Selection], [`#44475a`], [`68,71,90`],
  cell(fill: rgb("#f8f8f2"), []), [Foreground], [`#f8f8f2`], [`248,248,242`],
  cell(fill: rgb("#6272a4"), []), [Comment], [`#6272a4`], [`98,114,164`],
  cell(fill: rgb("#8be9fd"), []), [Cyan], [`#8be9fd`], [`139,233,253`],
  cell(fill: rgb("#50fa7b"), []), [Green], [`#50fa7b`], [`80,250,123`],
  cell(fill: rgb("#ffb86c"), []), [Orange], [`#ffb86c`], [`255,184,108`],
  cell(fill: rgb("#ff79c6"), []), [Pink], [`#ff79c6`], [`255,121,198`],
  cell(fill: rgb("#bd93f9"), []), [Purple], [`#bd93f9`], [`189,147,249`],
  cell(fill: rgb("#ff5555"), []), [Red], [`#ff5555`], [`255,85,85`],
  cell(fill: rgb("#f1fa8c"), []), [Yellow], [`#f1fa8c`], [`241,250,140`],
)

= Atom One Light Palette

#bordered-table(
  columns: 4,
  table.header(
    [Color], [Name], [Hex Code], [RGB Code]
  ),
  cell(fill: rgb("#383a42"), []), [Foreground], [`#383a42`], [`56,58,66`],
  cell(fill: rgb("#fafafa"), []), [Background], [`#fafafa`], [`250,250,250`],
  cell(fill: rgb("#9d9d9f"), []), [Gutter], [`#9d9d9f`], [`157,157,159`],
  cell(fill: rgb("#dcdcdf"), []), [Guide], [`#dcdcdf`], [`220,220,223`],
  cell(fill: rgb("#e45649"), []), [Red], [`#e45649`], [`228,86,73`],
  cell(fill: rgb("#50a14f"), []), [Green], [`#50a14f`], [`80,161,79`],
  cell(fill: rgb("#c18401"), []), [Yellow], [`#c18401`], [`193,132,1`],
  cell(fill: rgb("#4078f2"), []), [Blue], [`#4078f2`], [`64,120,242`],
  cell(fill: rgb("#a626a4"), []), [Purple], [`#a626a4`], [`166,38,164`],
  cell(fill: rgb("#0184bc"), []), [Cyan], [`#0184bc`], [`1,132,188`],
)
