#import "../templates/conf.typ": *

#show: template.with(
  title: "ggplot2 Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. Basic Structure

`ggplot2` is a plotting system for R, based on the Grammar of Graphics.

```r
library(ggplot2)

ggplot(data = <DATA>, mapping = aes(<MAPPINGS>)) +
    <GEOM_FUNCTION>() +
    <COORDINATE_FUNCTION>() +
    <FACET_FUNCTION>() +
    <SCALE_FUNCTION>() +
    <THEME_FUNCTION>()
```

= 2. Geoms (Geometric Objects)

Define the type of plot.

- `geom_point()`: Scatter plot.
- `geom_line()`: Line plot.
- `geom_bar()` / `geom_col()`: Bar chart.
- `geom_histogram()`: Histogram.
- `geom_boxplot()`: Box and whisker plot.
- `geom_violin()`: Violin plot.
- `geom_smooth()`: Add a smoothed conditional mean (regression line).
- `geom_text()` / `geom_label()`: Add text annotations.
- `geom_tile()` / `geom_raster()`: Heatmaps.

= 3. Aesthetics (aes)

Map data variables to visual properties.

- `x`, `y`: Position.
- `color`: Outline color.
- `fill`: Internal area color.
- `size`: Size of points or lines.
- `shape`: Point shape prefix.
- `alpha`: Transparency level.
- `linetype`: Solid, dashed, etc.

= 4. Scales

Control how data values are translated to aesthetic space.

- `scale_x_continuous()`, `scale_y_log10()`.
- `scale_color_manual(values = c("red", "blue"))`.
- `scale_fill_gradient(low = "white", high = "red")`.
- `scale_x_date()`: Formatting for date variables.

= 5. Faceting

Divide one plot into multiple subplots (small multiples).

- `facet_wrap(~ variable)`: Wrap 1D ribbon of panels into 2D.
- `facet_grid(rows ~ cols)`: 2D grid of panels.

= 6. Labels and Titles

- `labs()`: Title, subtitle, caption, x-axis, y-axis, and legend labels.
  ```r
  + labs(title = "My Plot", x = "Weight", y = "Height")
  ```

= 7. Themes

Control the non-data parts of the plot (background, grid lines, fonts).

- `theme_gray()`: Default gray background.
- `theme_bw()`: White background with grid lines.
- `theme_minimal()`: Clean, minimal design.
- `theme_classic()`: Simple, axes-only theme.
- `theme()`: Fine-tune individual elements.
  ```r
  + theme(legend.position = "bottom")
  ```

= 8. Coordinate Systems

- `coord_flip()`: Flip axes (useful for bar charts).
- `coord_polar()`: Polar coordinates (pie charts, coxcomb).
- `coord_fixed()`: maintain fixed aspect ratio.

= 9. Saving Plots

- `ggsave("plot.png", width = 10, height = 7)`: Save the last plot created.


= Tips for Better Data Viz

== Layering
Add layers with `+`. The order matters; later layers are drawn on top.

== Stat Transformations
Some geoms perform statistical transformations (e.g., `geom_bar` counts occurrences by default). Use `stat = "identity"` to use literal values.

== Global vs Local Mapping
- Mapping inside `ggplot(aes(...))` is global and inherited by all geoms.
- Mapping inside `geom_*(aes(...))` is local to that specific layer.

== Colors
Use `RColorBrewer` or `viridis` for colorblind-friendly and perceptually uniform palettes.
```r
+ scale_color_viridis_d()
```
