#import "../templates/conf.typ": *

#show: template.with(
  title: "macOS Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. Essential Keyboard Shortcuts

Understanding macOS shortcuts can significantly boost your productivity.

- `Cmd + Space`: Spotlight Search (Open apps, files, or perform calculations).
- `Cmd + Tab`: Switch between open applications.
- `Cmd + ~`: Switch between windows of the same application.
- `Cmd + W`: Close current window.
- `Cmd + Q`: Quit application.
- `Cmd + Shift + 4`: Capture selected area as screenshot (saved to Desktop by default).
- `Cmd + Shift + 5`: Open Screen Capture interface (record video or advanced shots).
- `Cmd + Option + Esc`: Force Quit applications.
- `Cmd + Space` (Hold): Siri.

= 2. Finder and File Management

- `Space`: Quick Look (Preview file without opening).
- `Cmd + Delete`: Move selected item to Trash.
- `Cmd + Shift + Delete`: Empty Trash.
- `Cmd + [ / ]`: Back/Forward in Finder navigation.
- `Cmd + Option + P`: Show path bar.
- `Cmd + Option + S`: Show/Hide Sidebar.
- `Cmd + Shift + .`: Toggle visibility of hidden files.
- `Cmd + I`: View Get Info (File properties).

= 3. Window Management and Spaces

- `Ctrl + Up`: Mission Control (All windows and spaces).
- `Ctrl + Left / Right`: Switch between Desktop Spaces.
- `Cmd + Option + D`: Show/Hide the Dock.
- `Cmd + Ctrl + F`: Toggle Full Screen mode.

= 4. Terminal and CLI (macOS specific)

macOS is Unix-certified (BSD-based).

- `pbcopy < file.txt`: Copy file content to the system clipboard.
- `pbpaste > file.txt`: Paste clipboard content to a file.
- `open .`: Open the current terminal directory in Finder.
- `open file.txt`: Open a file using the default macOS application.
- `caffeinate`: Prevent your Mac from sleeping.
- `say "Hello"`: Convert text to speech.
- `system_profiler`: Detailed system hardware and software information.
- `tmutil`: Time Machine control utility.
- `mdfind`: Command-line search using Metadata (Spotlight engine).

= 5. Homebrew (The macOS Package Manager)

- `brew install <package>`: Install a command-line tool.
- `brew install --cask <app>`: Install a GUI application (e.g., Google Chrome).
- `brew update`: Update Homebrew itself.
- `brew upgrade`: Upgrade all installed packages.
- `brew cleanup`: Remove old versions and caches.

= 6. Development Tools

- `xcode-select --install`: Install command-line developer tools (gcc, git, etc.).
- `softwareupdate -l`: List available software updates.
- `sudo softwareupdate -ia`: Install all available updates.

= 7. System Paths

- `/Applications`: Installed user applications.
- `~/Library`: User-specific settings and application data (usually hidden).
- `/Library`: System-wide settings.
- `/Volumes`: Mounted external drives and disk images.
- `/usr/local/bin`: Usual location for Homebrew-installed binaries.
