#import "../templates/conf.typ": *

#show: template.with(
  title: "fzf Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. Basic Concepts

`fzf` is a general-purpose command-line fuzzy finder. It reads a list from STDIN, filters it interactively, and outputs the selection to STDOUT.

= 2. Search Syntax

- `sb`: Fuzzy match (find items containing 's' and 'b' in that order).
- `'sb`: Exact match (find literal "sb").
- `^sb`: Prefix-exact match (starts with "sb").
- `sb$`: Suffix-exact match (ends with "sb").
- `!sb`: Inverse-exact match (does not contain "sb").
- `!^sb`: Inverse-prefix-exact match.
- `^sb | $pattern`: OR operator.

= 3. Shell Key Bindings

- `Ctrl-t`: Search files and paste path to command line.
- `Ctrl-r`: Search command history.
- `Alt-c`: Fuzzy change directory (cd).
- `**` + `Tab`: Trigger fzf completion for many commands (e.g., `cd **`, `vim **`).

= 4. Command Line Usage

- `find . | fzf`: Find and select a file.
- `ls | fzf -m`: Multi-select items using `Tab`.
- `fzf --preview 'cat {}'`: Preview file content while searching.
- `fzf --reverse`: Display the search UI from top to bottom.
- `fzf --height 40%`: Run fzf in a smaller layout within the terminal.

= 5. Advanced Examples

```bash
# Preview using bat (syntax highlighting)
fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'

# Git integration: branch search and checkout
git branch | fzf | xargs git checkout

# Process management: search and kill
ps aux | fzf | awk '{print $2}' | xargs kill -9
```

= 6. Environment Variables

- `FZF_DEFAULT_COMMAND`: Default command to generate input (e.g., use `fd` or `ripgrep`).
- `FZF_DEFAULT_OPTS`: Global default options (colors, layout, etc.).
- `FZF_CTRL_T_OPTS`: Specific options for the `Ctrl-t` binding.

= 7. UI Customization

- `--layout=reverse`: Search bar at the top.
- `--border`: Add a border around the finder.
- `--color`: Customize every color aspect (bg, fg, hl, info, prompt, etc.).
- `--prompt='🔍 '`: Change the search prompt.
