#import "../templates/conf.typ": *

#show: template.with(
  title: "Helix Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. Helix Core Concepts

Helix is a modal text editor with built-in support for LSP, tree-sitter, and a modern "Selection-Action" philosophy (different from Vim's "Action-Selection").

- Select-Action: You select the text first, then apply an action to it (e.g., `w` then `d`).
- Multiple Cursors: Native support for powerful multi-line editing.
- Built-in LSP: Intelligent diagnostics and autocompletion out of the box.

= 2. Navigation (Normal Mode)

- `h`, `j`, `k`, `l`: Left, Down, Up, Right.
- `w`, `b`, `e`: Next, Previous, End of word.
- `W`, `B`, `E`: Same as above but for whitespace-separated words.
- `0`, `$`: Start, End of line.
- `g g`, `G`: Start, End of file.
- `Ctrl + u`, `Ctrl + d`: Page Up/Down.

= 3. Selection and Editing

- `v`: Enter Visual mode.
- `x`: Select the whole line.
- `d`: Delete (cut) current selection.
- `c`: Change (delete and enter insert mode).
- `y`: Yank (copy) current selection.
- `p`: Paste after selection.
- `u`, `U`: Undo and Redo.

= 4. Search and Select (`/` & `s`)

- `/`: Search for a pattern (and select the matches).
- `n`, `N`: Next/Previous match.
- `s`: Select/Filter inside current selection using regex (Powerful for multi-cursor).
- `S`: Split current selection into multiple selections based on regex.

= 5. LSP and Code Intelligence

- `m`: Match mode (jumps to matching brackets, etc.).
- `g d`: Go to Definition.
- `g r`: List References.
- `g y`: Go to Type definition.
- `K`: Hover (show documentation).
- `[ d`, `] d`: Previous/Next diagnostic.
- `<space> + r`: Rename symbol.
- `<space> + a`: Code Action.

= 6. View and File Management

- `:e filename`: Open file.
- `:w`: Save.
- `:q`: Quit.
- `Ctrl + w`: Window management (split, jump, etc.).
- `<space> + f`: Global file picker.
- `<space> + s`: Symbol picker (current file).
- `<space> + S`: Symbol picker (workspace).

= 7. Multiple Cursors

- `C`: Duplicate current selection to next line.
- `Alt + C`: Duplicate current selection to previous line.
- `s`: Filter selections.
- `,`: Remove current selection from multi-cursor.


= Pro Tips

== Select inside...
- `mi(`: Match inside parentheses.
- `mi"`: Match inside double quotes.
- `ma{`: Match around braces (including the braces).

== Selection to Shell
- `|`: Pipe selection to shell command and replace.
- `!`: Pipe selection to shell command and ignore output.

== Configuration
Location: `~/.config/helix/config.toml`
Helix is designed to be usable with zero config, but highly themeable and customizable via TOML.

== Tutorial
Run `hx --tutor` to start the interactive tutorial.
