#import "../templates/conf.typ": *

#show: template.with(
  title: "Gemini CLI Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. Overview

`gemini-cli` is a powerful command-line interface developed by the Google DeepMind team. It allows users to interact with Gemini models directly from the terminal, automate tasks, and integrate AI into shell workflows.

= 2. Setup and Settings

- Key Configuration: `export GOOGLE_API_KEY="your_api_key_here"`.
- Basic Prompt: `gemini "What is the capital of France?"`.
- Model Selection: `gemini --model flash "text..."`.
- System Prompt: `gemini --system "You are a helpful coding assistant" "Explain..."`.

= 3. File and Data Interaction

- Read from File: `cat code.py | gemini "Explain this code"`.
- Pass Local Files: `gemini --file image.png "What's in this image?"`.
- Multiple Files: `gemini --file data.csv --file report.pdf "Summarize the relationship between these files"`.

= 4. Automation and Scripting

- Inline Shell Assistant: `` `gemini --shell "find all logs and zip them"` ``.
- Batch Processing:
  ```bash
  for file in *.txt; do
    cat "$file" | gemini "Summarize to one bullet point" > "${file%.txt}_summary.txt"
  done
  ```
- Pipe Integration: `ls | gemini "Categorize these files into groups"`.

= 5. Advanced Flags

- `--temperature`: Control randomness (0.0 for deterministic, 1.0 for creative).
- `--top_p`, `--top_k`: Advanced sampling parameters.
- `--max_tokens`: Limit the length of the response.
- `--json`: Output result in JSON format (useful for parsing in scripts).

= 6. Context and History

- Multi-turn Conversation: Use `--chat` mode to maintain context across prompts.
- Snapshot: Save the state of a session for later resume.

= 7. Use Cases

- Code Review: `git diff | gemini "Review these changes for security vulnerabilities"`.
- Log Analysis: `tail -n 100 error.log | gemini "Identify the root cause of the error"`.
- Translation: `cat article.md | gemini "Translate this into professional Korean"`.


= Pro Tips

== System Context
Use the `--system` flag to define a persistent persona or set of constraints (e.g., "Respond only in valid JSON").

== Speed vs Quality
Use the `flash` model for high-speed, cost-effective tasks (like classification) and the standard `pro` model for complex reasoning and creative generation.

== Shell Formatting
If the output contains code blocks, use `gemini ... | glow` (if installed) or redirects to files to preserve formatting.
