#import "../templates/conf.typ": *

#show: template.with(
  title: "flox Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. Introduction

`flox` is a developer tool that provides a simplified interface to the Nix package manager. it allows you to create portable, reproducible environments that work consistently across different operating systems.

= 2. Project Initialization and Environments

- `flox init`: Initialize a new flox environment in the current directory (creates `.flox/`).
- `flox activate`: Activate the environment for the current directory.
- `flox services`: Manage background services associated with the environment.

= 3. Package Management

- `flox install [package]`: Search for and install a package into the active environment.
- `flox search [query]`: Search for available packages in the flox/Nix catalog.
- `flox list`: List all packages installed in the current environment.
- `flox remove [package]`: Uninstall a package.
- `flox upgrade`: Upgrade installed packages to their latest versions.

= 4. Running Commands

- `flox run [command]`: Run a command within the flox environment without activating it.
- `flox run -- [package] [args]`: Run a specific package directly.

= 5. Remote and Sharing

- `flox push`: Push your environment configuration to the flox cloud for sharing.
- `flox pull`: Pull an environment configuration.
- `flox subscribe [user/env]`: Subscribe to someone else's environment.

= 6. Global vs Local

- Flox environments are local by default (per directory).
- You can create named global environments that are accessible from anywhere on your system.


= Why flox? (Pro Tips)

== Built on Nix
Flox leverages the power of Nix (over 80,000 packages) but removes the complexity of learning the Nix language for basic environment management.

== Reproducibility
Environments are defined by configuration, ensuring that if it works on your machine, it will work on your teammate's machine or in CI.

== Multi-layer Environments
You can activate multiple flox environments simultaneously, layering tools as needed.

== Declarative Management
Everything about your environment is stored in code, making it easy to track changes via Git.
