#import "../templates/conf.typ": *

#show: template.with(
  title: "Git Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= GIT CHEAT SHEET

Git is an open-source distributed version control system that helps manage source code versions locally and collaborate with others by integrating with platforms like GitHub. This cheatsheet summarizes frequently used Git commands for quick reference.

== STAGE & SNAPSHOT  
Work with the snapshot history and the staging area.

- `git status`: Show the status of modified files in the working directory and the staging area.
- `git add [file]`: Add the current state of a modified file to the staging area to be included in the next commit.
- `git reset [file]`: Remove a file from the staging area while keeping the contents in the working directory.
- `git diff`: Compare changes that have not yet been staged.
- `git diff --staged`: Compare changes in the staging area that are ready to be committed.
- `git commit -m [message]`: Permanently save changes from the staging area as a new commit.

== SETUP  
User information and global configurations.

- `git config --global user.name [name]`: Set the username to be recorded in the commit history.
- `git config --global user.email [email]`: Set the email address to be associated with the commit history.
- `git config --global color.ui auto`: Automatically apply colors to command outputs for better readability.

== SETUP & INIT  
Repository initialization and cloning.

- `git init`: Initialize the current directory as a new Git repository.
- `git clone [url]`: Clone a remote repository from the specified URL to the local machine.

== BRANCH & MERGE  
Manage independent work flows and merge them.

- `git branch`: List current branches; the active branch is marked with `*`.
- `git branch [name]`: Create a new branch based on the current commit.
- `git checkout [name]`: Switch the working environment to the specified branch.
- `git merge [name]`: Merge changes from the specified branch into the current branch.
- `git log`: Display the full commit history of the current branch.

== INSTALLATION & GUIS  
Platform-specific installation and GUI tools.

- GitHub for Windows: https://windows.github.com  
- GitHub for Mac: https://mac.github.com  
- Git for All Platforms (Linux, Solaris, etc.): http://git-scm.com  

== SHARE & UPDATE  
Synchronize and update with remote repositories.

- `git remote add [alias] [url]`: Assign an alias (usually origin) to a remote repository URL.
- `git fetch [alias]`: Retrieve all branch information from the remote repository.
- `git merge [alias]/[branch]`: Merge the fetched remote branch into the current local branch to bring it up to date.
- `git push [alias] [branch]`: Transmit local commits to the remote repository.
- `git pull`: Fetch and immediately merge the latest changes from the remote repository into the current branch.

== TRACKING PATH CHANGES  
Manage file deletions and path changes.

- `git rm [file]`: Delete a file from the project and record the state in the staging area.
- `git mv [old] [new]`: Change a file path or rename it, and record the state in the staging area.
- `git log --stat -M`: Display commit logs including file movements or renames.

== TEMPORARY COMMITS  
Temporarily store work-in-progress changes.

- `git stash`: Temporarily store current modifications and clear the working directory.
- `git stash list`: List all stashed changes.
- `git stash pop`: Apply the most recently stashed changes and remove them from the list.
- `git stash drop`: Delete a specific stash entry.

== REWRITE HISTORY  
Modify branches and rewrite history.

- `git rebase [branch]`: Reconstruct history by moving current branch commits to the end of the specified branch.
- `git reset --hard [commit]`: Reset the staging area and force the working directory to matches a specific commit state.

== INSPECT & COMPARE  
View history and check changes.

- `git log`: View the commit history of the currently active branch.
- `git log B..A`: Show commits that exist in branchA but not in branchB.
- `git log --follow [file]`: Track and show the full history of a file even if it has been renamed.
- `git diff B...A`: Compare and show changes that are only in branchA.
- `git show [SHA]`: View detailed information of a specific commit or tag.

== IGNORING PATTERNS  
Specify files to be excluded from tracking.

- `git config --global core.excludesfile [path]`: Set a global ignore pattern file for all local repositories.
- `.gitignore`: Create in the project root to specify files or directories to be ignored by Git.

== Advanced Git Workflow

=== Advanced Git Rebase
- `git rebase -i HEAD~3`: Interactively modify or squash the last 3 commits.
- `git rebase --onto main feature`: Move a specific branch to another base branch.
- `git rebase --continue`: Continue the rebase process after resolving conflicts.
- `git rebase --abort`: Abort the rebase and return to the original state.
- `git rebase --skip`: Skip the current commit and proceed with the rebase.

=== Cherry-pick and Advanced Merging
- `git cherry-pick <SHA>`: Apply changes from a specific commit to the current branch.
- `git cherry-pick <start>..<end>`: Apply a range of commits at once.
- `git cherry-pick --no-commit <SHA>`: Add changes to the staging area without creating a commit.
- `git merge --no-ff [branch]`: Force creation of a merge commit even in a Fast-forward relationship.
- `git merge --squash [branch]`: Combine all changes from the branch into a single commit for merging.

=== Submodule Management
- `git submodule add <url> <path>`: Add another repository as a subdirectory of the current project.
- `git submodule init`: Initialize submodules.
- `git submodule update`: Update submodule contents.
- `git submodule update --remote`: Update submodules to the latest commit on the remote repository.
- `git submodule foreach git pull origin main`: Run pull in all submodules simultaneously.

=== Git Hooks and Automation
- `pre-commit`: Hook executed just before a commit; often used for linting or tests.
- `post-commit`: Hook executed just after a commit; used for notifications, etc.
- `pre-push`: Hook executed just before a push; used for final validations.
- `commit-msg`: Verifies if the written commit message follows specific rules.

=== Advanced Branch Management
- `git branch -m [old] [new]`: Rename a branch.
- `git branch --set-upstream-to=origin/main [branch]`: Set the upstream branch for a local branch.
- `git branch --unset-upstream`: Unset the configured upstream branch.
- `git branch -d --force [name]`: Force delete a branch even if work is not completed.
- `git branch --merged`: List branches that have already been merged.
- `git branch --no-merged`: List branches that have not yet been merged.

=== Advanced Git Stash
- `git stash push -m "message"`: Stash changes with a descriptive message.
- `git stash list`: View all stashed entries.
- `git stash show stash@{0}`: View changes in a specific stash entry.
- `git stash apply stash@{0}`: Apply a stash without removing it from the list.
- `git stash pop stash@{0}`: Apply a stash and remove it from the list.
- `git stash branch [name] stash@{0}`: Create and switch to a new branch from a stashed state.

=== Bug Tracking with Git Bisect
- `git bisect start`: Start a binary search to find the point where a bug was introduced.
- `git bisect bad <commit>`: Mark a commit as having the bug.
- `git bisect good <commit>`: Mark a commit as bug-free.
- `git bisect run <script>`: Automatically run binary search using a script.
- `git bisect reset`: End search and return to the original branch.

=== Multi-branch Work with Git Worktree
- `git worktree add [path] [branch]`: Checkout another branch in a separate directory to work on them simultaneously.
- `git worktree list`: View all active working trees.
- `git worktree remove [path]`: Remove a previously added working tree.
- `git worktree prune`: Clean up invalid working tree information.

=== Recovery with Git Reflog
- `git reflog`: Detail the history of changes to HEAD to find accidentally deleted commits.
- `git reflog show [branch]`: View change history for a specific branch.
- `git reset --hard HEAD@{2}`: Force recovery to a specific point recorded in reflog.
- `git cherry-pick HEAD@{2}`: Select and recover a specific commit from history.

=== Advanced Git Config
- `git config --global core.autocrlf true`: Automatically convert line endings between OS differences.
- `git config --global core.safecrlf true`: Verify data loss during line ending conversion.
- `git config --global pull.rebase true`: Use rebase by default instead of merge during pull.
- `git config --global init.defaultBranch main`: Set the default branch name.
- `git config --global alias.co checkout`: Set shortcuts for frequently used commands.

=== Git LFS (Large File Storage)
- `git lfs install`: Initialize LFS for large file management.
- `git lfs track "*.psd"`: Specify files with certain extensions for LFS tracking.
- `git lfs track "*.zip"`: Configure ZIP files to be managed by LFS.
- `git lfs ls-files`: List files currently managed by LFS.
- `git lfs pull`: Fetch files from the LFS remote server.

=== Deployment Archives with Git Archive
- `git archive --format=zip --output=release.zip main`: Export work as a ZIP archive.
- `git archive --format=tar.gz --output=release.tar.gz main`: Export as a TAR.GZ archive.
- `git archive --format=zip --prefix=project/ main`: Create an archive including a specific prefix path.

=== Useful Advanced Command Combinations
```bash
# Summary and stats of the last 10 commits
git log --oneline --stat -10

# Track full history of a specific file even if renamed
git log --follow -- [filename]

# Compare commit counts between specific branches
git rev-list --count main
git rev-list --count [branch]

# View commit history during a specific period
git log --since="2023-01-01" --until="2023-12-31"

# View commits performed by a specific author
git log --author="Name"

# Search by commit message content
git log --grep="bug fix"

# View logs with file diffs (patch)
git log -p [filename]

# See the full history across branches in a graph format
git log --graph --oneline --all
```
