#import "../templates/conf.typ": *

#show: template.with(
  title: "Seaborn Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. Basic Concepts

Seaborn is a statistical data visualization library based on matplotlib, providing high-level interfaces and attractive themes.

- Import: `import seaborn as sns`
- Main logic: Integrated with Pandas DataFrames. Uses `data`, `x`, `y`, `hue` (color mapping).

= 2. Distribution Plots

Analyze how data is distributed.

- `sns.histplot()`: Histogram with optional KDE (kernel density estimation).
- `sns.kdeplot()`: Kernel density plot (smooth curve).
- `sns.ecdfplot()`: Empirical cumulative distribution function.
- `sns.rugplot()`: Marginal distributions.

= 3. Categorical Plots

Visualize data grouped by categorical variables.

- `sns.barplot()`: Show point estimates and confidence intervals as bars.
- `sns.countplot()`: Count of occurrences.
- `sns.boxplot()`: Show distribution across levels of a category.
- `sns.violinplot()`: Combine boxplot and KDE.
- `sns.stripplot()` / `sns.swarmplot()`: Categorical scatter plots (swarm avoids point overlapping).

= 4. Relational Plots

Analyze relationships between numeric variables.

- `sns.scatterplot()`: Standard scatter plot.
- `sns.lineplot()`: Line plot with error bands.
- `sns.regplot()`: Scatter plot with a linear regression line.
- `sns.lmplot()`: Facet-aware version of `regplot`.

= 5. Matrix and Multi-plot Grids

- `sns.heatmap(data.corr())`: Visualize correlation matrices or 2D data grids.
- `sns.jointplot()`: Relationship between two variables plus their marginal distributions.
- `sns.pairplot(df)`: Visualize all pairwise relationships in a dataset.
- `sns.FacetGrid(df, col="C")`: Create a grid of plots based on data subsets.

= 6. Styling and Color Palettes

- Set Theme: `sns.set_theme(style="whitegrid", palette="muted")`.
- Styles: `darkgrid`, `whitegrid`, `dark`, `white`, `ticks`.
- Colors:
  - `sns.color_palette("deep")`.
  - `sns.diverging_palette()`: For data with a central midpoint (e.g., correlations).

= 7. Working with Pandas

```python
import seaborn as sns
import pandas as pd

df = sns.load_dataset("tips") # Built-in dataset example

# x/y: column names, data: dataframe, hue: group by color
sns.scatterplot(data=df, x="total_bill", y="tip", hue="day", style="time")
```


= Pro Tips

== Figure Size
Since Seaborn uses Matplotlib, use `plt.figure(figsize=(10, 6))` before creating a Seaborn plot to control its size.

== Context Scaling
`sns.set_context("paper")` vs `sns.set_context("talk")`: Scale elements (lines, labels) for different presentation environments.

== Removing Spines
`sns.despine()`: Remove the top and right spines from the plot for a cleaner look.
