#import "../templates/conf.typ": *

#show: template.with(
  title: "pixi Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. Introduction

`pixi` is a modern, cross-platform package manager and workflow tool built on top of the Conda ecosystem. It focuses on speed, reproducibility, and a seamless developer experience.

= 2. Project Initialization

- `pixi init`: Initialize a new project (creates `pixi.toml`).
- `pixi init --import environment.yml`: Import an existing Conda environment file.

= 3. Dependency Management

- `pixi add [package]`: Add a dependency to the project (e.g., `pixi add python numpy`).
- `pixi add --pypi [package]`: Add a Python package directly from PyPI.
- `pixi remove [package]`: Remove a dependency.
- `pixi install`: Install all dependencies specified in `pixi.toml` and generate/update `pixi.lock`.

= 4. Running Tasks and Environments

- `pixi run [task_name]`: Execute a task defined in the `[tasks]` section of `pixi.toml`.
- `pixi shell`: Start a shell within the project's isolated environment.
- `pixi run python main.py`: Run a command directly in the environment without entering the shell.

= 5. Configuration (pixi.toml)

```toml
[project]
name = "my_project"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.10"
pandas = "*"

[tasks]
start = "python main.py"
test = "pytest"
```

= 6. Multi-environment Support

Add different environments for testing, production, or different Python versions.
```toml
[environments]
test = ["test-dependencies"]
```
Use `pixi run -e test [command]` to run within a specific environment.

= 7. Global Installation

- `pixi global install [package]`: Install a tool globally for use outside specific projects (replaces `conda install -g` or `pipx`).
- `pixi global list`: List globally installed tools.


= Why pixi? (Pro Tips)

== Lock Files
Pixi always generates a `pixi.lock` file, ensuring that every contributor and CI system uses the exact same versions of all dependencies.

== Speed
Written in Rust, it is significantly faster than traditional `conda` and even `mamba` in many operations.

== No Conda required
Pixi is a standalone binary. You don't need to have Conda or Mamba installed on your system to use it.

== Zero-config CI
Since all environment information is in `pixi.toml`, setting up a CI pipeline is as simple as running `pixi run [task]`.
