#import "../templates/conf.typ": *

#show: template.with(
  title: "Helix Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. Launching
- `hx`: Launch Helix
- `hx <file>`: Open specific file
- `hx --help`: Show help

= 2. Essentials
- `u`, `U`: Undo, Redo
- `Alt-u`, `Alt-U`: Move in tree history
- `:wq`: Save and quit
- `Esc`: Return to Normal mode

= 3. Movement
- `h`, `j`, `k`, `l`: Left, Down, Up, Right
- `w`, `b`, `e`: Next, Prev, End of word
- `W`, `B`, `E`: WORD (whitespace-delimited)
- `gh`, `gl`: Line start, end
- `gg`, `ge`: File start, end
- `<nn>G`: Go to line <nn>
- `Ctrl-b`, `Ctrl-f`: Page Up, Down
- `Ctrl-u`, `Ctrl-d`: Half Page Up, Down

= 4. Selection
- `%`: Select whole file
- `x`: Select line (extend by line)
- `Alt-;`: Swap anchor and cursor
- `Alt-o`, `Alt-i`: Expand, Shrink selection
- `;`: Collapse selection to cursor
- `s<regex>`: Select matches inside selection
- `S`: Split selection on regex

= 5. Altering Content
- `i`, `a`: Insert before, after selection
- `I`, `A`: Insert at line start, end
- `o`, `O`: Add line below, above
- `d`, `Alt-d`: Delete selection (with/without yank)
- `c`, `Alt-c`: Change selection (with/without yank)
- `y`, `p`, `P`: Yank, Paste after, before
- `~`, `` ` ``, `Alt-` `` ` ``: Change case
- `> `, `<`: Indent, Outdent
- `Ctrl-a`, `Ctrl-x`: Increment, Decrement

= 6. Search & Match
- `/`, `?`: Search forward, backward
- `n`, `N`: Next, Prev match
- `*`, `Alt-*`: Search for current selection
- `mm`: Go to matching delimiter
- `mi<ch>`, `ma<ch>`: Select inside, around delimiter

= 7. LSP & Treesitter
- `gd`, `gy`: Go to Definition, Type def
- `gr`, `gi`: Go to References, Implementation
- `]d`, `[d`: Next, Prev diagnostic
- `]f`, `[f`: Next, Prev function
- `Alt-n`, `Alt-p`: Next, Prev sibling node
- `<space>r`: Rename symbol
- `<space>a`: Code action
- `<space>k`: Documentation hover

= 8. Multiple Cursors
- `C`, `Alt-C`: Add selection below, above
- `&`: Align selections
- `,`: Remove all except primary
- `Alt-,`: Remove primary selection
- `(`, `)`: Rotate primary selection

= 9. View & Window
- `Ctrl-w v`, `s`: Vertical, Horizontal split
- `Ctrl-w w`: Next split
- `Ctrl-w q`: Close current split
- `zz`, `zt`, `zb`: Center, Top, Bottom align

= 10. Pickers
- `<space>f`: File picker (root)
- `<space>F`: File picker (cwd)
- `<space>b`: Buffer picker
- `<space>j`: Jumplist picker
- `<space>s`, `S`: Symbol picker (file, workspace)

= 11. Registers & Macros
- `"<ch>`: Select register <ch>
- `Q`, `q`: Record, Play macro
- `@`: Last macro register

= 12. Shell
- `|`: Pipe selection and replace
- `!`: Insert shell output before
- `Alt-!`: Append shell output after
- `$`: Filter selection through shell
