#import "../templates/conf.typ": *

#show: template.with(
  title: "Typst Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. Basic Syntax and Text Formatting

Typst is a modern, fast, and easy-to-use markup language for document preparation, designed as an alternative to LaTeX.

- Sections: Use `=` for headers. Add more `=` for sub-headers (e.g., `== Level 2`).
- Bold: `*bold text*`.
- Italic: `_italic text_`.
- Monospace (Code): `` `code` ``.
- Lists:
  - `- Item`: Unordered.
  - `+ Item`: Ordered.
- Links: `https://typst.app`.

= 2. Document Layout (Scripting Mode)

Commands starting with `#` are used for control and layout.

- Show Rule: `#show: ...` (Apply styles to elements).
- Set Rule: `#set text(font: "Linux Libertine")` (Set defaults).
- Functions: `template.with(title: "My Doc")`.
- Metadata: `#datetime.today().display()`.

= 3. Mathematics

Enclose math expressions in `$`.
- Inline: `$x + y = z$`.
- Block:
  ```typst
  $ sum_(i=1)^n i = (n(n+1)) / 2 $
  ```
- Symbols: Supports intuitive names like `alpha`, `sum`, `integral`.

= 4. Figures and Media

- Images: `image("path/to/img.png", width: 50%)`.
- Figures:
  ```typst
  #figure(
    image("logo.png"),
    caption: [My Figure Caption]
  )
  ```

= 5. Tables

```typst
#table(
  columns: (1fr, auto),
  inset: 10pt,
  align: horizon,
  table.header([Name], [Age]),
  [Alice], [25],
  [Bob], [30],
)
```

= 6. Code Blocks

Single backticks for inline, triple backticks for blocks. Supports syntax highlighting.
```typst
#```rust
fn main() {
    println!("Hello Typst!");
}
#```
```

= 7. Page Setup

```typst
#set page(
  paper: "a4",
  margin: (x: 2cm, y: 1.5cm),
  header: [My Document],
  footer: [Page #counter(page).display()],
)
```

= 8. Variables and Logic

- Variables: `#let x = 10`.
- Conditionals: `#if x > 5 [True] else [False]`.
- Loops: `#for i in range(5) [ #i ]`.


= Pro Tips

== Local Fonts
Use `--font-path` during compilation to use custom fonts not installed on the system:
`typst compile --font-path ./fonts my_doc.typ`

== Live Preview
Use `typst watch` to automatically recompile the document as you save changes. It works great with PDF viewers that support auto-reload.

== Packages
Typst has a built-in package manager. Import community packages using:
`#import "@preview/tablex:0.0.8": *`
