#import "../templates/conf.typ": *

#show: template.with(
  title: "Docker Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= Basic Concepts

Docker is a platform for developing, shipping, and running applications in containers.

- Image: A read-only template containing the application and its required environment.
- Container: A runnable instance of an image.
- Dockerfile: A text document containing commands to assemble an image.
- Docker Hub: A cloud-based registry for sharing and managing images.

= Image Management

- `docker pull [image]`: Download an image from a registry.
- `docker images`: List locally stored images.
- `docker rmi [image]`: Remove an image.
- `docker build -t [name] .`: Build an image from a Dockerfile in the current directory.
- `docker tag [src_image] [target_image]`: Tag an image.
- `docker push [image]`: Upload an image to a registry.

= Container Management

- `docker run [image]`: Create and start a container.
  - `-d`: Run in background (detached mode).
  - `-p 8080:80`: Map host port 8080 to container port 80.
  - `-v /host/path:/container/path`: Mount a volume.
  - `--name [name]`: Assign a name to the container.
  - `-it`: Interactive mode with terminal.
- `docker ps`: List running containers (`-a` to include stopped ones).
- `docker stop [container]`: Stop a running container.
- `docker start [container]`: Start a stopped container.
- `docker restart [container]`: Restart a container.
- `docker rm [container]`: Remove a container (`-f` to force).
- `docker exec -it [container] bash`: Run a command inside a running container.

= Logs and Inspection

- `docker logs [container]`: View container logs.
  - `-f`: Follow logs in real-time.
- `docker inspect [object]`: Get detailed information about a container or image.
- `docker stats`: Display real-time resource usage statistics.
- `docker top [container]`: Show running processes inside a container.

= Volume and Network

- `docker volume ls`: List volumes.
- `docker volume create [name]`: Create a volume.
- `docker volume rm [name]`: Remove a volume.
- `docker network ls`: List networks.
- `docker network create [name]`: Create a network.
- `docker network connect [network] [container]`: Connect a container to a network.

= Docker Compose

Tool for defining and running multi-container Docker applications.

- `docker-compose up`: Create and start containers defined in `docker-compose.yml`.
  - `-d`: Run in background.
- `docker-compose down`: Stop and remove containers, networks, and images.
- `docker-compose build`: Build or rebuild services.
- `docker-compose logs -f`: View service logs.
- `docker-compose ps`: List containers in the compose project.

= Pruning (Cleanup)

- `docker system prune`: Remove unused data (stopped containers, unused networks, dangling images).
- `docker image prune`: Remove dangling images.
- `docker container prune`: Remove all stopped containers.
- `docker volume prune`: Remove all unused volumes.


= Google Style Guide (Docker Best Practices)

== Dockerfile Optimization

- Use official, minimal base images (e.g., `alpine`, `debian-slim`).
- Combine `RUN` commands using `&&` and use `\` for line breaks to reduce image layers.
- Order commands from "least likely to change" to "most likely" to maximize layer caching.
- Clean up package manager caches (`rm -rf /var/lib/apt/lists/*`) in the same `RUN` layer.

== Security

- Avoid running as `root`; create and use a non-privileged user.
- Do not include secrets or sensitive credentials in the Dockerfile. Use environment variables or secrets management.
- Scan images for vulnerabilities regularly.

== Configuration and Portability

- Use `.dockerignore` to exclude unnecessary files (e.g., `.git`, node_modules) from the build context.
- Favor `ENTRYPOINT` for the main executable and `CMD` for default arguments.
- Prefer environment variables (`ENV`) for application configuration.
- Use explicit version tags for images instead of `latest` for reproducibility.

== Lifecycle and Health

- Implement a health check (`HEALTHCHECK`) to monitor application status.
- Ensure applications handle SIGTERM signals correctly for graceful shutdown.
- Keep containers ephemeral; they should be easy to stop, destroy, and replace.
