#import "../templates/conf.typ": *

#show: template.with(
  title: "Helix Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= Usage
== Registers
Usage: `"` + `<char>` + `<action>` (e.g., `"ay`).

=== User-defined
- `"ay`: Yank selection to register `a`.
- `"op`: Paste register `o` after selection.
- `"hc`: Store in `h`, then change (delete & insert).
- `"md`: Store in `m`, then delete.

=== Default Registers
- `/`: Last search pattern.
- `:`: Last executed command.
- `"`: Last yanked text.
- `@`: Last recorded macro.

=== Special Registers
- `_`: Black hole; all values are discarded.
- `#`: Selection indices (1, 2, 3...). Read-only.
- `.`: Contents of current selections. Read-only.
- `%`: Name of the current file. Read-only.
- `+`: System clipboard (yank/paste).
- `*`: Primary clipboard (yank/paste).

== Surround (Match Mode `m`)
Inspired by `vim-sandwich`. Supports counts and multiple selections.

- `ms<char>`: *Add* surround to selection.
- `mr<from><to>`: *Replace* closest surround.
- `md<char>`: *Delete* closest surround.
- *Example*: `%` (select all) -> `s` (split) -> `use` -> `mr([` (change `(use)` to `[use]`).

== Textobjects (Match Mode `m`)
- `ma`: Select *around* the object (includes delimiters).
- `mi`: Select *inside* the object (excludes delimiters).

=== Object Keys
- `w`, `W`: Word, WORD.
- `p`: Paragraph.
- `(`, `[`, `{`, `'`, `"`: Specified surround pairs.
- `m`: The closest surround pair.
- `f`, `t`: Function, Type (or Class). (TS)
- `a`: Argument/parameter. (TS)
- `c`: Comment. (TS)
- `T`: Test. (TS)
- `g`: Change.

== Syntax aware motions (TS)
Move the selection according to its location in the syntax tree.

- `Alt-o`: *Expand* selection to parent node.
- `Alt-i`: *Shrink* selection to child node.
- `Alt-p`: Move to *previous* sibling node.
- `Alt-n`: Move to *next* sibling node.
- `Alt-a`: Select all sibling nodes.

== Pickers (Space Mode)
=== Common Pickers
- `f`, `F`: File picker (root, cwd).
- `b`: Buffer picker.
- `j`: Jumplist picker.
- `s`, `S`: Symbol picker (doc, workspace).
- `d`, `D`: Diagnostics (doc, workspace).
- `/`: Global search.
- `a`: Code actions.
- `k`: Hover docs.

=== Interaction
- *Filtering*: Most use fuzzy fzf syntax.
- *Regex*: Global search uses regex.
- *Column filtering*: %prefix (e.g., %p .toml filters path).
- *Registers*: Ctrl-r + <char> to insert register content.
- *Quick Global Search*: Space + / -> Enter (uses current search register /).

== Keymap (Normal Mode)
=== Movement
- `h`, `j`, `k`, `l`: Left, Down, Up, Right.
- `w`, `b`, `e`: Next, Prev, End of word.
- `W`, `B`, `E`: WORD (whitespace delimited).
- `f`, `F`, `t`, `T`: Find/Till char (multiline).
- `G`: Go to line <n>.
- `Home`, `End`: Line start, end.
- `C-u`, `C-d`: Half page Up, Down.
- `C-i`, `C-o`: Jumplist Forward, Backward.

=== Changes
- `i`, `a`: Insert, Append.
- `I`, `A`: Insert at start, end of line.
- `o`, `O`: Open line below, above.
- `u`, `U`: Undo, Redo.
- `Alt-u`, `Alt-U`: Tree history Back, Forward.
- `y`, `p`, `P`: Yank, Paste after, before.
- `d`, `c`: Delete, Change.
- `>`, `<`: Indent, Unindent.
- `=`: Format (LSP).
- `C-a`, `C-x`: Increment, Decrement number.

=== Selection Manipulation
- `s`: Select regex matches in selections.
- `S`: Split selection on regex.
- `;`: Collapse to cursor.
- `Alt-;`: Flip anchor and cursor.
- `Alt-:`: Ensure forward direction.
- `C`, `Alt-C`: Add cursor Below, Above.
- `(`, `)`: Rotate selections.
- `%`: Select entire file.
- `x`: Select/Extend line.
- `J`: Join lines.
- `C-c`: Toggle comments.

=== Search
- `/`, `?`: Search Forward, Backward.
- `n`, `N`: Next, Prev match.
- `*`: Search selection (bounded).
- `Alt-*`: Search selection (raw).

== Minor Modes
- `v`: Select/Extend mode.
- `g`: Goto mode (e.g., gh, ge, gd, gy).
- `m`: Match mode (surround, textobjects).
- `z`: View mode (e.g., zz, zt, zb).
- `Ctrl-w`: Window mode (splits, navigation).
- `Space`: Space mode (pickers, LSP).

== Unimpaired (Bracket [ ])
Navigate between structured elements (TS).

- `]d`, `[d`: Next, Prev diagnostic.
- `]f`, `[f`: Next, Prev function.
- `]t`, `[t`: Next, Prev type/class.
- `]a`, `[a`: Next, Prev argument.
- `]c`, `[c`: Next, Prev comment.
- `]T`, `[T`: Next, Prev test.
- `]g`, `[g`: Next, Prev change.
- `]Space`, `[Space`: Add newline below, above.

== Commands
- `:w`, `:q`, `:wq`: Save, Quit, Both.
- `:e <file>`, `:o`: Open file.
- `:bn`, `:bp`: Next, Prev buffer.
- `:t <theme>`: Set theme.
- `:h <cmd>`: Help.
- `:tree-sitter-subtree`: View syntax tree.


= Configuration
== Editor (config.toml)
```toml
theme = "nord"
[editor]
line-number = "relative"
cursor-shape.insert = "bar"
true-color = true
```

== Key remapping
```toml
[keys.normal]
"C-s" = ":w"
"C-q" = ":q"
```

= Guides
- Languages: languages.toml to define LSPs.
- Queries: runtime/queries/ for TS features.
- Indents: indents.scm for auto-indent.
- Injections: injections.scm for combined languages.
