#import "../templates/conf.typ": *

#show: template.with(
  title: "Math Symbols & Notation",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= Arithmetic and Algebra

- $+$, $-$: Addition, Subtraction.
- $times$, $dot$, $*$: Multiplication.
- $div$, $slash$: Division.
- $plus.minus$: Plus-minus.
- $minus.plus$: Minus-plus.
- $approx$: Approximately equal.
- $scripts(eq.not)$: Not equal.
- $equiv$: Equivalent to / Defined as.
- $scripts(prop)$: Proportional to.
- $oo$: Infinity.
- $<$, $>$: Less than, Greater than.
- $<=$, >=: Less than or equal to, Greater than or equal to.
- $|x|$: Absolute value of $x$.
- $x^n$: $x$ to the power of $n$.
- $sqrt(x)$: Square root of $x$.
- $n!$: $n$ factorial.

= Set Theory

- $in$: Element of (e.g., $x in A$).
- $in.not$: Not an element of.
- $subset$: Proper subset.
- $subset.eq$: Subset (can be equal).
- $union$: Union.
- $inter$: Intersection.
- $nothing$: Empty set.
- $NN$: Natural numbers ($1, 2, 3, ...$).
- $ZZ$: Integers ($..., -1, 0, 1, ...$).
- $QQ$: Rational numbers.
- $RR$: Real numbers.
- $CC$: Complex numbers.

= Logic

- $forall$: For all.
- $exists$: There exists.
- $exists.not$: There does not exist.
- $=>$: Material implication (If... then).
- $<=>$: Biconditional (If and only if).
- $not, tilde$: Logical NOT.
- $and, \&$: Logical AND.
- $or$: Logical OR.
- $therefore$: Therefore.
- $because$: Because.

= Calculus and Analysis

- $diff y / diff x$: Derivative of $y$ with respect to $x$.
- $partial$: Partial derivative.
- $integral$: Integral.
- $integral.double, integral.triple$: Multiple integrals.
- $integral.cont$: Line integral over a closed curve.
- $lim_(x -> a)$: Limit as $x$ approaches $a$.
- $sum$: Summation.
- $product$: Product of a sequence.
- $Delta$: Delta (Difference or Change).
- $nabla$: Nabla (Gradient operator).

= Linear Algebra and Vectors

- $bold(v), vec(v)$: Vector $v$.
- $||bold(v)||$: Norm of vector $v$.
- $bold(A), bold(M)$: Matrices.
- $bold(A)^T$: Transpose of matrix $A$.
- $bold(A)^(-1)$: Inverse of matrix $A$.
- $det(bold(A))$: Determinant of matrix $A$.
- $times$: Cross product.
- $dot$: Dot product (Scalar product).
- $times.circle$: Kronecker product.

= Greek Letters (Commonly used)

- $alpha, beta, gamma$: Alpha, Beta, Gamma.
- $delta, Delta$: Delta.
- $epsilon, epsilon.alt$: Epsilon.
- $theta$: Theta (Angles).
- $lambda$: Lambda (Eigenvalues, Wavelength).
- $mu$: Mu (Mean, Micro).
- $pi$: Pi.
- $sigma, Sigma$: Sigma (Std dev, Summation).
- $phi, Phi$: Phi (Golden ratio, Flux).
- $omega, Omega$: Omega (Angular frequency, Resistance).
