#import "../templates/conf.typ": *

#show: template.with(
  title: "Regex Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= Character Classes

- `.`: Any character except newline.
- `\d`: Digit `[0-9]`.
- `\D`: Non-digit.
- `\w`: Word character (alphanumeric + underscore) `[a-zA-Z0-9_]`.
- `\W`: Non-word character.
- `\s`: Whitespace (space, tab, newline).
- `\S`: Non-whitespace.
- `\t`, `\n`, `\r`: Tab, Newline, Carriage return.

= Sets and Ranges

- `[abc]`: Any character from the set (a, b, or c).
- `[^abc]`: Any character NOT in the set.
- `[a-z]`: Characters from a to z.
- `[A-Z]`: Characters from A to Z.
- `[0-9]`: Digits from 0 to 9.

= Quantifiers

- `*`: 0 or more.
- `+`: 1 or more.
- `?`: 0 or 1.
- `{n}`: Exactly n times.
- `{n,}`: n or more times.
- `{n,m}`: Between n and m times.

= Anchors and Boundaries

- `^`: Start of string (or line in multiline mode).
- `$`: End of string (or line in multiline mode).
- `\b`: Word boundary.
- `\B`: Not a word boundary.

= Groups and References

- `(abc)`: Capturing group.
- `(?:abc)`: Non-capturing group.
- `(?<name>abc)`: Named capturing group.
- `\1`, `\2`: Backreference to a capturing group.
- `a|b`: Alternation (OR).

= Lookaround (Advanced)

- `(?=abc)`: Positive lookahead (followed by abc).
- `(?!abc)`: Negative lookahead (NOT followed by abc).
- `(?<=abc)`: Positive lookbehind (preceded by abc).
- `(?<!abc)`: Negative lookbehind (NOT preceded by abc).

= Common Examples

- Email: `^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`
- IPv4 Address: `^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$`
- Date (YYYY-MM-DD): `^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$`
- URL: `https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&//=]*)$`

= Flags

- `i`: Ignore case (case-insensitive).
- `g`: Global search (find all matches).
- `m`: Multiline mode (`^` and `$` match start/end of lines).
- `s`: Dotall mode (`.` matches newline).
- `u`: Unicode support.
- `y`: Sticky mode (matches from current position).
