#import "../templates/conf.typ": *

#show: template.with(
  title: "Warp Terminal Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= Modern Terminal Experience

Warp is a high-performance, Rust-based terminal designed for modern developers with native AI integration and block-oriented output.

- Reimagined Input: Text editor-style input with cursor management and selection.
- Blocks: Command output is grouped into logical blocks that can be shared or copied easily.
- AI Command Search: Natural language to shell command conversion.

= Navigation and Keyboard Shortcuts

- `Cmd + Space`: Search through command history (standard shell) and local blocks.
- `Cmd + T`: New Tab.
- `Cmd + D`: Split Pane (Vertical).
- `Cmd + Shift + D`: Split Pane (Horizontal).
- `Cmd + [` or `]`: Navigate through blocks.
- `Cmd + Shift + [ / ]`: Switch between tabs.
- `Cmd + Option + Arrow`: Switch between panes.

= AI Features

- `Ctrl + ` ` (Backtick)` or `#` : Open the AI Command Search.
- AI Chat: Integrated side panel for asking terminal or coding related questions.
- Explain Error: One-click button on failed command blocks to get an AI explanation of the error.

= Blocks Manipulation

- `Cmd + C`: Copy the command input or the selected block output.
- `Cmd + L`: Share a link to a block (with protected data filtering).
- Right-click block: Menu to filter, export, or bookmark a specific block.

= Workflow and Theme

- `Cmd + P`: Open Command Palette (access all Warp features).
- `Ctrl + Cmd + T`: Change Theme.
- Workflows: Reusable, shared command templates (`Ctrl + Shift + R`).

= Modern Editor Features

- Multi-cursor: `Cmd + Click` to add multiple cursors.
- Keybindings: Familiar shortcuts like `Cmd + A` (Select All) and `Cmd + V` (Paste) work as expected in the input area.


= Pro Tips

== Input Philosophy
Warp treats the input area like a modern IDE. You can use standard text selection, mouse clicks, and even undo/redo within your command before hitting Enter.

== Remote Development
Warp works seamlessly over SSH. While terminal features remain, AI and Warp-specific UI features are available locally while interacting with the remote server.

== Workflow Sharing
Create a `.warp/workflows` folder in your project to share common team commands that show up in the Warp search interface automatically.
