#import "../templates/conf.typ": *

#show: template.with(
  title: "Windows CMD Cheatsheet",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= Basic Navigation and File Operations

- `cd`: Change directory (`cd ..`: parent, `cd /d D:`: change drive and directory).
- `dir`: List files and directories in the current path.
- `path`: Display or set the executable search path.
- `mkdir` / `md`: Create a new directory.
- `rmdir` / `rd`: Remove a directory (`/s`: including subdirectories).
- `copy [src] [dest]`: Copy files.
- `xcopy`: Copy files and directory trees (advanced version of copy).
- `robocopy`: Robust file copy (Standard for large transfers and syncing).
- `move [src] [dest]`: Move or rename files/directories.
- `del` / `erase`: Delete one or more files.
- `type [file]`: Display the contents of a text file.
- `ren` / `rename`: Rename a file or directory.

= System and Disk Information

- `systeminfo`: Displays detailed configuration information about the PC.
- `ver`: Displays the Windows version.
- `hostname`: Displays the computer's network name.
- `tasklist`: Displays a list of currently running processes.
- `taskkill /pid [ID]`: Terminate a process by its ID (`/f`: force).
- `chkdsk`: Checks a disk and displays a status report.
- `diskpart`: Advanced disk partitioning utility.
- `format [drive]`: Formats a disk for use with Windows.

= Network Commands

- `ipconfig`: Displays all current TCP/IP network configuration values (`/all`: detailed).
- `ping [host]`: Verifies connectivity to a network host.
- `tracert [host]`: Traces the route taken to a network host.
- `netstat`: Displays active TCP connections and listening ports.
- `nslookup`: Queries DNS to find IP addresses or domain names.
- `getmac`: Displays the MAC addresses of network adapters.
- `net share`: Displays information about all shared resources on the computer.

= File Permissions and Attributes

- `attrib`: Displays or changes file attributes (Read-only, Hidden, etc.).
  - `attrib +h file`: Hide a file.
- `icacls`: Display or modify Access Control Lists (ACLs) for files and directories.

= Advanced Utilities

- `sfc /scannow`: Scans and repairs corrupted system files.
- `dism`: Deployment Image Servicing and Management tool (System repair).
- `assoc`: Displays or modifies file extension associations.
- `ftype`: Displays or modifies file types used in extension associations.
- `where [pattern]`: Finds files that match a pattern within the PATH.

= Environment Variables and Scripts

- `set`: Displays, sets, or removes environment variables for the current session.
- `setx`: Sets environment variables permanently (user or system level).
- `%VAR_NAME%`: Syntax to access a variable.
- `echo %PATH%`: Print the PATH variable.

= Redirection and Pipes

- `>`: Redirect output to a file (overwrite).
- `>>`: Append output to a file.
- `|`: Pipe output from one command to another.
- `&`: Run multiple commands in sequence.
- `&&`: Run the second command ONLY if the first succeeded.
- `||`: Run the second command ONLY if the first failed.


= Pro Tips

== Run as Administrator
Many system-level commands (e.g., `sfc`, `dism`, `netsh`) require elevated privileges. Right-click the Command Prompt and select "Run as Administrator".

== Command History
Press `F7` in the command prompt to see a popup list of your previous commands.

== Auto-completion
Press `Tab` to automatically complete file or directory names as you type.
