project:
  type: website
  output-dir: ../site_output

website:
  title: "Cheatsheets"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/partrita/cheatsheets

format:
  html:
    theme: flatly
    css: styles.css
    copy-code: true
