#import "./templates/conf.typ": *

#show: template.with(
  title: "fzf 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. fzf 개요

범용 커맨드라인 퍼지 파인더(fuzzy finder). 표준 입력을 대화형으로 필터링하여 선택 항목을 출력함.

= 2. 기본 사용법

- 파일 선택: `find . -type f | fzf`
- 디렉토리 선택: `find . -type d | fzf`
- 히스토리 선택: `history | fzf`

= 3. 셸 통합 단축키

- `Ctrl+T`: 현재 디렉토리 파일/디렉토리 검색 및 입력
- `Ctrl+R`: 명령어 히스토리 검색 및 입력
- `Alt+C`: 하위 디렉토리 검색 후 즉시 이동

= 4. 검색 구문

- `text`: 퍼지 매칭 (포함 여부)
- `'text`: 정확히 일치 (Exact-match)
- `^text` / `text$`: 시작/종료 일치
- `!text`: 제외 (Inverse-match)
- `|`: OR 조건 검색 (예: `py | js`)

= 5. 주요 옵션

- `--height [N%]`: 창 높이 지정
- `--layout=reverse`: 위에서 아래로 레이아웃 변경
- `--multi`: 다중 선택 활성화 (`Tab` 키 사용)
- `--preview 'command'`: 선택 항목 미리보기 (`{}`는 경로로 치환)
- `--bind 'key:action'`: 키 바인딩 설정

= 6. 미리보기 활용 예시

- 파일 내용: `fzf --preview 'cat {}'`
- 구문 강조: `fzf --preview 'bat --color=always {}'`
- 트리 구조: `fzf --preview 'tree -C {}'`

= 7. 도구 연동

- Git 브랜치 전환: `git branch | fzf | xargs git checkout`
- Git 로그 확인: `git log --oneline | fzf --preview 'git show {+1}'`
- 프로세스 종료: `ps -ef | fzf -m | awk '{print $2}' | xargs kill -9`

= 8. 환경 변수 설정

`~/.bashrc` 또는 `~/.zshrc`에 등록
```bash
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --preview="bat {}"'
```
