#import "./templates/conf.typ": *

#show: template.with(
  title: "NumPy 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. NumPy 개요

과학 계산 핵심 라이브러리. 다차원 배열 객체 및 처리 함수 제공.

```python
import numpy as np
```

= 2. 배열 생성 (Array Creation)

- 리스트 생성: `np.array([1, 2, 3])`
- 특정 값 채움 배열:
  - `np.zeros((2, 3))`: 2x3 크기 0 채움 배열
  - `np.ones((2, 3))`: 1 채움 배열
  - `np.full((2, 3), 7)`: 7 채움 배열
- 연속값 생성:
  - `np.arange(10, 30, 5)`: 10-30 사이 5씩 증가 배열
  - `np.linspace(0, 2, 9)`: 0-2 사이 9개 균일 간격 분할 배열
- 랜덤 배열:
  - `np.random.rand(2, 2)`: 0-1 사이 균등 분포
  - `np.random.randn(2, 2)`: 표준 정규 분포

= 3. 배열 속성 및 형태 변경

- `arr.shape`: 배열 차원 (튜플)
- `arr.ndim`: 차원 수
- `arr.size`: 전체 요소 수
- `arr.dtype`: 데이터 타입
- `arr.reshape(new_shape)`: 형태 변경
- `arr.T`: 전치(Transpose)

= 4. 인덱싱 및 슬라이싱

- 기본 인덱싱: `arr[2]`, `arr[1, 2]`
- 슬라이싱: `arr[0:5]`, `arr[:, 1]` (모든 행 1번 열)
- 불리언 인덱싱: `arr[arr > 2]`
- 팬시 인덱싱: `arr[[0, 1, 3]]` (특정 인덱스 선택)

= 5. 배열 연산

- 요소별 연산: `arr + 5`, `arr1 * arr2`
- 브로드캐스팅: 크기 다른 배열 간 연산 지원.
- 행렬 곱: `A.dot(B)` 또는 `A @ B`

= 6. 주요 함수 (Ufuncs)

- 집계 함수:
  - `sum()`, `min()`, `max()`, `mean()`, `std()`
  - 축 지정: `arr.sum(axis=0)` (열 기준 합계)
- 수학 함수: `np.sqrt()`, `np.exp()`, `np.log()`, `np.sin()`
- 비교 함수: `np.maximum(arr1, arr2)` (요소별 최댓값)

= 7. 배열 결합 및 분할

- `np.concatenate([arr1, arr2], axis=0)`: 축 기준 결합
- `np.vstack((arr1, arr2))`: 수직 결합 (행 추가)
- `np.hstack((arr1, arr2))`: 수평 결합 (열 추가)
- `np.split(arr, 3)`: 3개 분할
- `np.hsplit()`, `np.vsplit()`: 수평/수직 분할

= 8. 파일 입출력

- 텍스트 저장/로드:
  - `np.savetxt('file.txt', arr, delimiter=',')`
  - `np.loadtxt('file.txt', delimiter=',')`
- 바이너리 저장/로드:
  - `np.save('file.npy', arr)`
  - `np.load('file.npy')`
