#import "./templates/conf.typ": *

#show: template.with(
  title: "Django 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 프로젝트 및 앱 설정

- 프로젝트 시작:
  `django-admin startproject <project_name>`
- 앱 생성:
  `python manage.py startapp <app_name>`
- `settings.py` 앱 등록:
  ```python
  INSTALLED_APPS = [
      ...
      '<app_name>',
  ]
  ```
- 개발 서버 실행:
  `python manage.py runserver`

= 2. 모델 (Models)

`models.py` 내 데이터베이스 스키마 정의.

- 모델 정의:
  ```python
  from django.db import models

  class Post(models.Model):
      title = models.CharField(max_length=200)
      content = models.TextField()
      created_at = models.DateTimeField(auto_now_add=True)

      def __str__(self):
          return self.title
  ```
- 주요 필드 타입:
  - `CharField`, `TextField`, `IntegerField`, `FloatField`, `BooleanField`
  - `DateTimeField`, `DateField`, `TimeField`
  - `ForeignKey`, `ManyToManyField`, `OneToOneField`
- 마이그레이션:
  - `python manage.py makemigrations`: 모델 변경사항 마이그레이션 파일 생성.
  - `python manage.py migrate`: 마이그레이션 DB 적용.

= 3. 쿼리셋 (QuerySet) API

DB 상호작용 방법.

- 모든 객체 조회: `Post.objects.all()`
- 특정 객체 조회(PK): `Post.objects.get(pk=1)`
- 필터링:
  `Post.objects.filter(title__startswith='Django')`
  `Post.objects.exclude(created_at__year=2023)`
- 정렬: `Post.objects.order_by('-created_at')`
- 객체 생성: `Post.objects.create(title='New', content='...')`
- 객체 수정/저장:
  ```python
  post = Post.objects.get(pk=1)
  post.title = 'Updated'
  post.save()
  ```
- 객체 삭제: `post.delete()`

= 4. 뷰 (Views)

`views.py` 내 비즈니스 로직 작성.

- 함수 기반 뷰 (FBV):
  ```python
  from django.shortcuts import render
  from .models import Post

  def post_list(request):
      posts = Post.objects.all()
      return render(request, 'app/post_list.html', {'posts': posts})
  ```
- 클래스 기반 뷰 (CBV):
  ```python
  from django.views.generic import ListView
  from .models import Post

  class PostListView(ListView):
      model = Post
      template_name = 'app/post_list.html'
      context_object_name = 'posts'
  ```

= 5. URL 설정

`urls.py` 내 URL 패턴-뷰 연결.

- 프로젝트 `urls.py`:
  ```python
  from django.urls import path, include

  urlpatterns = [
      path('admin/', admin.site.urls),
      path('app/', include('app_name.urls')),
  ]
  ```
- 앱 `urls.py`:
  ```python
  from django.urls import path
  from . import views

  urlpatterns = [
      path('', views.post_list, name='post_list'),
  ]
  ```

= 6. 템플릿 (Templates)

HTML 내 DTL(Django Template Language) 사용.

- 변수 출력: `{{ my_variable }}`
- 제어 태그:
  ```html
  {% for post in posts %}
      <h2>{{ post.title }}</h2>
  {% endfor %}

  {% if user.is_authenticated %}...{% endif %}
  ```
- URL 참조: `{% url 'post_list' %}`
- 상속: `{% extends 'base.html' %}`, `{% block content %}{% endblock %}`

= 7. 폼 (Forms)

`forms.py` 내 폼 정의.

```python
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']
```
- 뷰 폼 처리:
  ```python
  def post_create(request):
      if request.method == 'POST':
          form = PostForm(request.POST)
          if form.is_valid(): form.save()
      else:
          form = PostForm()
      return render(request, 'app/post_form.html', {'form': form})
  ```
- 템플릿 폼 렌더링:
  ```html
  <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Save</button>
  </form>
  ```

= 8. 관리자 (Admin)

`admin.py` 모델 등록 및 관리자 페이지 관리.

```python
from django.contrib import admin
from .models import Post

admin.site.register(Post)
```
- 관리자 계정 생성: `python manage.py createsuperuser`
