#import "./templates/conf.typ": *

#show: template.with(
  title: "임상관련 용어 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by me",
)

== 1. 자주 사용되는 약어
- *Q3W (Every 3 Weeks):* 3주(21일) 간격 약물 투여 주기.
- *AE (Adverse Event):* 이상 반응.
- *RP2D (Recommended Phase 2 Dose):* 2상 시험 추천 용량.
- *TTR (Time To Response):* 반응 도달 시간.
- *DoR (Duration of Response):* 반응 지속 기간.
- *DCR (Disease Control Rate):* 질병 통제율.

== 2. RECIST 1.1 기준
*Response Evaluation Criteria In Solid Tumors (고형암 반응 평가 기준)*

#table(
  columns: (1fr, 1fr, 1.5fr),
  inset: 8pt,
  align: horizon,
  table.header([반응 유형], [표적 병변], [신규 병변]),
  [CR (Complete Response)], [100% 감소], [없음],
  [PR (Partial Response)], [30% 이상 감소], [없음 또는 안정],
  [SD (Stable Disease)], [PR/PD 미달], [없음 또는 안정],
  [PD (Progressive Disease)], [20% 이상 증가], [진행 여부 무관]
)

== 3. CTCAE
*Common Terminology Criteria for Adverse Events (공통 용어 부작용 기준)*

- *Grade 1 (Mild):* 경미 (무증상, 약한 증상).
- *Grade 2 (Moderate):* 중등도 (일상생활 제한).
- *Grade 3 (Severe):* 중증 (입원 필요, 자가 관리 제한).
- *Grade 4 (Life-threatening):* 생명 위협.
- *Grade 5 (Death):* 사망.

== 4. 주요 평가 지표
- *ORR (Objective Response Rate):* 객관적 반응률. 종양 크기 감소 환자 비율.
  - *All Line:* 1차~3차 이상 전체 치료 라인 대상 평가.
  - *Second Line:* 1차 실패 후 2차 치료 평가. 내성 환자 대상 효과 확인.
- *DCR (Disease Control Rate):* 질병 통제율. SD 포함 약물 조절 효과 확인.
- *PFS (Progression-Free Survival):* 무진행 생존율. 질병 진행/사망 없는 기간.
- *OS (Overall Survival):* 전체 생존율. 치료 후 사망까지의 기간. 최종 효능 지표.

== 5. 부가 지표
- *MTD (Maximum Tolerated Dose):* 최고 내약 용량. 안전하게 견디는 최고 용량.
- *DLT (Dose-Limiting Toxicity):* 용량 제한 독성. MTD 산출의 결정적 기준.
- *RDE (Recommended Dose for Expansion):* 추천 용량. 확장 코호트 진행 용량.
- *PK (Pharmacokinetics):* 약동학. 체내 약물 흡수, 분포, 대사, 배설 연구.
- *PD (Pharmacodynamics):* 약력학. 약물이 인체에 미치는 생리적 영향 연구.
- *Cmax (Maximum Concentration):* 최고 혈중 농도. 독성 발생 가능성 평가 지표.
- *Tmax (Time to Maximum Concentration):* 최고 농도 도달 시간. 흡수 속도 지표.

== 6. Adverse Events (이상반응 상세)
- *TRAE (Treatment-Related Adverse Event):* 치료 관련 이상반응. 약물 인과관계 의심 사례.
- *TEAE (Treatment-Emergent Adverse Event):* 치료 중 발생한 이상반응. 투여 후 발생/악화 사례.
- *irAE (Immune-Related Adverse Event):* 면역 관련 이상반응. 면역항암제 특이 부작용.
- *SAE (Serious Adverse Event):* 중대한 이상반응. 사망/생명 위협 등 신속 보고 대상.
- *TESAE (Treatment-Emergent Serious Adverse Event):* 치료 중 발생한 중대한 이상반응.
- *AST/ALT (Aspartate/Alanine Aminotransferase):* 간 효소 수치. 간 독성 모니터링 지표.