#import "./templates/conf.typ": *

#show: template.with(
  title: "Kotlin 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 변수, 타입, Null 안정성

- 변수 선언:
  - `val`: 읽기 전용 (immutable) 변수. Java의 `final` 대응
  - `var`: 재할당 가능 (mutable) 변수
- 타입 추론: `val name = "Kotlin"` (String 자동 추론)
- 기본 타입: `Int`, `Double`, `Boolean`, `Char`, `String` 등 (모두 객체)
- Null 안정성 (Null Safety):
  - `String?`: Null 허용 타입
  - `String`: Null 불허 타입
  - 안전한 호출: `obj?.prop` (Null이면 Null 반환)
  - 엘비스 연산자: `obj ?: "default"` (Null이면 우측 값 반환)
  - Not-null 단언: `obj!!` (Null이면 NPE 발생, 주의)

= 2. 제어 흐름

- `if-else`: 표현식으로 사용 가능
  ```kotlin
  val max = if (a > b) a else b
  ```
- `when`: Java의 `switch`를 대체하는 강력한 조건문
  ```kotlin
  when (x) {
      1 -> print("x == 1")
      2, 3 -> print("2 또는 3")
      in 4..7 -> print("범위 내 존재")
      is String -> print("문자열 타입")
      else -> print("기타")
  }
  ```
- 루프:
  ```kotlin
  for (item in coll) print(item)
  for (i in 1..5) { ... }      // 1~5 포함
  for (i in 1 until 5) { ... } // 5 미포함
  for (i in 5 downTo 1 step 2) { ... } // 5, 3, 1
  ```

= 3. 함수

- 정의: `fun` 키워드 사용
  ```kotlin
  fun sum(a: Int, b: Int): Int = a + b // 단일 표현식 함수
  ```
- 기본 인수: `fun greet(name: String, msg: String = "Hi")`
- 명명된 인수: `greet(msg = "Hello", name = "Kim")`

= 4. 클래스와 객체

- 클래스 정의:
  ```kotlin
  class Person(val name: String) { // 주 생성자
      var age: Int = 0
  }
  ```
- 데이터 클래스 (Data Class): `equals`, `hashCode`, `toString`, `copy` 자동 생성
  ```kotlin
  data class User(val name: String, val age: Int)
  ```
- 상속: `open` 키워드 필요. `:` 사용
  ```kotlin
  open class Shape
  class Rectangle : Shape()
  ```
- 인터페이스: `interface MyInterface { fun method() }`
- 객체 (Object): 싱글턴(Singleton) 정의 시 사용
  ```kotlin
  object Manager { fun work() { ... } }
  ```

= 5. 확장 기능 (Extensions)

기존 클래스 수정 없이 함수/프로퍼티 추가
```kotlin
fun String.initials(): String = split(' ').map { it.first() }.joinToString("")
```

= 6. 고차 함수와 람다

- 람다 표현식: `{ 인자 -> 본문 }`
- 컬렉션 함수: `filter`, `map`, `forEach`, `reduce` 등
  ```kotlin
  val evens = list.filter { it % 2 == 0 }
  val squared = list.map { it * it }
  ```

= 7. 코루틴 (Coroutines)

비동기 프로그래밍 지원
- `suspend` 함수: 일시 중단 가능 함수
- 빌더:
  - `launch`: 결과 없는 코루틴 실행
  - `async`: `Deferred` 결과 반환 (await로 수신)
  - `runBlocking`: 코루틴 완료까지 스레드 블로킹

= 8. 스코프 함수 (Scope Functions)

객체 컨텍스트 내 코드 실행
- `let`: Null 체크 및 결과 반환 시 주로 사용
- `apply`: 객체 속성 설정 및 자신 반환
- `run`, `with`, `also` 등 상황에 따라 선택

