#import "./templates/conf.typ": *

#show: template.with(
  title: "Scikit-learn 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 기본 워크플로우

1.  *데이터 준비*: 특성(X)/타겟(y) 분리.
2.  *모델 선택*: 문제 적합 모델 임포트.
3.  *모델 인스턴스화*: 하이퍼파라미터 설정.
4.  *학습*: `model.fit(X, y)`.
5.  *예측*: `model.predict(X_new)`.
6.  *평가*: 성능 측정.

= 2. 데이터 전처리 (Preprocessing)

- 스케일링 (Scaling):
  - `StandardScaler`: 평균 0, 분산 1 조정.
  - `MinMaxScaler`: 0-1 사이 조정.
  - `RobustScaler`: 이상치에 강한 중앙값/사분위수 기반 조정.
- 인코딩 (Encoding):
  - `LabelEncoder`: 범주형 텍스트 숫자로 변환.
  - `OneHotEncoder`: 범주형 변수 원-핫 벡터 변환.
- 결측치 처리:
  - `SimpleImputer`: 평균, 중앙값 등 결측치 대체.

```python
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
```

= 3. 모델 선택

== 지도 학습 (Supervised Learning)
- 회귀 (Regression):
  - `LinearRegression`, `Ridge`, `Lasso`
  - `SVR` (Support Vector Regressor)
  - `RandomForestRegressor`, `GradientBoostingRegressor`
- 분류 (Classification):
  - `LogisticRegression`, `SVC`
  - `KNeighborsClassifier`, `DecisionTreeClassifier`
  - `RandomForestClassifier`, `GradientBoostingClassifier`

== 비지도 학습 (Unsupervised Learning)
- 군집 (Clustering): `KMeans`, `DBSCAN`
- 차원 축소: `PCA`, `TSNE`

= 4. 데이터 분할 및 교차 검증

- 학습/테스트 분할:
  ```python
  from sklearn.model_selection import train_test_split
  X_train, X_test, y_train, y_test = train_test_split(
      X, y, test_size=0.2, random_state=42
  )
  ```
- 교차 검증:
  ```python
  from sklearn.model_selection import cross_val_score
  scores = cross_val_score(model, X, y, cv=5)
  ```

= 5. 모델 평가 (Metrics)

== 회귀 평가 지표
- `mean_absolute_error` (MAE)
- `mean_squared_error` (MSE)
- `r2_score` (R-squared)

== 분류 평가 지표
- `accuracy_score`: 정확도
- `precision_score`: 정밀도
- `recall_score`: 재현율
- `f1_score`: F1 점수
- `confusion_matrix`: 혼동 행렬
- `roc_auc_score`: ROC AUC

```python
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
```

= 6. 하이퍼파라미터 튜닝

- 그리드 서치 (Grid Search):
  ```python
  from sklearn.model_selection import GridSearchCV
  param_grid = {'n_estimators': [100, 200], 'max_depth': [3, 5]}
  grid_search = GridSearchCV(model, param_grid, cv=5)
  grid_search.fit(X_train, y_train)
  ```
- 랜덤 서치 (Randomized Search): `RandomizedSearchCV`

= 7. 파이프라인 (Pipeline)

전처리 및 학습 단계 통합 관리.

```python
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('svc', SVC())
])

pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)
```
