#import "./templates/conf.typ": *

#show: template.with(
  title: "Pandas 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. Pandas 개요

데이터 조작 및 분석 핵심 라이브러리. Series(1차원), DataFrame(2차원) 구조 제공.

```python
import pandas as pd
```

= 2. 데이터 구조 생성

== Series
```python
s = pd.Series([1, 3, 5, np.nan, 6, 8])
```

== DataFrame
- 딕셔너리 생성:
  ```python
  data = {'Name': ['Tom', 'Nick', 'Juli'], 'Age': [20, 21, 19]}
  df = pd.DataFrame(data)
  ```
- 파일 읽기:
  `df = pd.read_csv('data.csv')`, `pd.read_excel('data.xlsx')`

= 3. 데이터 확인 및 탐색

- `df.head(n)`: 처음 n개 행 표시 (기본 5)
- `df.tail(n)`: 마지막 n개 행 표시
- `df.info()`: DataFrame 요약 정보 (인덱스, 컬럼, 결측치, 메모리 등)
- `df.describe()`: 수치형 데이터 기술 통계 요약
- `df.shape`: (행, 열) 크기
- `df.columns`: 컬럼 이름 목록
- `df.index`: 인덱스 정보
- `df.sort_values(by='col')`: 특정 컬럼 기준 정렬

= 4. 데이터 선택 (Selection)

== 컬럼 선택
- `df['col']` (Series 반환)
- `df[['c1', 'c2']]` (DataFrame 반환)

== 행 선택
- `df[0:3]`: 행 슬라이싱

== 라벨 기반 선택 (`.loc`)
- `df.loc[label]`: 단일 행 선택
- `df.loc[:, ['A', 'B']]`: 모든 행 A, B 컬럼 선택
- `df.loc['start':'end', ['A', 'B']]`: 범위 및 컬럼 선택

== 위치 기반 선택 (`.iloc`)
- `df.iloc[3]`: 3번 위치 행 선택
- `df.iloc[3:5, 0:2]`: 정수 위치 슬라이싱

== 조건부 선택
- `df[df['A'] > 0]`: 조건 만족 행 선택
- `df[df['country'].isin(['USA', 'Canada'])]`: 포함 조건 행 선택

= 5. 데이터 조작

== 결측치 처리
- `df.dropna()`: 결측치 포함 행 제거
- `df.fillna(value=5)`: 결측치 특정 값 대체
- `pd.isna(df)`: 결측치 여부 확인

== 데이터 변경
- `df['C'] = df['A'] + df['B']`: 새 컬럼 추가
- `df.at[idx, 'col'] = val`: 특정 위치 값 변경 (고속)
- `df.iat[r, c] = val`: 정수 위치 값 변경 (고속)
- `df.apply(func)`: 함수 적용

= 6. GroupBy

데이터 그룹화 및 집계 연산.

```python
df.groupby('A').sum()
df.groupby(['A', 'B']).mean()
```

= 7. 데이터 병합 (Merge, Concat)

== Concat (연결)
```python
pd.concat([df1, df2])
```

== Merge (병합)
SQL 스타일 조인.
```python
pd.merge(left, right, on='key', how='inner')
```
- `how`: `inner`, `left`, `right`, `outer`

= 8. 데이터 입출력

- CSV 저장: `df.to_csv('output.csv', index=False)`
- Excel 저장: `df.to_excel('output.xlsx', sheet_name='Sheet1')`

= 9. 시계열 데이터 (Time Series)

- 날짜 범위 생성: `pd.date_range('20230101', periods=6)`
- 리샘플링: `ts.resample('M').sum()` (월별 합계)

= 10. 피벗 테이블 (Pivot Tables)

```python
pd.pivot_table(df, values='D', index=['A', 'B'], columns=['C'])
```
