#import "./templates/conf.typ": *

#show: template.with(
  title: "lf (list files) 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 기본 개념
`lf`는 Go 기반 터미널 파일 관리자임. `ranger` 영감, 서버-클라이언트 아키텍처 기반 인스턴스 간 상태 공유. Vim 유사 키 바인딩 기반 효율적 파일 시스템 탐색 및 관리 지원함.

= 기본 이동
- `k`, `up`: 위로 이동
- `j`, `down`: 아래로 이동
- `h`, `left`: 상위 디렉토리 이동
- `l`, `right`: 파일 열기 또는 디렉토리 진입
- `gg`: 목록 최상단 이동
- `G`: 목록 최하단 이동
- `H`: 화면 최상단 이동
- `M`: 화면 중간 이동
- `L`: 화면 최하단 이동
- `~`: 홈 디렉토리 이동
- `gh`: 홈 디렉토리 이동 (go home)

= 파일 조작
- `space`: 파일 선택/해제. 다중 선택 가능
- `d`: 선택 파일 삭제 (`~/.local/share/lf/trash` 이동)
- `D`: 선택 파일 영구 삭제
- `y`: 선택 파일 복사 (yank)
- `c`: 선택 파일 잘라내기 (cut)
- `p`: 현재 디렉토리 복사/잘라내기 파일 붙여넣기 (paste)
- `r`: 파일 이름 변경 (rename)
- `:mkdir <name>`: 새 디렉토리 생성
- `:touch <name>`: 새 파일 생성
- `:link <target>`: 심볼릭 링크 생성

= 검색 및 필터링
- `/`: 검색 모드 진입. 입력 시 실시간 파일 필터링
- `f`: 필터 모드 진입. `find` 유사 동작
- `?`: 검색 기록 조회

= 셸 명령어 실행
- `!`: 외부 셸 명령 실행 (예: `!echo "hello"`)
- `$`: 셸 프롬프트 열람 및 현재 디렉토리 작업 수행. `lf` 복귀 시 `exit` 입력
- `c`: 셸 명령 기반 `lf` 상호작용 클라이언트 모드

= 보기 모드 및 정렬
- `zh`: 숨김 파일 표시 토글
- `zr`: 정렬 순서 반전 (reverse)
- `zs`: 이름(n), 크기(s), 시간(t) 기준 정렬 변경
- `zp`: 미리보기 창 표시 토글

= 탭 및 창
`lf` 자체 탭 기능 미내장. 터미널 멀티플렉서(`tmux`, `zellij` 등) 병행 시 다수 인스턴스 실행 가능. 서버-클라이언트 아키텍처 기반 인스턴스 간 상태 공유함.

= 사용자 정의
`lf`는 `~/.config/lf/lfrc` 기반 사용자 정의 가능함.
- *키 바인딩 변경*: `map gh cd ~`
- *사용자 정의 명령어*: `cmd my-command echo "hello"`
- *셸 스크립트 미리보기 설정*:
  ```bash
  # lfrc 예시
  set previewer "/path/to/your/preview/script.sh"
  ```
- *색상 테마 설정*: `set colors ...`

= 종료
- `q`: `lf` 종료. 종료 시 마지막 디렉토리 `cd` 설정 가능함
  ```bash
  # .bashrc 또는 .zshrc에 추가
  lfcd () {
      tmp="$(mktemp)"
      lf -last-dir-path="$tmp" "$@"
      if [ -f "$tmp" ]; then
          dir="$(cat "$tmp")"
          rm -f "$tmp"
          if [ -d "$dir" ]; then
              if [ "$dir" != "$(pwd)" ]; then
                  cd "$dir"
              fi
          fi
      fi
  }
  # 이제 'lf' 대신 'lfcd'를 사용
  ```
