#import "./templates/conf.typ": *

#show: template.with(
  title: "Glob 패턴 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. Glob 패턴이란?

Glob 패턴은 와일드카드 문자를 사용하여 여러 파일을 한 번에 지정하는 방법입니다. 주로 셸 환경에서 파일 경로를 확장하는 데 사용됩니다. `*`, `?`와 같은 특수 문자를 사용하여 패턴과 일치하는 파일 이름들을 찾습니다.

= 2. 기본 와일드카드

- `*`: 0개 이상의 모든 문자와 일치합니다.
  - 예: `*.txt` -> `.txt`로 끝나는 모든 파일 (e.g., `a.txt`, `hello.txt`)
  - 예: `a*` -> `a`로 시작하는 모든 파일 (e.g., `a.txt`, `apple`)

- `?`: 정확히 하나의 문자와 일치합니다.
  - 예: `?.txt` -> 한 글자 이름과 `.txt` 확장자를 가진 파일 (e.g., `a.txt`, `b.txt`)
  - 예: `file?.log` -> `file1.log`, `file2.log` 등과 일치

- `[]`: 대괄호 안의 문자 중 하나와 일치합니다.
  - 예: `[abc].log` -> `a.log`, `b.log`, `c.log`와 일치
  - 범위 지정: `[a-z]`, `[0-9]`
    - 예: `[a-c].log` -> `a.log`, `b.log`, `c.log`
  - 부정: `[!abc]` 또는 `[^abc]` (셸에 따라 다름)
    - 예: `[!a-z].txt` -> 알파벳 소문자로 시작하지 않는 파일

= 3. 확장 및 고급 패턴

- `**`: 현재 디렉토리 및 모든 하위 디렉토리를 재귀적으로 탐색합니다. (zsh, bash 4+ 등에서 지원)
  - 예: `**/README.md` -> 모든 하위 디렉토리에서 `README.md` 파일을 찾습니다.

- `{}` (Brace Expansion): 쉼표로 구분된 문자열 목록을 생성합니다. 엄밀히 말해 glob은 아니지만 함께 자주 사용됩니다.
  - 예: `mv file.{txt,md}` -> `mv file.txt file.md`
  - 예: `touch {a,b,c}.js` -> `a.js`, `b.js`, `c.js` 파일 생성

= 4. 주요 사용 예시

- 모든 `.jpg` 및 `.png` 파일 찾기:
  ```bash
  ls *.{jpg,png}
  ```

- `src` 디렉토리 아래의 모든 `.js` 파일 찾기:
  ```bash
  ls src/**/*.js
  ```

- 이름이 'test'로 시작하고, 그 뒤에 숫자가 하나 오는 파일 찾기:
  ```bash
  ls test[0-9].*
  ```

- 숨김 파일을 제외한 모든 파일 선택:
  ```bash
  ls *
  ```

- 숨김 파일까지 포함한 모든 파일 선택 (셸 설정에 따라 다름):
  ```bash
  ls .* *
  ```

= 5. 셸별 차이점

Globbing의 동작은 사용하는 셸(bash, zsh, fish 등)에 따라 약간씩 다를 수 있습니다. 예를 들어, `**`와 같은 고급 기능은 최신 버전의 셸에서만 지원될 수 있습니다. `shopt -s globstar` (bash)와 같은 명령어로 특정 기능을 활성화해야 할 수도 있습니다.
