#import "./templates/conf.typ": *

#show: template.with(
  title: "uv 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= uv 사용 가이드: Python 고속 프로젝트 도구

Rust 기반 초고속 Python 패키지 설치 및 환경 관리 도구. `pip`, `pip-tools`, `venv` 통합. 고속 Python 개발 워크플로우 제공.

= 1. 프로젝트 초기화 및 가상 환경 관리 (`uv init`, `uv venv`)

프로젝트 시작 및 가상 환경 생성/관리 최적화.

- `uv init`: 현재 디렉토리 uv 프로젝트 초기화. `pyproject.toml`, `uv.lock` 생성.
- `uv venv`: `.venv` 가상 환경 생성.
    - `uv venv my-env`: `my-env` 이름 가상 환경 생성.
- `uv venv --python <version>`: 특정 Python 버전 가상 환경 생성.
- `uv venv --seed`: `pip`, `setuptools`, `wheel` 사전 설치.
- 가상 환경 활성화:
    - Linux/macOS: `source .venv/bin/activate`
    - Windows: `.venv\Scripts\activate`
- 가상 환경 비활성화: `deactivate`


= 2. 패키지 추가 및 제거 (`uv add`, `uv remove`)

의존성 추가/제거 및 환경 동기화 자동 처리.

- `uv add <package>`: 의존성 추가 및 설치.
- `uv remove <package>`: 의존성 제거 및 삭제.


= 3. 환경 동기화 (`uv sync`)

파일 정의 기반 환경 완전 일치화.

- `uv sync`: `pyproject.toml`/`uv.lock` 기반 활성 환경 동기화.


= 4. 종속성 고정 및 해결 (`uv lock`)

의존성 버전 고정 및 업데이트.

- `uv lock`: `uv.lock` 업데이트. 모든 종속성 정확한 버전 기록.


= 5. 패키지 확인 (`uv pip list`, `uv pip freeze`, `uv pip check`)

설치된 패키지 확인 및 검증.

- `uv pip list`: 설치 목록 표시.


= 6. 캐시 관리 (`uv cache`)

로컬 캐시 효율적 관리로 공간 확보 및 문제 해결.

- `uv cache clean`: 모든 캐시 삭제.


= uv 활용 워크플로우 예시

1. 프로젝트 초기화:
```bash
uv init my-new-project
cd my-new-project
```
2. 의존성 추가:
```bash
uv add fastapi uvicorn
```
3. 개발 의존성 추가:
```bash
uv add pytest --group dev
```
4. 환경 동기화:
```bash
uv sync
```
5. 스크립트 실행:
```bash
uv run uvicorn main:app --reload
```

= pyproject.toml 예시

```toml
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my-awesome-package"
version = "0.1.0"
description = "멋진 Python 패키지 예시"
dependencies = [
    "requests>=2.25.1",
    "beautifulsoup4<5.0.0",
]
```
