#import "./templates/conf.typ": *

#show: template.with(
  title: "PHP 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 기본 구문

- PHP 태그: `<?php ... ?>`
- 주석: `//`, `#` (한 줄), `/* ... */` (여러 줄)
- 출력: `echo`, `print`
- 변수: `$` 접두사 사용. 문자/밑줄 시작 필수. `$name = "Jules";`
- 문자열 연결: `.` 연산자 사용.
- 문자열 보간: 큰따옴표 내 변수 사용. `echo "Hello, $name";`

= 2. 타입 및 연산자

- 타입: `String`, `Integer`, `Float`, `Boolean`, `Array`, `Object`, `NULL`.
- 배열:
  - 인덱스 배열: `$cars = ["Volvo", "BMW"];`
  - 연관 배열: `$ages = ["Peter"=>35, "Ben"=>37];`
- 연산자: 타 언어와 유사.
- 삼항 연산자: `(condition) ? true_expr : false_expr;`
- Null 병합 연산자 (PHP 7+): `$user = $_GET['user'] ?? 'nobody';`

= 3. 제어 흐름

- `if-elseif-else`:
  ```php
  if (condition) { ... }
  elseif (condition) { ... }
  else { ... }
  ```
- `switch`:
  ```php
  switch ($variable) {
    case "val": ... break;
    default: ...
  }
  ```
- 반복문: `while`, `do-while`, `for`
- `foreach`:
  ```php
  foreach ($colors as $value) { echo "$value\n"; }
  ```

= 4. 함수

- 함수 정의:
  ```php
  function greet($name = "Guest") {
    return "Hello, $name!";
  }
  ```
- 타입 힌팅: `function add(int $a, int $b): int { ... }`

= 5. 클래스와 객체 (OOP)

- 클래스 정의:
  ```php
  class Car {
    public $color;
    public function __construct(public string $model) {}
    public function drive() { return "Driving $this->model!"; }
  }
  ```
- 인스턴스: `$myCar = new Car("Tesla");`
- 멤버 접근: `$myCar->drive();`
- 기타: `extends` (상속), `interface`, `trait` 지원.

= 6. 슈퍼글로벌 (Superglobals)

전역 접근 가능 내장 변수.
- `$_GET` / `$_POST`: 요청 데이터
- `$_REQUEST`: GET, POST, COOKIE 통합
- `$_SERVER`: 서버/실행 환경 정보
- `$_SESSION` / `$_COOKIE`: 세션 및 쿠키
- `$_FILES`: 업로드 파일 정보

= 7. 파일 처리

- 읽기: `$content = file_get_contents("file.txt");`
- 쓰기: `file_put_contents("file.txt", "content");`

= 8. 데이터베이스 연동 (PDO)

DB 일관 접근 인터페이스.

```php
try {
     $pdo = new PDO($dsn, $user, $pass, $options);
} catch (\PDOException $e) { ... }

// 쿼리 실행
$stmt = $pdo->query('SELECT name FROM users');
while ($row = $stmt->fetch()) { echo $row['name']; }

// Prepared Statement
$stmt = $pdo->prepare('SELECT * FROM users WHERE email = ?');
$stmt->execute([$email]);
```

= 9. Composer

PHP 의존성 관리 도구.
- `composer.json`: 프로젝트 의존성 정의 파일.
- `composer install`: 정의된 종속성 설치.
- `composer update`: 종속성 최신 업데이트.
- `composer require vendor/package`: 새 종속성 추가.
- Autoloading: `require 'vendor/autoload.php';`
