#import "./templates/conf.typ": *

#show: template.with(
  title: "C# 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 기본 구조 및 실행

`C#` 프로그램은 네임스페이스, 클래스, `Main` 메서드로 구성

```csharp
using System;
namespace MyApp {
    class Program {
        static void Main(string[] args) {
            Console.WriteLine("Hello, C#!");
        }
    }
}
```
- 실행: `dotnet run`

= 2. 변수와 데이터 타입

- 값 타입: `int`, `double`, `bool`, `char`, `decimal`, `struct`, `enum`
- 참조 타입: `string`, `object`, `class`, `interface`, `delegate`, `array`
- `var`: 컴파일러 타입 자동 추론
- 상수: `const`
- Nullable: `int?` (null 허용)

= 3. 제어 흐름

- 조건문: `if-else`, `switch` (패턴 매칭 지원)
- 루프:
  - `for`, `while`, `do-while`
  - `foreach`: `foreach (var item in coll) { ... }`

= 4. 클래스와 객체 (OOP)

- 클래스 정의:
  ```csharp
  public class Car {
      public string Color { get; set; } // 프로퍼티
      public int Speed { get; private set; }
      public Car(string color) { Color = color; } // 생성자
      public void Accelerate(int n) { Speed += n; } // 메서드
  }
  ```
- 상속: `public class ElectricCar : Car { ... }`
- 인터페이스: `public interface IDrivable { void Drive(); }`

= 5. 컬렉션 (Generic)

- `List<T>`: 가변 크기 리스트
- `Dictionary<K, V>`: 키-값 쌍 저장소

= 6. LINQ (쿼리 기능)

데이터 소스 통합 쿼리
```csharp
var list = new List<int> { 1, 2, 3, 4 };
// 메서드 구문
var res = list.Where(n => n > 2).ToList();
// 쿼리 구문
var query = from n in list where n > 2 select n;
```

= 7. 예외 처리

- `try-catch-finally`: 에러 대응 및 자원 해제
- `throw`: 예외 강제 발생

= 8. 비동기 프로그래밍

`async`/`await` 기반 논블로킹 작업
```csharp
public async Task<string> FetchAsync() {
    using var client = new HttpClient();
    return await client.GetStringAsync(url);
}
```
