#import "./templates/conf.typ": *

#show: template.with(
  title: "Neovim 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

// 여기에 문서 내용을 작성하세요

= 명령어 가이드

Neovim은 효율적인 작업을 위해 다양한 키보드 명령어를 제공합니다. 
다음은 자주 사용되는 주요 명령어들을 기능별로 분류하여 정리한 것입니다.

== 커서 이동 (Moving Around)

- `h`: 커서를 왼쪽으로 이동
- `j`: 커서를 아래로 이동
- `k`: 커서를 위로 이동
- `l`: 커서를 오른쪽으로 이동
- `0`: 커서를 현재 줄의 맨 앞으로 이동
- `^`: 커서를 현재 줄의 첫 번째 비공백 문자로 이동
- `$`: 커서를 현재 줄의 맨 뒤로 이동
- `gg`: 커서를 파일의 맨 앞으로 이동
- `G`: 커서를 파일의 맨 뒤로 이동
- `5G`: 커서를 5번째 줄로 이동

== 파일 관리 (File Management)

- `:e filename`: 편집할 파일 열기
- `:w`: 현재 버퍼를 디스크에 저장
- `:w filename`: 현재 버퍼를 `filename`으로 저장
- `:q`: 현재 창 닫기
- `:wq`: 저장하고 현재 창 닫기
- `:q!`: 저장하지 않고 현재 창 닫기
- `:wa`: 열려 있는 모든 버퍼를 디스크에 저장

== 편집 명령 I (Editing Commands I)

- `i`: 커서 앞에 삽입 모드로 진입
- `a`: 커서 뒤에 삽입 모드로 진입
- `I`: 현재 줄의 맨 앞에 삽입 모드로 진입
- `A`: 현재 줄의 맨 뒤에 삽입 모드로 진입
- `o`: 현재 줄 아래에 새 줄을 삽입하고 삽입 모드로 진입
- `O`: 현재 줄 위에 새 줄을 삽입하고 삽입 모드로 진입

== 편집 명령 II (Editing Commands II)

- `dd`: 현재 줄 삭제
- `D`: 커서부터 줄 끝까지 삭제
- `C`: 커서부터 줄 끝까지 변경하고 삽입 모드로 진입
- `u`: 마지막 변경 사항 실행 취소
- `cw`: 커서부터 단어 끝까지 변경하고 삽입 모드로 진입
- `cb`: 커서부터 단어 시작까지 변경하고 삽입 모드로 진입

== 비주얼 모드 (Visual Mode Commands)

- `v`: 비주얼 모드 진입 (문자 단위 선택)
- `V`: 비주얼 모드 진입 (줄 단위 선택)
- `y`: 선택된 텍스트 복사 (yank)
- `d`: 선택된 텍스트 삭제
- `c`: 선택된 텍스트 변경하고 삽입 모드로 진입

== 검색 및 바꾸기 (Search and Replace)

- `/pattern`: `pattern`을 파일에서 앞으로 검색
- `?pattern`: `pattern`을 파일에서 뒤로 검색
- `n`: 이전 검색을 같은 방향으로 반복
- `N`: 이전 검색을 반대 방향으로 반복
- `:%s/pattern/replacement/g`: 파일 전체에서 `pattern`을 `replacement`로 모두 바꾸기

== 매크로 및 레지스터 (Macros and Registers)

- `qa`: `a` 레지스터에 매크로 기록 시작
- `q`: 매크로 기록 중지
- `@a`: `a` 레지스터에 저장된 매크로 실행
- `"`: 특정 레지스터 접근
- `"ay`: `a` 레지스터에 복사 (yank)

== 분할 및 탭 (Splits and Tabs)

- `:sp`: 현재 창을 수평으로 분할
- `:vsp`: 현재 창을 수직으로 분할
- `:tabe`: 새 탭 생성
- `:tabc`: 현재 탭 닫기
- `:tabn`: 다음 탭으로 이동
- `:tabp`: 이전 탭으로 이동

= 유용한 팁

== 들여쓰기
- `>>`: 현재 줄을 오른쪽으로 들여쓰기
- `<<`: 현재 줄을 왼쪽으로 들여쓰기
- `=`: 자동 들여쓰기 (현재 줄 또는 선택된 영역)
    - `gg=G`: 파일 전체 자동 들여쓰기

== 복사 및 붙여넣기
- `yy`: 현재 줄 복사 (yank)
- `dd`: 현재 줄 잘라내기 (cut)

== 주석 처리
- `gcc`: 현재 줄 주석 처리 토글
- `gc`: 선택 영역 주석 처리 토글

= 실무 단축키 및 팁
- `ciw`, `diw`: 현재 단어(inner word)를 변경/삭제. `caw`, `daw`는 공백 포함(a word).
- `ci(`, `di(`: 괄호 안의(inner) 내용을 변경/삭제. `ca(`, `da(`는 괄호 포함.
- `cit`, `dit`: 태그 안의(inner) 내용을 변경/삭제. `cat`, `dat`는 태그 포함.
- `:! <command>`: 셸 명령어 실행.
- `:r !<command>`: 셸 명령어 실행 결과를 현재 커서 위치에 삽입.
- ``f<char>``: 현재 줄에서 ``<char>``를 찾아 앞으로 이동. `;`와 `,`로 반복.
- `Ctrl-a`, `Ctrl-x`: 숫자 증가/감소.

== LSP (Language Server Protocol) 연동
Neovim은 내장 LSP 클라이언트를 통해 강력한 코드 인텔리전스 기능을 제공합니다. (LSP 플러그인 설정 필요)
- `gd`: 정의(definition)로 이동.
- `gr`: 참조(references) 목록 보기.
- `K`: 커서 위치의 심볼 정보 보기 (hover).
- `[d`, `]d`: 이전/다음 진단(diagnostic)으로 이동.
- ``<leader>ca``: 코드 액션(code action) 실행. (예: 빠른 수정, 리팩토링)
- ``<leader>rn``: 이름 변경(rename).

== Fuzzy Finder (Telescope, fzf 등)
- 파일, 버퍼, 코드 심볼 등을 빠르게 검색하고 이동하기 위해 `Telescope`나 `fzf.vim` 같은 플러그인 사용을 권장합니다.
- 예시 (Telescope):
  - ``<leader>ff`` : 파일 검색.
  - ``<leader>fg`` : 라이브그렙(live grep).
  - ``<leader>fb`` : 버퍼 검색.
