#import "./templates/conf.typ": *

#show: template.with(
  title: "ggplot2 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 기본 구조

```R
library(ggplot2)
# 데이터 + 매핑(aes) + 기하 객체(geom)
ggplot(data = mtcars, aes(x = hp, y = mpg)) +
  geom_point() # 산점도 생성
```

= 2. 주요 기하 객체 (Geoms)

- `geom_point()`: 산점도 (데이터 점 표시)
- `geom_line()`: 라인 플롯 (시계열 등)
- `geom_bar()`: 막대 그래프 (범주형 빈도)
- `geom_histogram()`: 히스토그램 (연속형 분포)
- `geom_boxplot()`: 박스 플롯 (사분위수 분포)
- `geom_smooth()`: 매끄러운 곡선 (추세선)

= 3. 축, 레이블 및 범위

- `labs()`: 제목, 축 이름, 캡션 등 설정
- `xlim()`, `ylim()`: 축 범위 지정
- `scale_x_continuous()`: X축 세부 설정 (간격, 레이블 등)

= 4. 테마 및 색상

- `theme_minimal()`, `theme_bw()`: 사전 정의된 테마 적용
- `scale_color_brewer()`: 색상 팔레트 변경 (Discrete)
- `scale_fill_gradient()`: 연속형 색상 그라데이션 설정

= 5. 패싯 (Faceting)

데이터 분할 시각화
- `facet_wrap(~ var)`: 한 변수 기준으로 분할
- `facet_grid(row ~ col)`: 두 변수 교차 분할

= 6. 플롯 저장

```R
p <- ggplot(mtcars, aes(hp, mpg)) + geom_point()
ggsave("plot.png", plot = p, width = 6, height = 4, dpi = 300)
```

