#import "./templates/conf.typ": *

#show: template.with(
  title: "C 언어 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 기본 구조 및 컴파일

```c
#include <stdio.h>
int main() {
    printf("Hello, C!\n");
    return 0;
}
```
- 컴파일: `gcc -o hello hello.c`
- 실행: `./hello`

= 2. 변수와 자료형

- 기본형: `int`, `float`, `double`, `char`, `void`
- 한정자: `short`, `long`, `signed`, `unsigned`
- 상수: `const`, `#define`
- 배열: `int arr[10];`
- 문자열: `char str[] = "Hi";` (널 종료 문자 배열)

= 3. 연산자

- 산술: `+`, `-`, `*`, `/`, `%`, `++`, `--`
- 관계: `==`, `!=`, `>`, `<`, `>=`, `<=`
- 논리: `&&` (AND), `||` (OR), `!` (NOT)
- 비트: `&`, `|`, `^`, `~`, `<<`, `>>`
- 할당: `=`, `+=`, `-=`, `*=`, `/=`
- 기타: `sizeof`, `&` (주소), `*` (참조), `?:`

= 4. 제어 흐름

- 조건문: `if-else`, `switch`
- 루프: `for`, `while`, `do-while`
- 제어: `break`, `continue`, `return`

= 5. 함수

- 정의: `ret_type func(params) { ... }`
- 프로토타입: `ret_type func(params);`

= 6. 포인터 (Pointer)

메모리 주소 저장 변수
- 주소 연산자 (`&`): 변수 주소 획득
- 역참조 연산자 (`*`): 주소의 값 접근

= 7. 구조체 (Structs)

사용자 정의 복합 자료형
```c
struct Person {
    char name[20];
    int age;
};
typedef struct Person Person;
```

= 8. 전처리기

- `#include`: 헤더 포함
- `#define`: 매크로 정의
- `#if`, `#ifdef`, `#endif`: 조건부 컴파일

= 9. 동적 메모리 (`stdlib.h`)

- `malloc`: 메모리 할당
- `calloc`: 0 초기화 할당
- `realloc`: 크기 재조정
- `free`: 메모리 해제

= 10. 파일 입출력

- `fopen`, `fclose`: 파일 열기/닫기
- `fprintf`, `fscanf`: 형식화 입출력
- `fgets`, `fputs`: 문자열 입출력