#import "./templates/conf.typ": *

#show: template.with(
  title: "NixOS 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 기본 개념
선언적(declarative) 구성 모델 기반 Linux 배포판. 전체 구성을 `/etc/nixos/configuration.nix`에 정의. 재현 가능하고 신뢰할 수 있는 시스템 구축. Nix 패키지 관리자 기반.

= 시스템 관리
- `nixos-rebuild switch`: 변경사항 적용 및 시스템 업데이트.
- `nixos-rebuild boot`: 시스템 업데이트 후 다음 부팅 시 적용.
- `nixos-rebuild test`: 시스템 테스트 빌드(미적용).
- `nixos-rebuild switch --upgrade`: 채널 최신화 후 시스템 업데이트.
- `nixos-rebuild --rollback`: 이전 세대 시스템 구성 롤백.
- `nix-channel --list`: 구독 중인 채널 목록 표시.
- `nix-channel --update`: 모든 채널 최신 버전 업데이트.

= 패키지 관리 (Nix-Env)
- `nix-env -iA nixos.<package_name>`: 패키지 설치 (예: `nix-env -iA nixos.firefox`).
- `nix-env -e <package_name>`: 패키지 제거.
- `nix-env -q`: 설치 패키지 목록 나열.
- `nix-env --upgrade`: 설치 패키지 업그레이드.
- 참고: 영구적 시스템 구성을 위해 `configuration.nix` 내 `environment.systemPackages`에 패키지 추가 권장. `nix-env`는 주로 임시 프로필 관리에 사용.

= Nix 셸 (임시 환경)
- `nix-shell -p <package1> <package2>`: 특정 패키지 포함 임시 셸 시작. 종료 시 원래 상태 복구.
- `nix-shell`: 현재 디렉토리 `shell.nix` 또는 `default.nix` 기반 개발 환경 로드.
- `nix-shell --pure`: 호스트 환경 격리 순수 셸 시작.

= Nix Store 및 가비지 컬렉션
- 모든 패키지 `/nix/store` 내 고유 해시 경로 저장.
- `nix-store --query --requisites /run/current-system`: 현재 시스템 모든 종속성 나열.
- `nix-collect-garbage`: 미참조 패키지 삭제.
- `nix-collect-garbage -d`: 모든 세대 삭제 및 미사용 패키지 정리 (주의: 롤백 불가).

= `configuration.nix` 예시 조각
```nix
{ config, pkgs, ... }:

{
  imports =
    [ ./hardware-configuration.nix ];

  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";

  networking.hostName = "nixos";
  networking.useDHCP = false;
  networking.interfaces.enp0s3.useDHCP = true;

  # 시간대 설정
  time.timeZone = "Asia/Seoul";

  # 시스템 패키지
  environment.systemPackages = with pkgs; [
    vim
    wget
    git
    firefox
  ];

  # 사용자 계정
  users.users.jules = {
    isNormalUser = true;
    extraGroups = [ "wheel" ]; # sudo 권한
  };

  # 서비스 활성화
  services.openssh.enable = true;
}
```

= Nix 언어 기본
- let-in 블록: `let x = 1; y = 2; in x + y`
- 함수: `x: x + 1`
- 집합 (Attribute Set): `{ name = "value"; nested = { ... }; }`
- `with pkgs; [ git vim ]`는 `[ pkgs.git pkgs.vim ]`와 동일.
