#import "./templates/conf.typ": *

#show: template.with(
  title: "fzf (Fuzzy Finder) 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. fzf 개요

`fzf`는 범용적으로 사용할 수 있는 명령줄 퍼지 파인더(Fuzzy Finder)입니다. 표준 입력을 통해 전달된 목록을 대화형으로 필터링하고, 선택한 결과를 표준 출력으로 반환합니다. 파일 탐색, 히스토리 검색, Git 커밋 선택 등 다양한 워크플로우를 획기적으로 개선합니다.

= 2. 기본 사용법

명령어의 출력을 파이프(`|`)로 연결하여 `fzf`를 실행합니다.

- 파일 목록에서 검색: `find . -type f | fzf`
- 디렉토리 목록에서 검색: `find . -type d | fzf`
- 명령어 히스토리에서 검색: `history | fzf`

= 3. 강력한 셸 통합 단축키 (설치 권장)

`fzf` 설치 시 셸 통합 설정을 추가하면 다음의 유용한 단축키를 사용할 수 있습니다.

- `Ctrl + T`: 현재 경로의 파일/디렉토리를 검색하여 터미널 프롬프트에 즉시 입력합니다.
- `Ctrl + R`: 전체 명령어 히스토리를 퍼지 검색하여 선택한 명령을 불러옵니다.
- `Alt + C`: 하위 디렉토리를 검색하여 선택한 위치로 즉시 이동(`cd`)합니다.

= 4. 검색 구문 (Search Syntax)

- `text`: 퍼지 매칭 (입력한 문자가 포함된 모든 항목 검색)
- `'text`: 정확히 일치하는 단어 검색 (Exact-match)
- `^text`: 해당 텍스트로 시작하는 항목 검색
- `text$`: 해당 텍스트로 끝나는 항목 검색
- `!text`: 해당 텍스트를 포함하지 않는 항목 검색 (Inverse-match)
- `|`: 여러 검색어에 대한 OR 조건 검색 (예: `py | js`)

= 5. 주요 옵션 및 설정

- `--height <%>`: 터미널 화면 내에서 fzf 창이 차지할 높이를 지정합니다. (예: `--height 40%`)
- `--layout=reverse`: 검색창을 상단에 배치하고 목록을 아래로 출력합니다.
- `--multi`: `Tab` 키를 사용하여 여러 항목을 동시에 선택할 수 있게 합니다.
- `--preview '명령어'`: 선택한 항목에 대한 미리보기 창을 보여줍니다. `{}`는 선택된 항목으로 치환됩니다.
- `--bind '키:동작'`: 특정 키에 사용자 정의 동작을 바인딩합니다.

= 6. 미리보기 창 활용 예시

`--preview` 옵션은 fzf의 활용도를 극대화하는 강력한 기능입니다.

- 파일 내용 미리보기:
  ```bash
  fzf --preview 'cat {}'
  ```
- `bat`을 사용한 구문 강조 미리보기:
  ```bash
  fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}'
  ```
- 디렉토리 구조 미리보기:
  ```bash
  find . -type d | fzf --preview 'tree -C {} | head -100'
  ```

= 7. 다른 도구와의 연동 실례

- **Git 협업**:
  - 브랜치 전환: `git branch | fzf | xargs git checkout`
  - 로그 상세 확인: `git log --oneline | fzf --preview 'git show {+1}'`
- **파일 검색 및 편집**:
  - `rg`(ripgrep) 검색 후 편집기로 열기: `rg --line-number . | fzf | cut -d: -f1,2 | xargs nvim`
- **프로세스 관리**:
  - 프로세스 선택 종료: `ps -ef | fzf --multi | awk '{print $2}' | xargs kill -9`

= 8. 환경 변수 설정

`~/.bashrc` 또는 `~/.zshrc` 파일에 환경 변수를 설정하여 `fzf`를 항상 원하는 스타일로 구동할 수 있습니다.

```bash
# fzf 기본 동작 명령어 설정
export FZF_DEFAULT_COMMAND='find . -type f'
# fzf 기본 테마 및 미리보기 옵션 설정
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --preview="bat --color=always {}"'
```
