#import "./templates/conf.typ": *

#show: template.with(
  title: "fzf (Fuzzy Finder) 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. fzf란?

`fzf`는 범용 커맨드라인 퍼지 파인더(fuzzy finder)입니다. 표준 입력으로 들어온 목록을 대화형으로 필터링하여 선택된 항목을 표준 출력으로 내보냅니다. 파일, 명령어 히스토리, git 커밋 등 다양한 목록을 빠르게 검색하고 선택하는 데 사용됩니다.

= 2. 기본 사용법

다른 명령어의 출력을 파이프로 `fzf`에 연결하여 사용합니다.

- 파일 목록에서 선택: `find . -type f | fzf`
- 디렉토리 목록에서 선택: `find . -type d | fzf`
- 명령어 히스토리에서 선택: `history | fzf`

= 3. 셸 통합 (설치 시 추가)

`fzf`를 설치할 때 셸 통합을 설정하면 매우 강력한 단축키를 사용할 수 있습니다.

- `Ctrl+T`: 현재 디렉토리 하위의 파일 및 디렉토리 목록을 퍼지 검색하여 선택한 경로를 프롬프트에 입력합니다.
- `Ctrl+R`: 명령어 히스토리를 퍼지 검색하여 선택한 명령어를 프롬프트에 입력합니다.
- `Alt+C`: 현재 디렉토리 하위의 디렉토리 목록을 퍼지 검색하여 선택한 디렉토리로 즉시 이동합니다.

= 4. 검색 구문

- `text`: `text`를 포함하는 항목을 검색합니다.
- `'text`: `text`와 정확히 일치하는 항목을 검색합니다.
- `^text`: `text`로 시작하는 항목을 검색합니다.
- `text$`: `text`로 끝나는 항목을 검색합니다.
- `!text`: `text`를 포함하지 않는 항목을 검색합니다.
- `!^text`: `text`로 시작하지 않는 항목을 검색합니다.
- `!text$`: `text`로 끝나지 않는 항목을 검색합니다.
- `|`: 여러 검색어를 OR 조건으로 묶습니다. (예: `py | js`)

= 5. 주요 옵션

- `--height <PERCENT>`: fzf 창의 높이를 터미널 높이의 백분율로 지정합니다. (예: `--height 40%`)
- `--layout <LAYOUT>`: 레이아웃을 지정합니다. (`default`, `reverse`, `reverse-list`)
- `--multi`: 여러 항목을 선택할 수 있게 합니다 (Tab 키로 선택).
- `--preview <COMMAND>`: 선택한 항목에 대한 미리보기 창을 표시합니다. `{}`는 선택된 항목으로 치환됩니다.
- `--bind <KEY:ACTION>`: 특정 키에 동작을 바인딩합니다.
- `--prompt <STRING>`: 프롬프트 문자열을 변경합니다.

= 6. 미리보기 창 활용

`--preview` 옵션은 `fzf`의 가장 강력한 기능 중 하나입니다.

- 파일 내용 미리보기:
  ```bash
  fzf --preview 'cat {}'
  ```
- `bat` (cat의 향상된 버전)으로 구문 강조 미리보기:
  ```bash
  fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}'
  ```
- `ls -l`로 파일 정보 미리보기:
  ```bash
  fzf --preview 'ls -l {}'
  ```
- `tree`로 디렉토리 구조 미리보기:
  ```bash
  find . -type d | fzf --preview 'tree -C {} | head -200'
  ```

= 7. 다른 도구와 함께 사용하기

- `git`과 함께 사용하기:
  - git 브랜치 전환: `git branch | fzf | xargs git checkout`
  - git 로그 보기: `git log --oneline | fzf --preview 'git show {+1}'`
- `rg` (ripgrep)과 함께 사용하기:
  - 파일 내용 검색 후 에디터로 열기: `rg --line-number . | fzf | cut -d: -f1,2 | xargs nvim`
- 프로세스 종료 (`kill`):
  - `ps -ef | fzf --multi | awk '{print $2}' | xargs kill -9`

= 8. 환경 변수

`~/.bashrc` 또는 `~/.zshrc`에 환경 변수를 설정하여 기본 옵션을 지정할 수 있습니다.

```bash
export FZF_DEFAULT_COMMAND='find . -type f'
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --preview="bat --color=always {}"'
```
- `FZF_DEFAULT_COMMAND`: `fzf`가 단독으로 실행될 때 입력으로 사용할 기본 명령어.
- `FZF_DEFAULT_OPTS`: `fzf` 실행 시 항상 적용할 기본 옵션.
