#import "./templates/conf.typ": *

#show: template.with(
  title: "JavaScript 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 변수, 타입, 연산자

- 변수 선언:
  - `const`: 블록 스코프. 재할당 불가 (상수)
  - `let`: 블록 스코프. 재할당 가능
  - `var`: 함수 스코프. 호이스팅 발생 (사용 권장 안 함)
- 데이터 타입:
  - 원시 타입: `String`, `Number`, `Boolean`, `null`, `undefined`, `Symbol`, `BigInt`
  - 객체 타입: `Object` (`Array`, `Function`, `Date` 등 포함)
- 주요 연산자:
  - 일치 비교: `===` (값과 타입 모두 비교, 권장), `==` (값만 비교)
  - 논리 연산: `&&`, `||`, `!`
  - Null 병합: `a ?? b` (a가 null/undefined일 때 b 반환)
  - 옵셔널 체이닝: `obj?.prop` (Null 참조 방지)

= 2. 제어 흐름

- 조건문: `if...else`, `switch`
- 루프: `for`, `while`, `do...while`
- `for...in`: 객체의 프로퍼티 순회
- `for...of`: 배열 등 이터러블 객체의 요소 순회

= 3. 함수

- 함수 정의:
  - 선언식: `function name() { ... }` (호이스팅 발생)
  - 표현식: `const name = function() { ... }`
  - 화살표 함수: `const name = () => { ... }` (`this` 바인딩 안 함)
- 인자 제어:
  - 기본값 인자: `function(name = "Guest")`
  - 나머지 인자 (Rest): `function(...args)` (배열로 수신)
- 전개 구문 (Spread): `...` (배열/객체 복사 및 병합)

= 4. 객체와 클래스

- 객체 리터럴: `const obj = { key: value }`
- 클래스 (ES6+):
  ```javascript
  class Person {
    constructor(name) { this.name = name; }
    greet() { console.log(`Hi, ${this.name}`); }
  }
  ```
- 프로토타입: JavaScript 객체의 상속 메커니즘

= 5. 주요 배열 메서드

- 요소 관리: `push`, `pop`, `shift`, `unshift`, `splice`, `slice`
- 고차 함수:
  - `forEach`: 각 요소에 작업 수행
  - `map`: 변형된 요소로 구성된 새 배열 생성
  - `filter`: 조건 일치 요소만 골라 새 배열 생성
  - `reduce`: 요소들을 하나로 축소 계산
  - `find`/`findIndex`: 조건 일치 요소/인덱스 탐색
  - `some`/`every`: 일부/전체 조건 일치 여부 확인

= 6. 비동기 처리

- Promise: 비동기 상태 객체 (`pending`, `fulfilled`, `rejected`)
  - `.then()`, `.catch()`, `.finally()` 체이닝
- async/await: Promise 기반 비동기 코드를 동기식으로 작성
  ```javascript
  async function fetch() {
    try {
      const res = await fetch(url);
      const data = await res.json();
      return data;
    } catch (err) { console.error(err); }
  }
  ```

= 7. 모듈 시스템 (ESM)

- `export`: `export const n = 1;`, `export default fn;`
- `import`: `import { n } from './m.js';`, `import fn from './m.js';`

= 8. 구조 분해 할당

- 배열: `const [a, b] = [1, 2]`
- 객체: `const { name, age } = person`
- 별칭 지정: `const { name: nick } = person`

= 9. `this` 바인딩

- 호출 방식에 따라 결정: 일반 함수(전역/undefined), 메서드(객체), 생성자(인스턴스)
- 명시적 바인딩: `.call()`, `.apply()`, `.bind()`
- 화살표 함수: 상위 스코프의 `this` 계승

= 10. 최신 기능 (ES6+)

- 템플릿 리터럴: `` `String ${expr}` ``
- Proxy/Reflect: 객체 동작 가로채기 및 메타 프로그래밍
- 제너레이터: `function*` 및 `yield` 기반 이터레이터
- 가비지 컬렉션 도움: `WeakMap`, `WeakSet` (약한 참조)
- 배열 평탄화: `flat`, `flatMap`
- 성능 최적화: 디바운싱, 스로틀링 패턴 권장

