#import "./templates/conf.typ": *

#show: template.with(
  title: "mise 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 기본 개념
언어 및 도구 버전을 프로젝트별로 관리하는 CLI 도구. `.tool-versions` 파일로 도구 및 버전 선언적 관리.

= 기본 명령어
- `mise install` 또는 `mise i`: 명시된 모든 도구 버전 설치.
- `mise use <tool>@<version>`: 특정 도구 버전을 전역/로컬 `.tool-versions`에 추가 및 활성화.
- `mise current`: 현재 디렉토리 활성화 도구 및 버전 표시.
- `mise ls`: 설치 도구 및 버전 목록 표시.
- `mise exec -- <command>`: 명시된 도구 환경에서 명령어 실행 (예: `mise exec -- npm test`).
- `mise reshim`: shim 재구성 (플러그인 설치/제거 후 필요).

= 플러그인 관리
- `mise plugins ls`: 설치 플러그인 목록 표시.
- `mise plugins add <name>`: 새 플러그인 추가 (예: `mise plugins add nodejs`).
- `mise plugins add <name> <git-url>`: Git URL로 플러그인 추가.
- `mise plugins rm <name>`: 플러그인 제거.
- `mise plugins update <name>`: 특정 플러그인 업데이트 (전체 업데이트: `mise plugins update --all`).

= 버전 관리
- `mise ls-remote <tool>`: 설치 가능 버전 목록 표시.
- `mise install <tool>@<version>`: 특정 버전 도구 설치.
- `mise uninstall <tool>@<version>`: 특정 버전 도구 제거.
- `mise global <tool>@<version>`: 전역 버전 설정(`~/.tool-versions`).
- `mise local <tool>@<version>`: 로컬(현재 디렉토리) 버전 설정. `.tool-versions` 파일 생성/수정.

= `.tool-versions` 파일 예시
프로젝트 루트 디렉토리 위치 시 자동 버전 활성화.
```
# .tool-versions
nodejs 20.11.0
python 3.11.7
rust 1.76.0
```

= 셸 통합
셸 설정 파일(`.bashrc`, `.zshrc` 등)에 활성화 스크립트 추가 필요.
```bash
# .zshrc 예시
eval "$(mise activate zsh)"
```
디렉토리 변경 시 `.tool-versions` 자동 감지 및 shim을 `PATH`에 추가.

= `asdf-vm`과의 관계
`asdf-vm`과 유사 기능 제공 및 플러그인 호환. Rust 기반 고성능 제공. 환경 변수 관리 및 작업 실행 기능 추가.
