#import "./templates/conf.typ": *

#show: template.with(
  title: "머신러닝 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 머신러닝 종류
- 지도 학습 (Supervised Learning): 입력(X)과 정답(Y) 데이터 쌍 학습, 새로운 입력 정답 예측
  - `회귀 (Regression)`: 연속 값 예측 (예: 집값 예측)
  - `분류 (Classification)`: 이산 범주 예측 (예: 스팸 메일 분류)
- 비지도 학습 (Unsupervised Learning): 정답 없는 데이터 학습, 데이터 숨겨진 구조나 패턴 발견
  - `군집화 (Clustering)`: 유사 데이터 그룹화
  - `차원 축소 (Dimensionality Reduction)`: 데이터 특징(feature) 수 축소
- 강화 학습 (Reinforcement Learning): 에이전트(agent)와 환경(environment) 상호작용, 보상(reward) 최대화 행동(action) 학습

= 지도 학습 알고리즘
- 선형 회귀 (Linear Regression): 데이터 적합 직선 탐색, 회귀 모델 생성
- 로지스틱 회귀 (Logistic Regression): 시그모이드 함수 사용, 클래스 소속 확률 예측 분류 모델
- 서포트 벡터 머신 (SVM, Support Vector Machine): 클래스 간 경계(margin) 최대화 결정 경계(decision boundary) 탐색 분류/회귀 알고리즘
- 결정 트리 (Decision Tree): 질문 기반 데이터 분할 예측 나무 구조 모델. 해석 용이
- K-최근접 이웃 (K-Nearest Neighbors, KNN): 주변 K개 이웃 다수결 클래스 예측
- 나이브 베이즈 (Naive Bayes): 베이즈 정리 기반 분류 알고리즘. 특징 독립 가정

= 비지도 학습 알고리즘
- K-평균 군집 (K-Means Clustering): 데이터 K개 군집(cluster)화. 가장 가까운 군집 중심(centroid) 할당
- 주성분 분석 (PCA, Principal Component Analysis): 데이터 분산 최대 설명 축 탐색, 데이터 차원 축소
- 계층적 군집 분석 (Hierarchical Clustering): 개별 데이터 기반 클러스터 병합(agglomerative) 또는 분할(divisive) 방식 군집 형성

= 앙상블 학습 (Ensemble Learning)
약한 학습기(weak learner) 결합, 강력한 모델 생성 기법
- 배깅 (Bagging, Bootstrap Aggregating): 부트스트랩 샘플링(중복 허용 샘플링) 기반 여러 모델 학습, 결과 평균 또는 다수결 합산
  - `랜덤 포레스트 (Random Forest)`: 배깅 적용 결정 트리 앙상블. 무작위 특징 선택으로 다양성 증대
- 부스팅 (Boosting): 오예측 데이터 가중치 부여, 순차적 모델 개선
  - `AdaBoost`, `Gradient Boosting Machine (GBM)`, `XGBoost`, `LightGBM`

= 모델 평가 지표
- 회귀 (Regression):
  - `MAE (Mean Absolute Error)`: 오차 절댓값 평균
  - `MSE (Mean Squared Error)`: 오차 제곱 평균
  - `R² (결정 계수)`: 데이터 분산 설명력 지표. 1에 가까울수록 우수
- 분류 (Classification): (혼동 행렬 기반)
  - `정확도 (Accuracy)`: 올바른 예측 비율
  - `정밀도 (Precision)`: Positive 예측 중 실제 Positive 비율
  - `재현율 (Recall)`: 실제 Positive 중 Positive 예측 비율
  - `F1 점수 (F1 Score)`: 정밀도와 재현율 조화 평균
  - `AUC (Area Under the ROC Curve)`: ROC 곡선 아래 면적. 1에 가까울수록 우수

= 과적합 방지 (Regularization)
- L1 Regularization (Lasso): 가중치 절댓값 합 비용 함수 추가. 특징 선택 효과
- L2 Regularization (Ridge): 가중치 제곱 합 비용 함수 추가. 모델 평활화
- 드롭아웃 (Dropout): (딥러닝) 학습 시 신경망 일부 뉴런 무작위 비활성화
- 조기 종료 (Early Stopping): 검증 데이터셋 성능 미향상 시 학습 중단
