#import "./templates/conf.typ": *

#show: template.with(
  title: "Docker 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 핵심 개념

- Docker: 컨테이너 기반 가상화 플랫폼
- 이미지 (Image): 컨테이너 실행용 읽기 전용 템플릿
- 컨테이너 (Container): 이미지의 실행 가능한 인스턴스
- Dockerfile: 이미지 빌드용 스크립트
- 볼륨 (Volume): 데이터 영구 저장 메커니즘
- 네트워크 (Network): 컨테이너 간 통신 설정

= 2. 컨테이너 관리

== 실행 및 제어
- `docker run [opts] IMAGE`: 컨테이너 생성 및 실행
  - `-d`: 백그라운드 실행
  - `-p host:container`: 포트 포워딩
  - `-v host:container`: 볼륨 마운트
  - `--name [name]`: 이름 지정
  - `-e KEY=VAL`: 환경 변수 설정
  - `--rm`: 종료 시 자동 삭제
  - `-it`: 터미널 상호작용 활성화
- `docker stop/start [id]`: 중지/시작
- `docker restart [id]`: 재시작
- `docker kill [id]`: 강제 종료
- `docker rm [id]`: 컨테이너 삭제 (`-f` 강제)

== 조회 및 정보
- `docker ps`: 실행 중인 목록 (`-a` 전체)
- `docker logs -f [id]`: 실시간 로그 확인
- `docker inspect [id]`: 상세 정보 조회 (JSON)
- `docker stats`: 리소스 사용량 실시간 모니터링
- `docker exec -it [id] [cmd]`: 실행 중인 컨테이너에 명령 전달

= 3. 이미지 관리

- `docker images`: 로컬 이미지 목록
- `docker build -t name:tag [path]`: 이미지 빌드
- `docker pull/push [name]`: 이미지 다운로드/업로드
- `docker rmi [id]`: 이미지 삭제
- `docker image prune`: 사용되지 않는 이미지 정리
- `docker tag [src] [target]`: 태그 추가

= 4. 네트워크 및 볼륨

- `docker network ls/create/rm`: 네트워크 관리
- `docker network connect [net] [cont]`: 컨테이너 연결
- `docker volume ls/create/rm`: 볼륨 관리
- `docker volume prune`: 안 쓰는 볼륨 일괄 삭제

= 5. Docker Compose

- `docker-compose up -d`: 백그라운드 서비스 시작
- `docker-compose down`: 중지 및 관련 자원 삭제
- `docker-compose ps`: 서비스 상태 확인
- `docker-compose logs -f`: 서비스 로그 확인
- `docker-compose exec [svc] [cmd]`: 서비스 컨테이너 명령 실행

= 6. Dockerfile 명령어

- `FROM`: 베이스 이미지 지정
- `RUN`: 빌드 시 명령어 실행
- `CMD`: 컨테이너 시작 시 기본 명령
- `ENTRYPOINT`: 고정된 실행 파일 지정
- `COPY/ADD`: 파일 복사 (ADD는 URL/압축해제 지원)
- `WORKDIR`: 작업 디렉토리 설정
- `ENV`: 환경 변수 설정
- `EXPOSE`: 노출 포트 선언
- `VOLUME`: 마운트 포인트 생성

= 7. 시스템 관리

- `docker system df`: 디스크 사용량 확인
- `docker system prune -a`: 미사용 자원 전체 정리
- `docker version/info`: 버전 및 시스템 정보

