#import "./templates/conf.typ": *

#show: template.with(
  title: "macOS 치트시트 ",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 파일 및 디렉토리 관리

- `ls`: 디렉토리 내용 나열
  - `-l`: 긴 형식(권한, 소유자, 크기, 날짜 등) 표시
  - `-a`: 점(`.`)으로 시작하는 숨김 파일 포함 모든 파일 표시
  - `-h`: 읽기 쉬운 형식(KB, MB, GB) 크기 표시
  - `-t`: 수정 시간 기준 정렬
  - `-R`: 하위 디렉토리 내용 재귀적 나열
- `cd`: 디렉토리 변경 (`~` 홈, `-` 이전 디렉토리)
- `pwd`: 현재 작업 디렉토리 전체 경로 출력
- `mkdir -p <path>`: 중간 경로 디렉토리 미존재 시 함께 생성
- `rm`: 파일 또는 디렉토리 삭제
  - `-r`: 디렉토리 및 내부 내용 재귀적 삭제
  - `-f`: 확인 없이 강제 삭제
- `cp`: 파일이나 디렉토리 복사
  - `-r` 또는 `-R`: 디렉토리 재귀적 복사
- `mv`: 파일이나 디렉토리 이동 또는 이름 변경
- `touch <filename>`: 빈 파일 생성 또는 타임스탬프 업데이트
- `find <path> -name "<pattern>"`: 경로 내 이름 패턴 기준 파일 검색
- `grep -r "<pattern>" <path>`: 경로 내 파일 내용 패턴 재귀적 검색
- `chmod`: 파일 권한 변경 (예: `chmod 755 script.sh`)
- `chown`: 파일 소유자 변경 (예: `chown user:group file.txt`)
- `ln -s <target> <link_name>`: 심볼릭 링크 생성
- `du -sh <path>`: 경로별 총 디스크 사용량 요약 표시
- `df -h`: 마운트된 볼륨 디스크 공간 사용량 표시

= 2. 시스템 정보 및 프로세스 관리

- `top`: 실행 중 프로세스 및 리소스 사용량 실시간 표시
- `ps aux`: 모든 사용자 실행 프로세스 상세 표시
- `kill <PID>`: 특정 프로세스 ID(PID) 종료
  - `kill -9 <PID>`: 프로세스 강제 종료
- `pgrep <process_name>`: 프로세스 이름 기준 PID 검색
- `pkill <process_name>`: 프로세스 이름 기준 종료
- `sysctl -n hw.ncpu`: CPU 코어 수 확인
- `system_profiler <dataType>`: 데이터 타입별 시스템 프로필 정보 상세 표시 (예: `SPHardwareDataType`)
- `scutil --get HostName`: 호스트 이름 확인
- `lsof -i :<port>`: 특정 포트 사용 프로세스 확인
- `caffeinate`: 시스템 잠자기 방지
  - `caffeinate -d`: 디스플레이 잠자기 방지
  - `caffeinate -t 3600`: 지정 시간(초) 동안 활성 상태 유지

= 3. 네트워크 관리

- `ifconfig`: 네트워크 인터페이스 구성 표시 및 설정
- `ipconfig getifaddr en0`: 특정 인터페이스(en0) IP 주소 획득
- `ping <host>`: 호스트 네트워크 연결 테스트
- `netstat -an`: 네트워크 연결 및 대기 포트 숫자 형식 표시
- `dscacheutil -flushcache`: DNS 캐시 초기화
- `mDNS -R`: Multicast DNS Responder 캐시 초기화
- `arp -a`: ARP 테이블(IP 주소-MAC 주소 매핑) 표시
- `ssh <user>@<host>`: 원격 호스트 SSH 안전 연결
- `scp <source> <destination>`: 원격 호스트 간 파일 안전 복사

= 4. macOS 특정 명령어

- `open`: 파일, 디렉토리, URL 기본 앱 열기
  - `open .`: 현재 디렉토리 Finder 열기
  - `open -a <Application> <file>`: 특정 앱으로 파일 열기
- `mdfind "<query>"`: 터미널 기반 Spotlight 검색
- `mdls <filename>`: 파일 메타데이터(Spotlight 정보) 표시
- `defaults`: macOS 사용자 기본 설정 읽기, 쓰기, 삭제
  - `defaults read com.apple.finder AppleShowAllFiles`: 숨김 파일 표시 여부 확인
  - `defaults write com.apple.finder AppleShowAllFiles -bool true`: 숨김 파일 표시 활성화
- `softwareupdate`: 시스템 소프트웨어 및 앱 명령줄 업데이트
  - `-l`: 사용 가능한 업데이트 나열
  - `-i -a`: 모든 업데이트 설치
- `diskutil`: 디스크 및 볼륨 관리
  - `diskutil list`: 모든 디스크 및 파티션 나열
  - `diskutil verifyVolume /`: 주 볼륨 무결성 검사
  - `diskutil repairPermissions /`: 주 볼륨 권한 복구 (구 버전)
- `tmutil`: Time Machine 제어
  - `tmutil status`: 백업 상태 표시
  - `tmutil startbackup`: 백업 시작
- `pbcopy`: 표준 입력 클립보드 복사 (예: `cat file.txt | pbcopy`)
- `pbpaste`: 클립보드 내용 표준 출력 붙여넣기
- `say`: 텍스트 음성 변환 출력

= 5. Homebrew (패키지 관리자)

- `brew install <formula>`: 커맨드라인 유틸리티(formula) 설치
- `brew install --cask <cask>`: GUI 애플리케이션(cask) 설치
- `brew uninstall <formula|cask>`: 패키지 제거
- `brew update`: Homebrew 및 패키지 목록 업데이트
- `brew upgrade`: 설치된 모든 패키지 업그레이드
- `brew list`: 설치된 패키지 목록 표시
- `brew search <text>`: 패키지 검색
- `brew info <formula>`: 패키지 정보 표시
- `brew doctor`: Homebrew 설치 상태 진단
- `brew cleanup`: 구버전 패키지 삭제, 공간 확보
