#import "./templates/conf.typ": *

#show: template.with(
  title: "C++ 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 기본 구조 및 컴파일

C++ 프로그램은 일반적으로 `#include` 지시문, `main` 함수, 그리고 다양한 구문으로 구성됩니다.

```cpp
#include <iostream> // 입출력 스트림 라이브러리

// 프로그램의 시작점
int main() {
    std::cout << "Hello, World!" << std::endl;
    return 0;
}
```
- 컴파일 및 실행:
  ```bash
  g++ -o hello hello.cpp
  ./hello
  ```

= 2. 변수, 타입, 연산자

- 기본 타입: `int`, `double`, `char`, `bool`, `float`.
- `std::string`: 문자열 타입.
- `const`: 상수 변수를 선언. `const double PI = 3.14;`
- `auto`: 컴파일러가 타입을 자동으로 추론. `auto x = 5;`
- 연산자: 산술(`+`, `-`, `*`, `/`, `%`), 관계(`==`, `!=`, `<`, `>`), 논리(`&&`, `||`, `!`).

= 3. 제어 흐름

- `if-else`:
  ```cpp
  if (condition) {
      // ...
  } else if (condition) {
      // ...
  } else {
      // ...
  }
  ```
- `switch`:
  ```cpp
  switch (variable) {
      case 1:
          // ...
          break;
      case 2:
          // ...
          break;
      default:
          // ...
  }
  ```
- `for` 루프:
  ```cpp
  for (int i = 0; i < 5; ++i) {
      // ...
  }
  ```
- 범위 기반 `for` 루프 (Range-based for):
  ```cpp
  std::vector<int> v = {1, 2, 3};
  for (int item : v) {
      std::cout << item << std::endl;
  }
  ```
- `while` 루프: `while (condition) { ... }`

= 4. 함수

- 함수 정의:
  ```cpp
  return_type function_name(param_type param_name) {
      // 함수 본문
      return value;
  }
  ```
- 함수 오버로딩: 동일한 이름이지만 매개변수 타입이나 개수가 다른 여러 함수를 정의할 수 있습니다.
- 기본 매개변수: `void print(int value, int base=10);`

= 5. 포인터와 참조

- 포인터 (`*`): 변수의 메모리 주소를 저장.
  ```cpp
  int var = 10;
  int* ptr = &var; // var의 주소를 ptr에 저장
  std::cout << *ptr; // ptr이 가리키는 값(10)을 출력
  ```
- 참조 (`&`): 변수의 별칭. 선언 시 반드시 초기화해야 함.
  ```cpp
  int var = 10;
  int& ref = var; // ref는 var의 또 다른 이름
  ref = 20; // var도 20으로 변경됨
  ```

= 6. 클래스와 객체

- 클래스 정의:
  ```cpp
  class MyClass {
  public: // 접근 지정자
      // 생성자
      MyClass(int val) : my_field(val) {}

      // 멤버 함수 (메서드)
      void myMethod() {
          std::cout << "Field is " << my_field << std::endl;
      }

  private:
      // 멤버 변수 (필드)
      int my_field;
  };
  ```
- 객체 생성: `MyClass obj(10);`
- 멤버 접근: `obj.myMethod();`
- 상속: `class Derived : public Base { ... };`

= 7. 표준 템플릿 라이브러리 (STL)

== `std::vector`
동적 배열.
```cpp
#include <vector>
std::vector<int> vec;
vec.push_back(10); // 요소 추가
vec.push_back(20);
int first = vec[0]; // 요소 접근
vec.size(); // 크기
```

== `std::map`
키-값 쌍을 저장하는 연관 컨테이너.
```cpp
#include <map>
std::map<std::string, int> ages;
ages["Alice"] = 30;
ages["Bob"] = 25;
```

== `std::string`
문자열을 다루는 클래스.
```cpp
#include <string>
std::string s = "Hello";
s += ", World!";
s.substr(0, 5); // "Hello"
s.find("World"); // 7
```

== 알고리즘
`#include <algorithm>` 헤더에 포함.
- `std::sort(vec.begin(), vec.end());`
- `std::find(vec.begin(), vec.end(), value_to_find);`
- `std::for_each(vec.begin(), vec.end(), my_function);`

= 8. 입출력

== 콘솔 입출력 (`iostream`)
```cpp
#include <iostream>
int x;
std::cout << "Enter a number: ";
std::cin >> x;
std::cerr << "This is an error message." << std::endl;
```

== 파일 입출력 (`fstream`)
```cpp
#include <fstream>
#include <string>

// 파일 쓰기
std::ofstream outFile("data.txt");
outFile << "Hello, file!" << std::endl;
outFile.close();

// 파일 읽기
std::ifstream inFile("data.txt");
std::string line;
while (std::getline(inFile, line)) {
    std::cout << line << std::endl;
}
inFile.close();
```
