#import "./templates/conf.typ": *


#show: template.with(
  title: "Seaborn 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

// 주요 내용 시작
= 데이터셋 로드

```python
import seaborn as sns

# 내장 데이터셋 로드
tips = sns.load_dataset("tips")
print(tips.head())
```

= 범주형 플롯

== 카운트 플롯 (Count Plot)

```python
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")
sns.countplot(x="day", data=tips)
plt.title("요일별 팁 카운트")
plt.show()
```

== 바 플롯 (Bar Plot)

```python
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")
sns.barplot(x="sex", y="total_bill", data=tips)
plt.title("성별 총 계산서 평균")
plt.show()
```

== 박스 플롯 (Box Plot)

```python
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")
sns.boxplot(x="day", y="total_bill", data=tips)
plt.title("요일별 총 계산서 박스 플롯")
plt.show()
```

== 바이올린 플롯 (Violin Plot)

```python
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")
sns.violinplot(x="day", y="total_bill", data=tips)
plt.title("요일별 총 계산서 바이올린 플롯")
plt.show()
```

= 관계형 플롯

== 산점도 (Scatter Plot - relplot)

```python
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")
sns.relplot(x="total_bill", y="tip", hue="smoker", data=tips)
plt.title("총 계산서와 팁의 관계 (흡연 여부)")
plt.show()
```

== 라인 플롯 (Line Plot - relplot)

```python
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = sns.load_dataset("fmri")
sns.relplot(x="timepoint", y="signal", kind="line", data=df)
plt.title("시간 경과에 따른 신호 변화")
plt.show()
```

= 분포 플롯

== 히스토그램 (Histogram - histplot)

```python
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")
sns.histplot(data=tips, x="total_bill", kde=True)
plt.title("총 계산서 분포")
plt.show()
```

== 커널 밀도 추정 (KDE Plot)

```python
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")
sns.kdeplot(data=tips, x="total_bill", y="tip", fill=True)
plt.title("총 계산서와 팁의 2D KDE")
plt.show()
```

= 매트릭스 플롯

== 히트맵 (Heatmap)

```python
import seaborn as sns
import matplotlib.pyplot as plt

flights = sns.load_dataset("flights")
flights_pivot = flights.pivot_table(index="month", columns="year", values="passengers")
sns.heatmap(flights_pivot, annot=True, fmt="d", cmap="YlGnBu")
plt.title("월별/연도별 승객 수 히트맵")
plt.show()
```

= 스타일 및 팔레트

```python
import seaborn as sns
import matplotlib.pyplot as plt

sns.set_style("whitegrid") # 스타일 설정
sns.set_palette("pastel") # 팔레트 설정

tips = sns.load_dataset("tips")
sns.barplot(x="sex", y="total_bill", data=tips)
plt.title("스타일 및 팔레트 적용")
plt.show()
```
