#import "./templates/conf.typ": *

#show: template.with(
  title: "HTML5 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 기본 문서 구조

```html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>제목</title>
    <link rel="stylesheet" href="style.css">
    <script src="script.js"></script>
</head>
<body>
    <!-- 콘텐츠 -->
</body>
</html>
```

= 2. 시맨틱 태그 (Semantic Tags)

- `<header>`: 머리말. 로고, 제목, 메뉴 등 포함
- `<nav>`: 주요 네비게이션 링크 모음
- `<main>`: 문서의 핵심 콘텐츠 (전체에서 단 하나)
- `<article>`: 독립적 콘텐츠 (뉴스, 블로그 등)
- `<section>`: 문서 구획 분할 (보통 제목 포함)
- `<aside>`: 보조 콘텐츠 (사이드바, 광고 등)
- `<footer>`: 꼬리말. 저작권, 연락처 정보 등
- `<figure>` / `<figcaption>`: 이미지와 설명문 결합

= 3. 텍스트 관련 태그

- `<h1>` ~ `<h6>`: 중요도 순 제목
- `<p>`: 문단 정의
- `<a>`: 하이퍼링크 (`href` 속성 사용)
- `<strong>`: 중요 텍스트 (굵게)
- `<em>`: 강조 텍스트 (기울임)
- `<blockquote>`: 긴 인용문 블록
- `<code>`: 짧은 코드 조각
- `<pre>`: 서식 유지 텍스트 (공백/줄바꿈 보존)
- `<br>`: 단순 줄바꿈
- `<hr>`: 수평 구분선

= 4. 목록 및 테이블

- `<ul>` / `<li>`: 순서 없는 목록
- `<ol>` / `<li>`: 순서 있는 목록
- `<dl>` / `<dt>` / `<dd>`: 용어 정의 목록
- `<table>`: 표 생성
- `<thead>`, `<tbody>`, `<tfoot>`: 표 구획 지정
- `<tr>`, `<th>`, `<td>`: 행, 헤더 셀, 데이터 셀

= 5. 폼 (Forms)

- `<form>`: 사용자 입력 양식 영역
- `<input>`: 다양한 입력 필드
  - `text`, `password`, `email`, `number`
  - `checkbox`, `radio`, `file`, `submit`
- `<label>`: 입력 필드 이름표 (`for` 속성으로 연결)
- `<textarea>`: 다중행 텍스트 입력
- `<select>` / `<option>`: 드롭다운 선택 메뉴
- `<button>`: 클릭 가능한 버튼

= 6. 미디어 태그

- `<img>`: 이미지 표시 (`src`, `alt` 필수)
- `<audio>` / `<video>`: 오디오/비디오 재생 (`controls` 속성)
- `<source>`: 미디어 자원 경로 지정

= 7. 주요 공통 속성 (Attributes)

- `id`: 고유 식별자
- `class`: 스타일/스크립트용 그룹 식별자
- `style`: 인라인 CSS 스타일
- `title`: 요소 추가 정보 (툴팁 표시)
- `data-*`: 사용자 정의 데이터 저장
- `disabled`: 요소 비활성화
- `placeholder`: 입력 힌트 메시지
- `required`: 필수 입력 항목 지정
