#import "./templates/conf.typ": *

#show: template.with(
  title: "Flox 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. Flox 개요

Flox는 Nix 기반 패키지 및 환경 관리자. 재현 가능한 격리된 개발 환경을 구축하고 공유하는 데 최적화됨.

== 핵심 개념: 환경 (Environment)
프로젝트에 필요한 패키지, 도구, 변수 등을 격리된 공간에 구성. 컨테이너가 아닌 하위 셸 기반으로 동작함.

= 2. 매니페스트 (Manifest)

`manifest.toml` 파일을 통해 선언적으로 환경 정의.

```toml
[install]
cowsay = "github:flox-examples/cowsay"

[profile]
alias l="ls -alh"
```

= 3. 기본 워크플로우

- 환경 초기화: `flox init`
- 패키지 검색: `flox search [name]`
- 패키지 설치: `flox install [name]`
- 환경 활성화: `flox activate`
- 설치 목록 확인: `flox list`
- 환경 편집: `flox edit`
- 환경 종료: `exit` 또는 `Ctrl-D`

= 4. 환경 공유

- FloxHub 푸시: `flox push`
- 환경 가져오기: `flox pull`

= 5. 추가 정보

- 공식 문서: https://flox.dev/docs/
- 리포지토리: https://github.com/flox/flox
