#import "./templates/conf.typ": *

#show: template.with(
  title: "CSS3 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 선택자 (Selectors)

- 기본: `*` (전체), `element` (태그), `.class` (클래스), `#id` (아이디)
- 조합:
  - `A B`: 자손 (모든 하위)
  - `A > B`: 자식 (직계 하위)
  - `A + B`: 인접 형제 (바로 뒤)
  - `A ~ B`: 일반 형제 (뒤에 오는 모든)
- 가상 클래스: `:hover` (마우스 오버), `:focus` (포커스), `:nth-child(n)` (순서)
- 가상 요소: `::before` / `::after` (앞/뒤에 콘텐츠 삽입)

= 2. 박스 모델 (Box Model)

- `width` / `height`: 콘텐츠 영역 크기
- `padding`: 테두리 안쪽 여백
- `border`: 테두리 선
- `margin`: 테두리 바깥쪽 여백
- `box-sizing`:
  - `content-box`: 너비에 padding/border 미포함 (기본)
  - `border-box`: 너비에 padding/border 포함 (권장)

= 3. 레이아웃 (Layout)

== Display & Position
- `display`: `block`, `inline`, `inline-block`, `none` (숨김)
- `position`:
  - `static`: 기본 위치
  - `relative`: 현재 위치 기준 상대 이동
  - `absolute`: 상위 요소 기준 절대 위치
  - `fixed`: 브라우저 창 기준 고정
  - `sticky`: 스크롤에 따라 고정/해제

== Flexbox (1차원)
- 컨테이너: `flex-direction`, `justify-content` (주축 정렬), `align-items` (교차축 정렬), `gap`
- 아이템: `flex-grow` (확장), `flex-shrink` (축소), `order` (순서)

== Grid (2차원)
- 컨테이너: `grid-template-columns/rows`, `justify-items`, `align-items`
- 아이템: `grid-column`, `grid-row`

= 4. 타이포그래피 (Typography)

- `font-family`: 글꼴
- `font-size`: 크기
- `font-weight`: 굵기
- `text-align`: 정렬 (`left`, `center`, `right`)
- `line-height`: 줄 간격
- `text-decoration`: 장식 (`none`, `underline`)

= 5. 전환 및 애니메이션

- `transition`: 속성 변경 시 부드러운 효과 적용
- `@keyframes`: 애니메이션 단계 정의
- `animation`: 정의된 키프레임 적용 및 제어

= 6. 미디어 쿼리 (Media Queries)

반응형 디자인 구현
```css
@media (max-width: 600px) {
  /* 화면 너비 600px 이하 스타일 */
}
```

= 7. 단위 (Units)

- 절대 단위: `px`
- 상대 단위: `%` (부모 대비), `em` (부모 폰트 대비), `rem` (루트 폰트 대비), `vw/vh` (화면 너비/높이 대비)
