#import "./templates/conf.typ": *

#show: template.with(
  title: "Julia 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 기본 문법

== 변수 및 함수

```julia
# 변수 정의
x, y, z = 10, "Julia", 3.14

# 함수 정의
function greet(name)
  return "Hello, $name!"
end

# 단축형 함수 정의
add(a, b) = a + b
```

== 제어 흐름

=== If-Else 조건문

```julia
if a > 0
  println("양수")
elseif a < 0
  println("음수")
else
  println("0")
end
```

=== 루프 (Loops)

```julia
# For 루프
for i in 1:5
  println(i)
end

# While 루프
while i <= 5
  println(i); i += 1
end
```

= 데이터 구조

== 배열 및 딕셔너리

```julia
# 배열 (1차원 및 다차원)
arr = [1, 2, 3]
matrix = [1 2; 3 4]

# 딕셔너리
dict = Dict("name" => "Julia", "v" => 1.9)
```

== 문자열 및 튜플

```julia
# 문자열 연결(*) 및 보간($)
combined = "Hello" * " " * "Julia"
message = "Name: $(name)"

# 튜플 및 언패킹
tup = (1, "hi", 3.14)
a, b, c = tup
```

== 구조체 (Structs)

```julia
struct Point
  x::Int
  y::Int
end
p = Point(10, 20)
```

= 고급 기능

== 에러 처리 (Try-Catch)

```julia
try
  return a / b
catch e
  println("에러 발생: $e")
finally
  println("항상 실행")
end
```

== 모듈 및 브로드캐스팅

```julia
# 모듈 사용
using LinearAlgebra

# 브로드캐스팅 (점 연산자)
arr = [1, 2, 3]
result = arr .+ 10 # 각 요소에 10 합산
```

== 컴프리헨션

```julia
# 배열 컴프리헨션
squares = [i^2 for i in 1:5]

# 딕셔너리 컴프리헨션
d = Dict(i => i^2 for i in 1:3)
```

= 유용한 명령어

```julia
# 도움말 확인: REPL에서 '?' 입력 후 명령어 입력
?println

# 패키지 관리 (Pkg)
using Pkg
Pkg.add("PackageName") # 패키지 추가
Pkg.status()           # 상태 확인
```

