#import "./templates/conf.typ": *

#show: template.with(
  title: "Java 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 기본 구조 및 실행

Java 프로그램은 클래스 내부 `main` 메서드에서 시작

```java
public class Hello {
    public static void main(String[] args) {
        System.out.println("Hello, Java!");
    }
}
```
- 컴파일: `javac Hello.java` -> `Hello.class` 생성
- 실행: `java Hello`

= 2. 변수와 데이터 타입

- 기본 타입 (Primitive):
  - 정수: `byte`, `short`, `int`, `long`
  - 실수: `float`, `double`
  - 기타: `char` (문자), `boolean` (불리언)
- 참조 타입 (Reference): `String`, `Array`, `Class`, `Interface` 등
- 변수 선언: `타입 변수명 = 값;`
- 상수 정의: `final double PI = 3.14;`
- 타입 변환: `(타입)값` (명시적 캐스팅)

= 3. 제어 흐름

- 조건문: `if-else`, `switch` (Java 12+ 표현식 지원)
- 루프:
  - 일반 `for`: `for (int i=0; i<5; i++) { ... }`
  - 향상된 `for`: `for (타입 요소 : 컬렉션) { ... }`
  - `while`, `do-while`

= 4. 객체 지향 프로그래밍 (OOP)

- 클래스 정의:
  ```java
  public class Car {
      private String model; // 필드
      public Car(String model) { this.model = model; } // 생성자
      public void drive() { ... } // 메서드
  }
  ```
- 상속 (`extends`): 부모 클래스 자원 재사용
- 인터페이스 (`interface`): 구현 명세 정의 (`implements`로 구현)

= 5. 컬렉션 프레임워크 (`java.util`)

- `ArrayList`: 가변 크기 리스트
- `HashMap`: 키-값 쌍 저장소
- `HashSet`: 중복 불허 집합

= 6. 예외 처리 (Exception)

- `try-catch-finally`: 예외 발생 대응 및 자원 해제
- `throws`: 메서드 외부로 예외 전가
- `try-with-resources`: 자동 자원 반납 (Java 7+)

= 7. 스트림 API 및 람다 (Java 8+)

컬렉션 데이터의 선언적 처리
```java
List<String> list = List.of("a", "b", "c");
List<String> res = list.stream()
                       .filter(s -> s.startsWith("a"))
                       .map(String::toUpperCase)
                       .collect(Collectors.toList());
```

= 8. 최신 주요 기능

- Record (Java 14+): 데이터 불변 객체 간소화 정의
- Sealed Classes (Java 15+): 상속 가능 클래스 제한
- Text Blocks (Java 13+): 다중행 문자열 지원
- Optional: NullPointerException 방지를 위한 래퍼 객체

