#import "./templates/conf.typ": *

#show: template.with(
  title: "Bash 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 입출력 및 변수

- `echo`: 문자열 출력 (`-e` 이스케이프 지원)
- `printf`: 형식화된 출력
- `read`: 사용자 입력 수신
- 변수 선언: `name="val"` (공백 금지)
- 변수 사용: `$name` 또는 `${name}`
- 명령어 치환: `$(cmd)`
- 환경 변수: `export NAME="val"`
- 특수 변수:
  - `$0`: 스크립트명
  - `$1, $2...`: 위치 인수
  - `$#`: 인수 개수
  - `$@`: 모든 인수 (개별 문자열)
  - `$?`: 종료 코드 (0: 성공)
  - `$$`: 현재 PID

= 2. 조건문

- `if [[ cond ]]; then ... fi`: 조건문 (확장형 권장)
- `case $var in pat) ... ;; esac`: 패턴 매칭

== 주요 비교 연산 (`[[ ... ]]`)
- 문자열: `==`, `!=`, `-z` (빈 문자열), `-n` (비지 않음)
- 정규식: `=~`
- 숫자: `-eq`, `-ne`, `-lt`, `-gt` (또는 `(( ... ))` 사용)
- 파일: `-e` (존재), `-f` (파일), `-d` (디렉토리), `-x` (실행 가능)

= 3. 반복문

- `for var in list; do ... done`: 목록 순회
- `for (( i=0; i<10; i++ ))`: C 스타일 루프
- `while cond; do ... done`: 조건 충족 시 반복
- `break / continue`: 루프 제어

= 4. 함수

```bash
my_func() {
    local var=$1 # 지역 변수
    echo $var
    return 0     # 종료 코드
}
my_func "arg"    # 호출
```

= 5. 배열 (Arrays)

- 선언: `arr=("a" "b")`
- 접근: `${arr[0]}` (요소), `${arr[@]}` (전체), `${#arr[@]}` (길이)
- 연관 배열: `declare -A map; map["k"]="v"`

= 6. 문자열 조작

- `${#s}`: 문자열 길이
- `${s:pos:len}`: 부분 문자열 추출
- `${s#pat}` / `${s%pat}`: 앞/뒤 패턴 제거 (최단 일치)
- `${s##pat}` / `${s%%pat}`: 앞/뒤 패턴 제거 (최장 일치)
- `${s/pat/rep}`: 패턴 치환

= 7. 셸 확장

- `~`: 홈 디렉토리
- `*`, `?`: 경로 확장 (Globbing)
- `{a,b}`: 중괄호 확장
- `$((...))`: 산술 연산 확장

= 8. 스크립팅 설정

- `set -e`: 에러 발생 시 즉시 종료
- `set -u`: 미정의 변수 사용 시 에러
- `set -o pipefail`: 파이프라인 에러 감지 강화
- `trap 'cmd' EXIT`: 종료 시 정리 작업 수행
