#import "./templates/conf.typ": *

#show: template.with(
  title: "Ruby 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 기본 구문 및 변수

- 주석: `#` 사용
- 출력: `puts` (줄바꿈 포함), `print` (미포함)
- 변수: `var = val` (타입 선언 불필요)
- 상수: 대문자 시작 (`CONST = 3.14`)
- 심볼: `:symbol` (불변 문자열, 메모리 효율적)
- 문자열 보간: `"#{var}"`

= 2. 제어 흐름

- `if-elsif-else`: 조건문
- `unless`: `if` 반대 조건 (`unless cond ... end`)
- 후행 조건문: `puts "ok" if true`
- `case-when`: 패턴 매칭 기반 조건문
- 루프: `while`, `until`, `for`

= 3. 메서드 (Methods)

- 정의:
  ```ruby
  def func(a, b="def")
    a + b # 마지막 표현식 반환
  end
  ```
- 관례: `?` (불리언 반환), `!` (원본 수정/위험 작업)

= 4. 블록, Proc, 람다

- 블록 (Block): `do...end` 또는 `{ ... }`
- `yield`: 메서드 내 블록 실행
- Proc: 블록의 객체화 (`Proc.new { ... }`)
- 람다 (Lambda): 인수 수에 엄격한 Proc (`->(x) { ... }`)

= 5. 클래스와 객체

- 정의:
  ```ruby
  class MyClass
    attr_accessor :name # getter/setter
    def initialize(n); @name = n; end # 생성자
  end
  ```
- 상속: `class Sub < Base`
- 믹스인 (Mixin): `include ModuleName`

= 6. 주요 컬렉션 및 Enumerable

- Array: `arr = [1, 2]`, `arr << 3` (추가)
- Hash: `{ "k" => "v" }` 또는 `{ k: "v" }` (심볼 키)
- Enumerable 메서드:
  - `map`: 변형된 새 배열 반환
  - `select`: 조건 일치 요소 추출
  - `reduce`: 누적 연산 수행
  - `any?`, `all?`: 조건 만족 여부 확인

= 7. 패키지 관리

- RubyGems: `gem install [name]`
- Bundler: `Gemfile` 기반 의존성 관리 (`bundle install`)

= 8. 예외 처리

- `begin...rescue...ensure...end` 구문 사용

