#import "./templates/conf.typ": *

#show: template.with(
  title: "C++ 치트시트",
  header: [#datetime.today().display()],
  footer: "generated by Gemini CLI",
)

= 1. 기본 구조 및 컴파일

```cpp
#include <iostream>
int main() {
    std::cout << "Hello, C++!" << std::endl;
    return 0;
}
```
- 컴파일: `g++ -o hello hello.cpp`
- 실행: `./hello`

= 2. 변수와 타입

- 기본 타입: `int`, `double`, `float`, `char`, `bool`
- 문자열: `std::string`
- 상수: `const`
- 타입 추론: `auto`
- 연산자: 산술, 관계, 논리 (C계열 공통)

= 3. 제어 흐름

- 조건문: `if-else`, `switch`
- 루프:
  - 일반 `for`: `for (int i=0; i<5; ++i)`
  - 범위 기반 `for`: `for (int x : vec)`
  - `while`

= 4. 함수

- 정의: `ret_type func(params) { ... }`
- 오버로딩: 이름은 같으나 매개변수가 다른 함수 정의 가능
- 기본 매개변수: `void f(int n=10);`

= 5. 포인터와 참조

- 포인터 (`*`): 메모리 주소 저장 및 접근
- 참조 (`&`): 변수의 별칭 (초기화 필수)

= 6. 클래스와 객체

- 클래스 정의:
  ```cpp
  class MyClass {
  public:
      MyClass(int v) : field(v) {} // 생성자
      void method() { ... }        // 메서드
  private:
      int field;                   // 필드
  };
  ```
- 상속: `class Derived : public Base { ... };`

= 7. 표준 템플릿 라이브러리 (STL)

- `std::vector`: 동적 배열
- `std::map`: 정렬된 키-값 쌍 (트리 기반)
- `std::unordered_map`: 해시 테이블 기반 매핑
- `std::string`: 문자열 클래스
- 알고리즘: `sort`, `find`, `for_each` (`<algorithm>` 헤더)

= 8. 입출력

- 콘솔: `std::cin` (입력), `std::cout` (출력)
- 파일 (`<fstream>`): `std::ifstream` (읽기), `std::ofstream` (쓰기)

= 9. 메모리 관리 (스마트 포인터)

- `std::unique_ptr`: 독점 소유권
- `std::shared_ptr`: 참조 카운팅 기반 공유 소유권
- `std::weak_ptr`: 순환 참조 방지용 약한 참조

= 10. 모던 C++ 주요 기능 (C++11/14/17/20)

- 이동 의미론: `std::move`를 통한 자원 효율적 이동
- 람다식: `[capture](params) { body }`
- 가변 인수 템플릿: `template<typename... Args>`
- 구조화 바인딩: `auto [a, b] = my_pair;`
- 컨셉 (Concepts): 템플릿 제약 조건 정의 (C++20)

