name: Publish Website

on:
  push:
    branches: main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.10.1
        with:
          pixi-version: v0.39.0
          cache: true

      - name: Build PDFs
        run: pixi run build

      - name: Build Website
        run: pixi run site-build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: site_output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
